const fs = require('fs');
const g = JSON.parse(fs.readFileSync('data/guides.json','utf8'));

// live-sound-pa
const pa = g.find(x => x.id === 'live-sound-pa');
pa.sections[0].content = '<p><strong>Powered speakers have built-in amplification; passive speakers need an external amp.</strong> For small to medium venues, powered speakers are simpler \u2014 just plug in and mix. No amp racks, no speaker cables to calculate.</p><p><strong>Powered speakers:</strong> The <strong>QSC K12.2</strong> ($1,000/ea) is the gold standard for reliability and sound quality. The <strong>EV ZLX-12P-G2</strong> ($599/ea) punches above its price with clear, detailed highs and a 12" woofer that handles everything from vocals to full bands. The <strong>Yamaha DXR12mkII</strong> ($899/ea) offers 1100W of Class D power with intelligent DSP that protects the speaker while maintaining clarity at high volumes.</p><p><strong>All-in-one PA systems:</strong> The <strong>Yamaha Stagepas 1K MKII</strong> ($1,232) is a column PA system with a 5-channel mixer, 1000W of power, and app control \u2014 perfect for solo artists and small bands who want setup in minutes. The <strong>JBL PRX ONE</strong> ($1,899) delivers 2000W with a 7-channel mixer and built-in effects for more demanding gigs.</p><p>Passive speakers with a separate amplifier give you more control and are easier to service in large installations. For most bands and small venues, powered is the way to go.</p>';

pa.sections[0].content_es = '<p><strong>Los parlantes activos tienen amplificaci\u00f3n integrada; los parlantes pasivos necesitan un amplificador externo.</strong> Para espacios peque\u00f1os y medianos, los parlantes activos son m\u00e1s simples \u2014 solo conecta y mezcla. Sin racks de amplificadores, sin cables de parlante que calcular.</p><p><strong>Parlantes activos:</strong> El <strong>QSC K12.2</strong> ($1,000/ea) es el est\u00e1ndar de oro en confiabilidad y calidad de sonido. El <strong>EV ZLX-12P-G2</strong> ($599/ea) supera su precio con agudos claros y detallados y un parlante de 12" que maneja todo desde voces hasta bandas completas. El <strong>Yamaha DXR12mkII</strong> ($899/ea) ofrece 1100W de potencia Clase D con DSP inteligente que protege el parlante mientras mantiene claridad a altos vol\u00famenes.</p><p><strong>Sistemas PA todo en uno:</strong> El <strong>Yamaha Stagepas 1K MKII</strong> ($1,232) es un sistema PA de columna con mezcladora de 5 canales, 1000W de potencia y control por app \u2014 perfecto para artistas solistas y bandas peque\u00f1as que quieren configuraci\u00f3n en minutos. El <strong>JBL PRX ONE</strong> ($1,899) ofrece 2000W con una mezcladora de 7 canales y efectos integrados para presentaciones m\u00e1s exigentes.</p><p>Los parlantes pasivos con un amplificador separado te dan m\u00e1s control y son m\u00e1s f\u00e1ciles de servicio en instalaciones grandes. Para la mayor\u00eda de bandas y espacios peque\u00f1os, activo es el camino a seguir.</p>';

// best-digital-mixers
const mx = g.find(x => x.id === 'best-digital-mixers');
mx.sections[0].content = '<p><strong>Budget digital mixers deliver features that used to cost $5,000+.</strong> The <strong>Behringer X Air XR18</strong> ($700) is the budget king \u2014 18 channels, wireless control via iPad, built-in effects, and USB recording. The <strong>Tascam Model 12</strong> ($599) combines a digital mixer with a DAW recorder, giving you analog-style workflow with digital flexibility.</p><p>For professional applications, the <strong>Behringer X32 Compact</strong> ($1,999) offers 40 channels with premium Midas preamps and a layout that has become the standard for live sound. The <strong>Allen & Heath CQ-18T</strong> ($1,299) delivers 16 mic preamps with automatic gain staging and a touchscreen interface that is genuinely intuitive.</p><p><strong>High-end options:</strong> The <strong>Korg SoundLink MW-1608</strong> ($1,000) is an analog-style digital mixer with Korg\'s renowned AIrek circuits for warm, musical sound. The <strong>Midas M32R LIVE</strong> ($2,499) packs Midas-quality preamps into a compact 16-channel frame with 40-bit floating-point processing.</p>';

mx.sections[0].content_es = '<p><strong>Las mezcladoras digitales econ\u00f3micas ofrecen caracter\u00edsticas que antes costaban m\u00e1s de $5,000.</strong> El <strong>Behringer X Air XR18</strong> ($700) es el rey econ\u00f3mico \u2014 18 canales, control inal\u00e1mbrico v\u00eda iPad, efectos integrados y grabaci\u00f3n USB. El <strong>Tascam Model 12</strong> ($599) combina una mezcladora digital con un grabador DAW, d\u00e1ndote flujo de trabajo estilo anal\u00f3gico con flexibilidad digital.</p><p>Para aplicaciones profesionales, el <strong>Behringer X32 Compact</strong> ($1,999) ofrece 40 canales con preamps Midas premium y una distribuci\u00f3n que se ha convertido en el est\u00e1ndar para sonido en vivo. El <strong>Allen & Heath CQ-18T</strong> ($1,299) ofrece 16 preamps de micr\u00f3fono con ganancia autom\u00e1tica y una interfaz con pantalla táctil que es genuinamente intuitiva.</p><p><strong>Opciones de gama alta:</strong> El <strong>Korg SoundLink MW-1608</strong> ($1,000) es una mezcladora digital estilo anal\u00f3gico con los circuitos AIrek de renombre de Korg para un sonido cálido y musical. El <strong>Midas M32R LIVE</strong> ($2,499) incluye preamps de calidad Midas en un chasis compacto de 16 canales con procesamiento de punto flotante de 40 bits.</p>';

mx.sections[1].content = '<p><strong>Studio vs Live Digital Mixers:</strong> Studio mixers like the <strong>SSL BiG SiX</strong> ($3,299) focus on premium preamps, analog summing, and pristine signal paths. Live mixers prioritize channel count, rugged construction, and real-time control.</p><p>The <strong>Tascam Model 12</strong> bridges both worlds \u2014 it works as a studio mixer with DAW integration and as a live mixer with dual-purpose preamps. For pure studio work, the SSL BiG SiX is unmatched. For live sound, the XR18 and X32 dominate because they offer more channels per dollar and wireless control that studio mixers don\'t need.</p>';

mx.sections[1].content_es = '<p><strong>Mezcladoras Digitales de Estudio vs En Vivo:</strong> Las mezcladoras de estudio como el <strong>SSL BiG SiX</strong> ($3,299) se enfocan en preamps premium, suministro anal\u00f3gico y rutas de se\u00f1al prístinas. Las mezcladoras en vivo priorizan cantidad de canales, construcci\u00f3n resistente y control en tiempo real.</p><p>El <strong>Tascam Model 12</strong> conecta ambos mundos \u2014 funciona como mezcladora de estudio con integraci\u00f3n DAW y como mezcladora en vivo con preamps de doble prop\u00f3sito. Para trabajo puro de estudio, el SSL BiG SiX es inigualable. Para sonido en vivo, el XR18 y X32 dominan porque ofrecen m\u00e1s canales por d\u00f3lar y control inal\u00e1mbrico que las mezcladoras de estudio no necesitan.</p>';

// daw-guide
const daw = g.find(x => x.id === 'daw-guide');
daw.sections[0].content = '<p><strong>Don\'t overthink your first DAW choice.</strong> GarageBand (free on Mac) and Cakewalk (free on Windows) are excellent starting points. They have all the basic tools you need to learn production.</p><p>When you\'re ready to upgrade, the main options are: <strong>Ableton Live 12 Suite</strong> ($749) for electronic music and live performance \u2014 its Session View lets you launch clips and arrange ideas in real-time. <strong>FL Studio Producer Edition</strong> ($199) is the go-to for beatmakers and hip-hop producers \u2014 its step sequencer and Piano Roll are legendary. <strong>Logic Pro</strong> ($199, Mac only) offers pro-level features at a consumer price with incredible built-in instruments and effects.</p><p><strong>Professional options:</strong> <strong>Avid Pro Tools Studio</strong> ($299/yr) remains the industry standard for recording and mixing \u2014 if you plan to work in a professional studio, this is what you will encounter. <strong>Steinberg Cubase Pro 15</strong> ($579) excels at MIDI sequencing and orchestral composition. <strong>Reason Studios Reason 14</strong> ($499) offers a unique rack-based workflow with modular synth routing that inspires sound design.</p>';

daw.sections[0].content_es = '<p><strong>No pienses demasiado en tu primera elecci\u00f3n de DAW.</strong> GarageBand (gratis en Mac) y Cakewalk (gratis en Windows) son excelentes puntos de partida. Tienen todas las herramientas b\u00e1sicas que necesitas para aprender producci\u00f3n.</p><p>Cuando est\u00e9s listo para mejorar, las principales opciones son: <strong>Ableton Live 12 Suite</strong> ($749) para m\u00fAsica electr\u00f3nica y actuaci\u00f3n en vivo \u2014 su Session View te permite lanzar clips y organizar ideas en tiempo real. <strong>FL Studio Producer Edition</strong> ($199) es el favorito para beatmakers y productores de hip-hop \u2014 su secuenciador de pasos y Piano Roll son legendarios. <strong>Logic Pro</strong> ($199, solo Mac) ofrece funciones de nivel profesional a precio de consumidor con instrumentos y efectos integrados incre\u00edbles.</p><p><strong>Opciones profesionales:</strong> <strong>Avid Pro Tools Studio</strong> ($299/a\u00f1o) sigue siendo el est\u00e1ndar de la industria para grabaci\u00f3n y mezcla \u2014 si planeas trabajar en un estudio profesional, esto es lo que encontrar\u00e1s. <strong>Steinberg Cubase Pro 15</strong> ($579) sobresale en secuenciaci\u00f3n MIDI y composici\u00f3n orquestal. <strong>Reason Studios Reason 14</strong> ($499) ofrece un flujo de trabajo \u00fanico basado en rack con enrutamiento de sintetizador modular que inspira el dise\u00f1o de sonido.</p>';

daw.sections[1].content = '<p><strong>DAW-Specific Workflows:</strong> Each DAW has a unique approach to music production. <strong>Ableton Live</strong> excels at clip-based arrangement and real-time performance. <strong>FL Studio</strong> dominates beat production with its pattern-based workflow. <strong>Logic Pro</strong> combines the best of both worlds with Tracks View and Live Loops. <strong>Pro Tools</strong> is unmatched for audio editing and mixing precision. <strong>Cubase</strong> offers the most comprehensive MIDI tools. <strong>Reason</strong> provides a modular environment that appeals to sound designers.</p><p>Most professional producers own multiple DAWs and use each for its strengths. Start with one, learn it deeply, and add others as your needs evolve.</p>';

daw.sections[1].content_es = '<p><strong>Flujos de Trabajo Espec\u00edficos de Cada DAW:</strong> Cada DAW tiene un enfoque \u00fanico para la producci\u00f3n musical. <strong>Ableton Live</strong> sobresale en arreglo basado en clips y actuaci\u00f3n en tiempo real. <strong>FL Studio</strong> domina la producci\u00f3n de beats con su flujo de trabajo basado en patrones. <strong>Logic Pro</strong> combina lo mejor de ambos mundos con Tracks View y Live Loops. <strong>Pro Tools</strong> es inigualable para edici\u00f3n de audio y precisi\u00f3n de mezcla. <strong>Cubase</strong> ofrece las herramientas MIDI m\u00e1s completas. <strong>Reason</strong> proporciona un entorno modular que atrae a los dise\u00f1adores de sonido.</p><p>La mayor\u00eda de los productores profesionales poseen m\u00faltiples DAWs y usan cada uno por sus fortalezas. Comienza con uno, aprende profundamente y agrega otros a medida que evolucionen tus necesidades.</p>';

fs.writeFileSync('data/guides.json', JSON.stringify(g,null,2),'utf8');
console.log('Fixed live-sound-pa, best-digital-mixers, daw-guide');
