var fs = require('fs');
var guides = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));

var fixCount = 0;

function fixField(obj, field, replacements) {
  if (!obj[field]) return;
  var original = obj[field];
  replacements.forEach(function(r) {
    obj[field] = obj[field].replace(new RegExp(r[0], 'gi'), r[1]);
  });
  if (obj[field] !== original) fixCount++;
}

var enReplacements = [
  // AI buzzwords → natural alternatives
  ['gold standard', 'industry reference'],
  ['the gold standard', 'the industry reference'],
  ['Gold Standard', 'Industry Reference'],
  ['undisputed kings', 'top picks'],
  ['undisputed king', 'top pick'],
  ['best-in-class', 'top-performing'],
  ['Best-in-Class', 'Top-Performing'],
  ['cutting-edge', 'modern'],
  ['Cutting-Edge', 'Modern'],
  ['state-of-the-art', 'advanced'],
  ['State-of-the-Art', 'Advanced'],
  ['world-class', 'high-end'],
  ['World-Class', 'High-End'],
  ['top-tier', 'high-end'],
  ['Top-Tier', 'High-End'],
  ['game-changer', 'standout option'],
  ['game changer', 'standout option'],
  ['Game-Changer', 'Standout Option'],
  ['industry-leading', 'leading'],
  ['Industry-Leading', 'Leading'],
  ['premium-grade', 'high-quality'],
  ['Premium-Grade', 'High-Quality'],
  ['revolutionary', 'new'],
  ['Revolutionary', 'New'],
  ['unmatched', 'hard to beat'],
  ['Unmatched', 'Hard to beat'],
  ['unparalleled', 'hard to beat'],
  ['Unparalleled', 'Hard to beat'],
  ['exceptional', 'strong'],
  ['Exceptional', 'Strong'],
  ['incredible', 'great'],
  ['Incredible', 'Great'],
  ['ultimate', 'best'],
  ['Ultimate', 'Best'],
  ['transform your sound', 'change your tone'],
  ['transform your workflow', 'speed up your workflow'],
  ['transforms your workflow', 'speeds up your workflow'],
  ['transforms the', 'turns the'],
  ['seamlessly', 'easily'],
  ['Seamlessly', 'Easily'],
  ['seamless integration', 'easy integration'],
  ['seamless', 'smooth'],
  ['unlocks endless', 'gives you many'],
  ['Unlock', 'Try'],
  ['journey', 'setup'],
  ['Journey', 'Setup'],
  ['harness', 'use'],
  ['leverage', 'use'],
  ['elevate', 'improve'],
  ['Elevate', 'Improve'],
  ['empower', 'help'],
  ['delve', 'look'],
  ['Discover', 'See'],
  ['discover', 'see'],
  ['whether you are a beginner or a pro', 'whether you are new or experienced'],
  ['Whether you are a beginner or a pro', 'Whether you are new or experienced'],
  ['whether you are a beginner or professional', 'whether you are new or experienced'],
  ['Whether you are a beginner or professional', 'Whether you are new or experienced'],
  ['in the world of', 'in'],
  ['In the world of', 'In'],
  ['at the end of the day', 'overall'],
  ['At the end of the day', 'Overall'],
  ['in a class of its own', 'very competitive'],
  ['the most recorded', 'one of the most recorded'],
  ['The most recorded', 'One of the most recorded'],
  ['in history', 'ever'],
  ['on the planet', 'available'],
  ['on earth', 'available'],
  ['ever made', 'available'],
  ['ever built', 'available'],
  ['in existence', 'available'],
  ['in the business', 'available'],
  ['the definitive', 'a strong'],
  ['The definitive', 'A strong'],
  ['the definitive choice', 'a strong choice'],
  ['the smartest', 'a smart'],
  ['The smartest', 'A smart'],
  ['the safest', 'a solid'],
  ['The safest', 'A solid'],
  ['the most trusted', 'a widely used'],
  ['The most trusted', 'A widely used'],
  ['the go-to choice', 'a popular choice'],
  ['The go-to choice', 'A popular choice'],
  ['the best-selling', 'a popular'],
  ['The best-selling', 'A popular'],
  ['the most popular', 'a popular'],
  ['The most popular', 'A popular'],
  ['brutally honest', 'thorough'],
  ['Brutally honest', 'Thorough'],
  ['you can\'t go wrong', 'either option works well'],
  ['You can\'t go wrong', 'Either option works well'],
  ['step up', 'upgrade'],
  ['Step up', 'Upgrade'],
  ['Step Up', 'Upgrade'],
  ['I\'ve personally', 'I have'],
  ['I\'ve spent countless', 'I have spent many'],
  ['I\'ve used', 'I have used'],
  ['I\'ve recommended', 'I recommend'],
  ['more times than I can count', 'many times'],
  ['the results are genuinely impressive', 'the results are clean'],
  ['this is the move', 'this is worth considering'],
  ['I\'ve tracked', 'I have tracked'],
  ['I wouldn\'t run', 'I do not run'],
  ['hands down', ''],
  ['for good reason', ''],
  ['for a good reason', ''],
  ['without further ado', ''],
  ['I\'ve learned', 'I learned'],
  ['I\'ve found', 'I found'],
  ['I\'ve mixed', 'I mixed'],
  ['I\'ve A/B', 'I compared'],
  ['I keep a pair', 'I have a pair'],
  ['I keep four', 'I have four'],
  ['I use something', 'I use'],
  ['I use the', 'I use'],
  ['I recommend them', 'They work well'],
  ['I recommend', 'A good choice is'],
  ['my secret weapon', 'a great tool'],
  ['These are my go-to', 'A reliable option is'],
  ['these are the monitors that made me', 'these monitors'],
  ['I\'ve never found anything that does the job better', 'they hold up well'],
  ['wouldn\'t run a studio without both', 'both are reliable'],
  ['I wouldn\'t run a studio without both', 'both are reliable'],
  ['the same DSP magic', 'the same DSP processing'],
  ['DSP magic', 'DSP processing'],
  ['built-in DSP magic', 'built-in DSP processing'],
  ['godsend', 'great help'],
  ['a godsend', 'a great help'],
  ['made me rethink what', 'challenged my view of'],
  ['belies its price', 'looks more expensive than it is'],
  ['the quintessential', 'a classic'],
  ['The quintessential', 'A classic'],
  ['capture inspiration wherever it strikes', 'record ideas on the go'],
  ['pro quality without the pro price tag', 'good quality at a lower price'],
  ['punches well above its weight class', 'performs better than expected'],
  ['Italian engineering in a box that never sounds slow', 'fast and responsive Italian engineering'],
  ['the safest choice if your gig list is full of celebrations', 'a solid pick for live events'],
  ['in this business, that\'s priceless', 'that matters for live work'],
  ['made more hit records than anything else', 'one of the most used mics'],
  ['the most recorded microphone in history', 'one of the most recorded microphones'],
  ['the most recorded electric guitar in history', 'one of the most recorded electric guitars'],
  ['the most recorded overdrive pedal in history', 'one of the most recorded overdrive pedals'],
  ['the most recorded overdrive pedal', 'one of the most recorded overdrive pedals'],
  ['on more hit records than any other pedal ever made', 'widely used in professional recordings'],
  ['on more hit records than anything else in history', 'widely used in professional recordings'],
  ['used on more hit records than anything else in history', 'widely used in professional recordings'],
  ['the best investment a working guitarist can make', 'a solid choice for gigging guitarists'],
  ['the best money you\'ll ever spend on your guitar tone', 'a good value for your guitar tone'],
  ['the last mixing bundle you\'ll ever buy', 'a complete mixing bundle'],
  ['the most musical delay plugin ever made', 'a very musical delay plugin'],
  ['the most creative, most inspiring bundle in the entire plugin world', 'a very creative effects bundle'],
  ['the most authentic analog experience in the plugin world', 'a convincing analog emulation'],
  ['the most powerful sampler and drum computer I\'ve ever used', 'a powerful sampler and drum computer'],
  ['the most intuitive groovebox I\'ve ever used', 'an easy-to-use groovebox'],
  ['the most powerful compact looper ever made', 'a powerful compact looper'],
  ['the simplest and best-selling looper ever made', 'a simple and popular looper'],
  ['the most powerful compact multi-effects ever made', 'a powerful compact multi-effects'],
  ['the most powerful all-in-one column array system in its class', 'a powerful column array system'],
  ['the most powerful speaker in its price class by a wide margin', 'a powerful speaker for the price'],
  ['the most versatile small amp on the market', 'a versatile small amp'],
  ['the most portable full-featured digital mixer ever made', 'a portable full-featured digital mixer'],
  ['the most accurate monitor and the gateway to genuine pro reference accuracy', 'an accurate monitor for pro reference'],
  ['the closest thing to pro reference accuracy without the pro reference price', 'close to pro reference accuracy at a lower price'],
  ['reference-grade monitoring does not need a big box', 'good monitoring does not need a big box'],
  ['the most technically ambitious monitor in this guide', 'a technically advanced monitor'],
  ['the scientific gold standard for headphone frequency response', 'a well-known reference for frequency response'],
  ['in a league of its own', 'very competitive'],
  ['nothing else in this price range offers this combination', 'rare at this price'],
  ['stand alone in its class', 'stand out in its category'],
  ['genuinely best-in-class', 'top-performing'],
  ['cleaner than interfaces twice the price', 'clean at this price point'],
  ['deliver stunning quality', 'deliver good quality'],
  ['deliver exceptional value', 'offer good value'],
  ['offers exceptional', 'offers strong'],
  ['delivers exceptional', 'delivers strong'],
  ['with exceptional', 'with strong'],
  ['sounds noticeably better than anything in its price range', 'sounds good for the price'],
  ['sounds better than anything in its price range', 'sounds good for the price'],
  ['sounds and plays like guitars costing twice as much', 'sounds good for the price'],
  ['the most recommended beginner electric guitar by educators worldwide', 'a popular beginner guitar among teachers'],
  ['the best entry point into condenser recording on the market', 'a good first condenser mic'],
  ['the best entry point', 'a good starting point'],
  ['the exact processing path I use for professional vocal production', 'a solid vocal processing chain'],
  ['the most natural, neutral open-back reference', 'a natural, neutral open-back'],
  ['the most transparent, musical tuning tool in existence', 'a transparent, musical tuning tool'],
  ['an absolute steal for the quality', 'good value for the quality'],
  ['walk into any professional studio on earth and you\'ll find', 'you will find in most studios'],
  ['Indestructible', 'Durable'],
  ['it\'s, indestructible', 'it\'s durable'],
  ['They\'re, fold flat', 'They fold flat'],
  ['the results are indistinguishable from setups costing five times as much', 'the results are surprisingly good for the price'],
  ['It\'s built like a tank', 'It\'s well-built'],
  ['significantly more premium than its competition', 'noticeably well-built'],
  ['the most characterful interface in the budget category', 'a characterful budget interface'],
  ['in this comprehensive guide', ''],
  ['we\'ll dive deep', 'we cover'],
  ['whether it plugs into USB or XLR', 'with USB connectivity'],
  ['Smart assistants handle gain staging', 'Automatic gain staging handles'],
  ['the same DSP magic', 'the same DSP processing'],
  ['motorized faders transform your workflow', 'motorized faders speed up your workflow'],
  ['out-resolves speakers twice its price', 'performs well for the price'],
  ['the amp that changed the game for budget players', 'a popular amp for budget players'],
  ['the amp is where your tone truly comes alive', 'the amp shapes your tone'],
  ['Truly', 'Really'],
  ['truly comes alive', 'really shines'],
  ['A modest guitar through a great amp can sound incredible', 'A modest guitar through a great amp sounds good'],
  ['Pro-Level', 'Professional'],
  ['pro-level', 'professional'],
  ['reference-grade', 'professional-quality'],
  ['Reference-Grade', 'Professional-Quality'],
  ['priceless', 'valuable'],
  ['That\'s priceless', 'That\'s valuable'],
  ['that\'s priceless', 'that\'s valuable'],
  ['every mix', 'most mixes'],
  ['Every mix', 'Most mixes'],
  ['every studio', 'most studios'],
  ['Every studio', 'Most studios'],
  ['every professional studio', 'most professional studios'],
  ['Every professional studio', 'Most professional studios'],
  ['nothing comes close', 'few match it'],
  ['Nothing comes close', 'Few match it'],
  ['the only choice you\'ll ever need', 'a solid choice'],
  ['will change your life', 'is worth trying'],
  ['will change everything', 'is a big improvement'],
  ['the undisputed king', 'a top pick'],
  ['The undisputed king', 'A top pick'],
  ['the undisputed kings', 'top picks'],
  ['The undisputed kings', 'Top picks'],
];

var esReplacements = [
  ['increíble', 'buena'],
  ['Increíble', 'Buena'],
  ['increíbles', 'buenas'],
  ['Increíbles', 'Buenas'],
  ['excepcional', 'sólida'],
  ['Excepcional', 'Sólida'],
  ['excepcionales', 'sólidos'],
  ['Excepcionales', 'Sólidos'],
  ['revolucionario', 'nuevo'],
  ['Revolucionario', 'Nuevo'],
  ['revolucionaria', 'nueva'],
  ['Revolucionaria', 'Nueva'],
  ['definitivo', 'ideal'],
  ['Definitivo', 'Ideal'],
  ['definitiva', 'ideal'],
  ['Definitiva', 'Ideal'],
  ['definitiva elección', 'buena elección'],
  ['la definitiva', 'una buena'],
  ['el definitivo', 'un buen'],
  ['de clase mundial', 'de alta gama'],
  ['de primer nivel', 'de alta gama'],
  ['vanguardia', 'moderna'],
  ['de vanguardia', 'moderna'],
  ['el estándar de oro', 'la referencia del sector'],
  ['el estándar de oro', 'la referencia del sector'],
  ['el viaje', 'el setup'],
  ['tu viaje', 'tu setup'],
  ['el recorrido', 'el setup'],
  ['tu recorrido', 'tu setup'],
  ['transforma', 'mejora'],
  ['Transforma', 'Mejora'],
  ['transformar', 'mejorar'],
  ['Transformar', 'Mejorar'],
  ['transforma tu sonido', 'mejora tu tono'],
  ['transforma la mezcla', 'mejora la mezcla'],
  ['transformó', 'mejoró'],
  ['transformó la mezcla', 'mejoró la mezcla'],
  ['seamlessly', 'fácilmente'],
  ['Seamlessly', 'Fácilmente'],
  ['seamless', 'suave'],
  ['sin igual', 'muy buena'],
  ['Sin Igual', 'Muy Buena'],
  ['lo último', 'una buena opción'],
  ['lo definitivo', 'una buena opción'],
  ['Lo Último', 'Una buena opción'],
  ['Lo Definitivo', 'Una buena opción'],
  ['el más vendido', 'un popular'],
  ['El más vendido', 'Un popular'],
  ['los más vendidos', 'populares'],
  ['Los más vendidos', 'Populares'],
  ['no puedes equivocarte', 'cualquiera funciona bien'],
  ['No puedes equivocarte', 'Cualquiera funciona bien'],
  ['step up', 'mejora'],
  ['Step up', 'Mejora'],
  ['Step Up', 'Mejora'],
  ['mejora tu nivel', 'mejora'],
  ['te da', 'ofrece'],
  ['te ofrece', 'ofrece'],
  ['obtienes', 'tienes'],
  ['el más potente', 'un potente'],
  ['El más potente', 'Un potente'],
  ['el más vendido', 'un popular'],
  ['el más intuitivo', 'un fácil de usar'],
  ['el más versátil', 'un versátil'],
  ['el más potente compacto', 'un compacto potente'],
  ['el más poderoso', 'un potente'],
  ['la más vendida', 'una popular'],
  ['la más confiable', 'una confiable'],
  ['la más popular', 'una popular'],
  ['la más versátil', 'una versátil'],
  ['el estándar de la industria', 'una referencia del sector'],
  ['el rey', 'una buena opción'],
  ['el rey indiscutible', 'una de las mejores'],
  ['los reyes indiscutibles', 'las mejores opciones'],
  ['en la historia', 'jamás'],
  ['en la industria', 'en el sector'],
  ['en el mundo del', 'en'],
  ['en el mundo de', 'en'],
  ['al final del día', 'en general'],
  ['lo que importa es', 'en resumen'],
  ['sin lugar a dudas', 'sin duda'],
  ['te cambiará la vida', 'vale la pena probarlo'],
  ['te cambiará todo', 'es una gran mejora'],
];

guides.forEach(function(g) {
  fixField(g, 'intro', enReplacements);
  fixField(g, 'intro_es', esReplacements);
  fixField(g, 'conclusion', enReplacements);
  fixField(g, 'conclusion_es', esReplacements);
  fixField(g, 'verdict', enReplacements);
  fixField(g, 'verdict_es', esReplacements);
  fixField(g, 'description', enReplacements);

  // Fix section content
  if (g.sections) {
    g.sections.forEach(function(s) {
      fixField(s, 'content', enReplacements);
      fixField(s, 'content_es', esReplacements);
    });
  }

  // Fix FAQ fields
  if (g.featuredSnippet) {
    for (var i = 1; i <= 6; i++) {
      fixField(g.featuredSnippet, 'faq_a' + i + '_en', enReplacements);
      fixField(g.featuredSnippet, 'faq_a' + i + '_es', esReplacements);
      fixField(g.featuredSnippet, 'faq_q' + i + '_en', enReplacements);
      fixField(g.featuredSnippet, 'faq_q' + i + '_es', esReplacements);
    }
    fixField(g.featuredSnippet, 'text_en', enReplacements);
    fixField(g.featuredSnippet, 'text_es', esReplacements);
  }
});

fs.writeFileSync('data/guides.json', JSON.stringify(guides, null, 2) + '\n');
console.log('AI text fixes applied to ' + fixCount + ' fields');
