var fs = require('fs');
var path = require('path');

var filePath = path.join(__dirname, 'data', 'guides.json');
var guides = JSON.parse(fs.readFileSync(filePath, 'utf8'));

var idx = {};
guides.forEach(function(g, i) { idx[g.id] = i; });

// ---------- fix-clipping-scarlett ----------
g = guides[idx['fix-clipping-scarlett']];
g.intro = 'Clipping on a Focusrite Scarlett 2i2 is almost always a gain staging issue, not a hardware defect. The interface has clean preamps for its price range, but every preamp has a ceiling. The solution is understanding where that ceiling is and working within it.';
g.intro_es = 'El clipping en una Focusrite Scarlett 2i2 casi siempre se debe a cómo se ajusta la ganancia, no a un defecto del equipo. La interfaz tiene preamplificadores limpios para su rango de precio, pero todo previo tiene un límite. La solución es entender dónde está ese límite y trabajar dentro de él.';
g.sections = [
  {
    heading: 'What Clipping Is and Why It Happens on the Scarlett 2i2',
    heading_es: 'Qué es el clipping y por qué ocurre en la Scarlett 2i2',
    content: '<p>Digital clipping occurs when the audio signal exceeds the maximum level the converter can handle. The waveform flattens at the peaks and information is lost. That harsh sound cannot be removed later — no plugin can reconstruct the lost transients.</p><p>The Scarlett 2i2 uses a halo ring as its indicator: green means a clean signal, yellow means you\'re approaching the limit, red means clipping is happening. The most common mistake is thinking the meter needs to hit the top to get a good signal. At 24-bit recording, you have roughly 144 dB of dynamic range. You don\'t need to get anywhere near 0 dB for good quality.</p><p>The goal is to keep peaks between -6 dB and -3 dB. That leaves enough headroom to avoid clipping while preserving full format resolution. If the ring turns red on the loudest moments, the gain is too high.</p>',
    content_es: '<p>El clipping digital ocurre cuando la señal de audio supera el nivel máximo que el convertidor puede manejar. La forma de onda se aplana en los picos y se pierde información. Ese sonido áspero no se puede eliminar después: ningún plugin reconstruye los transitorios perdidos.</p><p>La Scarlett 2i2 usa un anillo halo como indicador: verde es señal limpia, amarillo indica que te estás acercando al límite, rojo significa que ya hay clipping. El error más común es pensar que el medidor debe llegar al tope para tener buena señal. En grabación digital a 24 bits, tienes aproximadamente 144 dB de rango dinámico. No necesitas acercarte a 0 dB para tener calidad.</p><p>El objetivo es mantener los picos entre -6 dB y -3 dB. Eso deja margen suficiente para evitar clipping y conserva toda la resolución del formato. Si el anillo se pone rojo en los momentos más fuertes, la ganancia está demasiado alta.</p>',
    products: [15]
  },
  {
    heading: 'How to Adjust Gain on the Scarlett 2i2 Step by Step',
    heading_es: 'Cómo ajustar la ganancia en la Scarlett 2i2 paso a paso',
    content: '<p>Setting gain correctly on the Scarlett 2i2 is a straightforward process that removes the guesswork:</p><p><strong>1.</strong> Turn the gain knob to zero. Rotate it all the way to the left.</p><p><strong>2.</strong> Ask the musician to play or sing at the loudest volume in the piece. Not the average level — the absolute peak: the hardest drum hit, the most intense guitar chord, the highest vocal note.</p><p><strong>3.</strong> Slowly raise the gain while watching the halo ring. Stop the moment the ring starts showing yellow on the peaks. That means you\'re around -6 dB to -3 dB, which is the optimal range.</p><p><strong>4.</strong> Leave a safety margin of roughly 2 dB. If you see the ring touch red at any point, reduce the gain a bit more until the peaks only reach yellow.</p><p>This method works for any source: vocals, guitar, drums, synth. The principle is always the same: aim for yellow on the peaks, never red.</p><p>One important consideration: if you\'re using a low-output dynamic mic like the Shure SM7B, you\'ll need more gain than with a condenser. The Scarlett 2i2 offers 56 dB of gain, which can fall short for the SM7B without adding preamp noise. In that case, a Cloudlifter CL-1 or FetHead adds 20-25 dB of clean gain before the signal reaches the interface.</p>',
    content_es: '<p>Ajustar la ganancia correctamente en la Scarlett 2i2 sigue un proceso sencillo que elimina las conjeturas:</p><p><strong>1.</strong> Pon la perilla de ganancia en cero. Gírala completamente hacia la izquierda.</p><p><strong>2.</strong> Pide al músico que toque o cante al volumen más fuerte de la pieza. No el nivel promedio, sino el pico absoluto.</p><p><strong>3.</strong> Sube la ganancia lentamente. Detente cuando el anillo halo muestre amarillo en los picos. Eso indica -6 dB a -3 dB, el rango óptimo.</p><p><strong>4.</strong> Deja un margen de 2 dB. Si el anillo toca rojo, reduce la ganancia.</p><p>Para micrófonos de baja salida como el SM7B, la Scarlett puede quedarse corta. Un Cloudlifter CL-1 añade 20-25 dB de ganancia limpia.</p>',
    products: [15,5,1]
  },
  {
    heading: 'Air Mode: How to Use It Without Messing Up Your Levels',
    heading_es: 'El modo Air: cómo usarlo sin que arruine tus niveles',
    content: '<p>The Scarlett 2i2\'s Air mode applies a high-frequency boost (around 4-8 kHz) that can add more presence and brightness to the signal. It\'s useful on vocals and some acoustic instruments. But it has a side effect: it adds roughly 2-3 dB of gain to the signal.</p><p>If you set your gain with Air mode off and then engage it, the level will jump by those 2-3 dB. If you were already close to yellow, you\'ll probably hit red. The solution is simple: set your gain without Air, engage Air mode, then reduce the gain slightly to compensate for the boost.</p><p>Air mode isn\'t always the best choice. For naturally bright voices, acoustic guitars with lots of treble, or tambourines, the boost can sound aggressive. In those cases, it\'s better to leave it off and add presence in the mix if needed. You can\'t undo digital clipping, but you can always add brightness later.</p>',
    content_es: '<p>El modo Air de la Scarlett 2i2 aplica un realce en frecuencias altas (alrededor de 4-8 kHz) que puede dar más presencia y brillo a la señal. Pero tiene un efecto secundario: añade aproximadamente 2-3 dB de ganancia.</p><p>Si ajustas la ganancia con Air apagado y luego lo activas, el nivel subirá. La solución: ajusta la ganancia sin Air, activa el modo, y reduce la ganancia para compensar.</p><p>El modo Air no siempre es la mejor opción. Para voces brillantes o guitarras acústicas con muchos agudos, el realce puede sonar agresivo. En esos casos, es mejor dejarlo apagado.</p>',
    products: [15]
  },
  {
    heading: 'What to Do If You Already Recorded with Clipping',
    heading_es: 'Qué hacer si ya grabaste con clipping',
    content: '<p>If the audio is already clipped, it can\'t be fully recovered. The waveform peaks are gone and no process can recreate them exactly. However, the degree of damage determines whether the take can be saved or not.</p><p><strong>Mild clipping:</strong> the halo ring flashed red occasionally but not sustained. Lower the track\'s clip gain by 3-6 dB in your DAW so the waveform returns to a normal range. Then apply a compressor with a gentle ratio (2:1) to smooth out the dynamics. In many cases, the take is usable.</p><p><strong>Moderate clipping:</strong> the red was sustained but doesn\'t cover entire phrases. A declipper plugin like iZotope RX or Waves Clarity Vx can partially reconstruct the clipped waveforms. Results vary: sibilants and transients are usually the first things to sound artificial after processing.</p><p><strong>Severe clipping:</strong> the waveform looks flat for whole bars at a time. There\'s no fix. The only option is to rerecord. It\'s frustrating, but it\'s better than spending hours trying to fix what can\'t be fixed.</p>',
    content_es: '<p>Si el audio ya tiene clipping, no se puede recuperar por completo. Los picos de la forma de onda se perdieron y ningún proceso puede recrearlos exactamente.</p><p><strong>Clipping leve:</strong> baja el clip gain 3-6 dB en tu DAW. Aplica un compresor con ratio suave (2:1).</p><p><strong>Clipping moderado:</strong> usa un declipper como iZotope RX o Waves Clarity Vx. Los resultados varían.</p><p><strong>Clipping severo:</strong> no hay solución. Regraba.</p>',
    products: [15]
  },
  {
    heading: 'Common Mistakes When Using the Scarlett 2i2',
    heading_es: 'Errores comunes al usar la Scarlett 2i2',
    content: '<p>Several mistakes show up frequently among Scarlett 2i2 users. Here are the most common ones:</p><p><strong>Wrong input mode.</strong> The Scarlett has Inst, Line, and Mic modes. A guitar must be connected in Inst mode, which changes the impedance to match the pickup. If you connect it in Mic mode with high gain, clipping is almost guaranteed. Synthesizers and other line-level gear should go into the rear line inputs.</p><p><strong>Recording too hot on purpose.</strong> With 24-bit resolution, recording with peaks at -6 dB is more than enough. There\'s no benefit to getting close to 0 dB. The extra headroom protects against unexpected peaks and doesn\'t affect quality.</p><p><strong>Not using the pad for hot sources.</strong> For drums, heavily saturated guitar amps, or any high-volume source, hold down the Inst button for two seconds to engage the -10 dB pad. This reduces input sensitivity and prevents clipping before it reaches the preamp.</p><p><strong>Phantom power with ribbon mics.</strong> Engaging +48V with a ribbon microphone can permanently destroy the element. Always verify whether your mic needs phantom power before turning it on.</p><p><strong>Not monitoring levels during recording.</strong> A vocalist who sings softly during sound check may sing twice as loud during the actual take. Keep an eye on the halo ring while recording. If you see red, stop and adjust.</p>',
    content_es: '<p>Errores comunes con la Scarlett 2i2:</p><p><strong>Modo de entrada incorrecto.</strong> Guitarras en modo Inst. Sintetizadores en las entradas de línea traseras.</p><p><strong>Grabar demasiado fuerte.</strong> Con 24 bits, grabar con picos a -6 dB es suficiente. No hay beneficio en acercarse a 0 dB.</p><p><strong>No usar el pad.</strong> Para fuentes fuertes, activa el pad de -10 dB.</p><p><strong>Alimentación fantasma con micrófonos de cinta.</strong> +48V puede destruir el elemento. Verifica siempre.</p><p><strong>No monitorear niveles.</strong> Los niveles cambian durante la grabación. Vigila el anillo halo.</p>',
    products: [15]
  },
  {
    heading: 'When to Consider an Interface with More Headroom',
    heading_es: 'Cuándo considerar una interfaz con más margen',
    content: '<p>The Scarlett 2i2 is a solid interface for most situations, but there are cases where its 56 dB of gain fall short. If you use low-output mics like the SM7B, Electro-Voice RE20, or ribbon microphones, you\'ll likely need a Cloudlifter or a different interface.</p><p>The SSL 2+ MKII offers the 4K Legacy switch, which adds a tonal character that can reduce the need for EQ. The Audient iD14 MkII delivers 58 dB of gain with Class A preamps that offer more clarity at higher settings. The Universal Audio Apollo Twin X is in another category: Unison preamps that emulate vintage hardware and DSP for near-zero-latency monitoring.</p><p>For most home studio users, the Scarlett 2i2 is sufficient. An upgrade is only justified when your microphone needs more gain than the Scarlett can deliver cleanly.</p>',
    content_es: '<p>La Scarlett 2i2 es suficiente para la mayoría de los casos. Si usas SM7B, RE20 o micrófonos de cinta, considera un Cloudlifter o una interfaz con más ganancia.</p><p>SSL 2+ MKII: interruptor 4K Legacy. Audient iD14 MkII: 58 dB, preamplificadores Clase A. Universal Audio Apollo Twin X: preamplificadores Unison, DSP.</p><p>Para la mayoría del home studio, la Scarlett 2i2 es suficiente.</p>',
    products: [15,18,53,16]
  }
];
g.conclusion = 'Clipping on the Scarlett 2i2 is solved by setting gain correctly: aim for yellow on the peaks, never red. Air mode adds 2-3 dB, so compensate after engaging it. For low-output mics, a Cloudlifter solves the problem. The Scarlett 2i2 with proper gain staging delivers professional results in most home studio situations.';
g.conclusion_es = 'El clipping en la Scarlett 2i2 se soluciona ajustando la ganancia correctamente: busca amarillo en los picos, nunca rojo. El modo Air añade 2-3 dB, así que compensa después de activarlo. Para micrófonos de baja salida, un Cloudlifter resuelve el problema.';
g.verdict = 'Adjust gain first. Only upgrade your interface if your mic needs more clean gain than the Scarlett can provide.';
g.verdict_es = 'Ajusta la ganancia primero. Solo actualiza de interfaz si tu micrófono necesita más ganancia limpia.';
faqs = [
  { q_en: 'Does the Scarlett 4th Gen still have clipping problems?', a_en: 'The 4th Gen has improved preamps and a higher maximum input level, but clipping still happens if gain is set too high. The halo ring behavior is the same: green good, yellow approaching limit, red clipping.', q_es: '¿La Scarlett 4ta Gen sigue teniendo problemas de clipping?', a_es: 'La 4ta Gen tiene preamplificadores mejorados, pero el clipping sigue ocurriendo si la ganancia está demasiado alta. El anillo halo funciona igual.' },
  { q_en: 'Will a Cloudlifter fix clipping on my Scarlett?', a_en: 'A Cloudlifter adds clean gain before the preamp, which helps with low-output mics. It does not prevent clipping from hot signals. For loud sources, use the -10 dB pad instead.', q_es: '¿Un Cloudlifter arregla el clipping en mi Scarlett?', a_es: 'Un Cloudlifter añade ganancia limpia para micrófonos de baja salida. No previene clipping de fuentes fuertes. Para eso usa el pad de -10 dB.' },
  { q_en: 'My Scarlett clips only on the left channel. What could cause this?', a_en: 'Check if the left input has the Inst mode engaged while the right is on Line, or vice versa. Also verify the gain knobs are matched. If the problem persists, test with a different cable.', q_es: 'Mi Scarlett recorta solo en el canal izquierdo. ¿Qué puede ser?', a_es: 'Verifica que ambos canales tengan el mismo modo de entrada (Inst/Line) y que las perillas de ganancia estén iguales. Prueba con otro cable.' },
  { q_en: 'Can a bad USB cable cause clipping or distortion?', a_en: 'A faulty USB cable can cause dropouts, crackling, or the interface to disconnect, but not traditional waveform clipping. Try a different cable if you hear digital artifacts.', q_es: '¿Un cable USB malo puede causar clipping o distorsión?', a_es: 'Un cable USB defectuoso puede causar cortes, crujidos o desconexiones, pero no clipping de forma de onda. Prueba otro cable si escuchas artefactos digitales.' },
  { q_en: 'Should I record at 24-bit or 16-bit to avoid clipping?', a_en: 'Always record at 24-bit. It gives you 144 dB of dynamic range versus 96 dB for 16-bit. More headroom means you can safely record at lower levels without losing quality.', q_es: '¿Debería grabar a 24-bit o 16-bit para evitar clipping?', a_es: 'Siempre 24-bit. Te da 144 dB de rango dinámico contra 96 dB de 16-bit. Puedes grabar a niveles más bajos sin perder calidad.' }
];
faqs.forEach(function(f, i) {
  g.featuredSnippet['faq_q' + (i+1) + '_en'] = f.q_en;
  g.featuredSnippet['faq_a' + (i+1) + '_en'] = f.a_en;
  g.featuredSnippet['faq_q' + (i+1) + '_es'] = f.q_es;
  g.featuredSnippet['faq_a' + (i+1) + '_es'] = f.a_es;
});
g.featuredSnippet.text_en = 'Clipping on the Scarlett 2i2 is a gain staging problem. Set gain so the halo flashes yellow on peaks, not red. Air mode adds 2-3 dB — reduce gain after engaging it. For low-output mics like the SM7B, use a Cloudlifter.';
g.featuredSnippet.text_es = 'El clipping en la Scarlett 2i2 es un problema de escalera de ganancia. Ajusta la ganancia para que el halo parpadee amarillo. El modo Air añade 2-3 dB. Para el SM7B, usa un Cloudlifter.';
console.log('Rewrote: fix-clipping-scarlett');

// ---------- best-mic-for-guitar-amps ----------
g = guides[idx['best-mic-for-guitar-amps']];
g.intro = 'Recording a guitar amplifier has its own rules. Sound pressure levels from a cranked amp exceed 120 dB SPL, and not every mic handles that well. Dynamic mics are the most practical choice: they handle high SPL, reject room noise, and deliver a focused sound that sits well in a mix. These are the ones worth considering.';
g.intro_es = 'Grabar un amplificador de guitarra tiene sus propias reglas. Los niveles de presión sonora de un amp cranked superan los 120 dB SPL, y no todos los micrófonos manejan eso bien. Los micrófonos dinámicos son la opción más práctica: soportan alto SPL, rechazan el ruido de sala y entregan un sonido enfocado que se sienta bien en la mezcla. Estos son los que valen la pena considerar.';
g.sections = [
  {
    heading: 'Why Dynamic Mics Work Better on Guitar Cabinets',
    heading_es: 'Por qué los dinámicos funcionan mejor en gabinetes de guitarra',
    content: '<p>Dynamic microphones use a moving coil that converts sound pressure into an electrical signal. Their design makes them naturally resistant to high volume levels. A guitar amp cranked all the way can put out over 120 dB SPL. A condenser mic can distort at those levels. A dynamic mic won\'t.</p><p>Another advantage: dynamics are directional. They primarily capture what\'s in front of them and reject sound coming from the sides and behind. In a room with no acoustic treatment, this makes a huge difference. The mic hears the speaker, not the room reverb.</p><p>The frequency response of most dynamics includes a presence peak between 3 and 6 kHz. That emphasis helps the guitar cut through the mix without aggressive EQ. It\'s one of the reasons the SM57 became the standard for guitar.</p>',
    content_es: '<p>Los micrófonos dinámicos usan una bobina móvil que los hace naturalmente resistentes a altos niveles de volumen. Un amplificador de guitarra al máximo puede emitir más de 120 dB SPL. Un condensador puede distorsionar a esos niveles. Un dinámico, no.</p><p>Otra ventaja: son direccionales. Capturan lo que está frente a ellos y rechazan el sonido de la sala. En una sala sin tratamiento, esto marca una gran diferencia.</p><p>La mayoría de los dinámicos tienen un pico de presencia entre 3 y 6 kHz que ayuda a que la guitarra corte la mezcla.</p>',
    products: [5,1,51]
  },
  {
    heading: 'Shure SM57: The Standard Since the 1970s',
    heading_es: 'Shure SM57: el estándar desde los años 70',
    content: '<p>The Shure SM57 costs around $99 and is the most widely used microphone for recording guitar amps in the history of recorded music. It\'s not the most expensive or the most technically sophisticated, but its frequency response is purpose-built for this job: it tightens the low end, adds a midrange push around 5 kHz, and tames harsh highs. The result is a guitar that sits in the mix without fighting the bass or the vocals.</p><p>Mic placement matters more than the mic itself. The common approach is to place the SM57 right against the grille, aimed at the edge of the cone where it meets the dust cap, at roughly a 30-degree angle. From there, small movements change the tone: toward the center gives more attack and bite; toward the edge gives more body and warmth. It\'s worth spending time moving the mic and listening to how the sound changes.</p><p>The SM57 also handles drums, brass instruments, and many other sources well. If you can only buy one mic for recording amps, the SM57 is the most practical choice.</p>',
    content_es: '<p>El Shure SM57 cuesta alrededor de $99 y es el micrófono más usado para grabar amplificadores de guitarra. Su respuesta en frecuencia está diseñada para este trabajo: aprieta los graves, añade empuje en medios alrededor de 5 kHz y suaviza los agudos excesivos.</p><p>La posición del micrófono importa más que el micrófono mismo. Colócalo sobre la rejilla, apuntando al borde del cono, con un ángulo de unos 30 grados. Hacia el centro da más ataque; hacia el borde da más cuerpo.</p><p>Si solo puedes comprar un micrófono para amplificadores, el SM57 es la opción más práctica.</p>',
    products: [5]
  },
  {
    heading: 'Sennheiser MD 421: When You Need More Body',
    heading_es: 'Sennheiser MD 421: para cuando necesitas más cuerpo',
    content: '<p>The Sennheiser MD 421 has a wider frequency response (30 Hz – 17 kHz) and handles up to 160 dB SPL. Where the SM57 focuses on attack and midrange bite, the MD 421 captures more low end and a fuller picture of the amp. It\'s more of a complementary tool than a replacement.</p><p>Using both mics on the same speaker is a pro recording technique: the SM57 on the grille for attack, the MD 421 next to it for body, then blended to taste. This gives you more flexibility in the mix than a single mic.</p><p>The MD 421 costs around $379, nearly four times the price of the SM57. If you record amps often and want more tonal options, it\'s a worthwhile investment. To start, the SM57 is more than enough.</p>',
    content_es: '<p>El Sennheiser MD 421 tiene respuesta amplia (30 Hz - 17 kHz) y maneja hasta 160 dB SPL. Captura más graves y una imagen más completa del amplificador que el SM57.</p><p>La combinación de ambos en el mismo altavoz es una técnica profesional: SM57 para ataque, MD 421 para cuerpo. Se mezclan al gusto.</p><p>El MD 421 cuesta alrededor de $379. Para uso frecuente, vale la pena. Para empezar, el SM57 es suficiente.</p>',
    products: [51,5]
  },
  {
    heading: 'Shure SM7B on Guitar Amps: It Works But It\'s Not Ideal',
    heading_es: 'Shure SM7B en amplificadores: funciona, pero no es lo ideal',
    content: '<p>The SM7B is known as a vocal mic, but it also gets used on guitar amps. Its frequency response is flatter than the SM57\'s, with less midrange emphasis. For blues, jazz, or classic rock, it can sound more natural and less processed. It also has excellent off-axis rejection, which helps in untreated rooms.</p><p>The main issue is its low output. The SM7B needs a lot of clean gain, and most interfaces can\'t deliver it without adding noise. For amp use, a Cloudlifter CL-1 or equivalent is practically essential. If you already own an SM7B, give it a try. If you\'re buying a mic specifically for guitar amps, the SM57 performs better for less money.</p>',
    content_es: '<p>El SM7B tiene respuesta más plana que el SM57, con menos énfasis en medios. Para blues, jazz o rock clásico, puede sonar más natural. Tiene excelente rechazo fuera del eje.</p><p>El problema es su baja salida. Necesita mucha ganancia limpia. Un Cloudlifter es prácticamente necesario. Si estás comprando un micrófono para amplificadores, el SM57 rinde mejor por menos dinero.</p>',
    products: [1,15]
  },
  {
    heading: 'How to Position the Mic on the Cabinet',
    heading_es: 'Cómo colocar el micrófono en el gabinete',
    content: '<p>The position of the mic on the cabinet affects the tone more than the choice of mic itself. The same SM57 can sound completely different depending on where you place it. Here are the basic parameters:</p><p><strong>Center vs edge:</strong> The center of the cone gives the brightest, most aggressive sound. Maximum attack and presence. This is the position for rock and metal. The edge of the cone (where it meets the rubber surround) gives a darker, rounder sound with less top end. Most classic rock tones fall somewhere between center and edge.</p><p><strong>Angle:</strong> Pointing the mic straight at the speaker (on-axis) gives the most direct sound. Angling it 30-45 degrees (off-axis) tames harsh high frequencies. It\'s a good starting point if the tone sounds too bright.</p><p><strong>Distance:</strong> With the mic touching the grille, you get maximum impact and minimal room sound. Pulling it back 2-6 inches introduces the natural phase cancellation between the speaker and the mic, which can sound good on certain amps. It\'s worth trying different distances.</p><p>The recommended approach: record the same riff in different positions and listen to what works best in the context of the song. Twenty minutes of testing can save hours of EQ later.</p>',
    content_es: '<p>La posición del micrófono afecta el tono más que la elección del micrófono.</p><p><strong>Centro vs borde:</strong> Centro da más ataque. Borde da más cuerpo.</p><p><strong>Ángulo:</strong> On-axis da el sonido más directo. Off-axis (30-45 grados) reduce agudos.</p><p><strong>Distancia:</strong> Tocando la rejilla da máximo impacto. Separado da un sonido más grande.</p><p>Graba el mismo riff en diferentes posiciones y elige la que funcione mejor.</p>',
    products: [5,51,1]
  }
];
g.conclusion = 'The Shure SM57 at $99 is the most practical mic for recording guitar amps. It\'s not the most expensive or the most advanced, but its frequency response and high-SPL handling make it the right choice for most situations. Learning to place it well — how each centimeter of movement affects the tone — is a skill that pays off more than any microphone upgrade. If you need more body, the MD 421 is an excellent complement. If you want a flatter sound for blues or jazz, the SM7B with a Cloudlifter can work, but the SM57 should be your first purchase.';
g.conclusion_es = 'El Shure SM57 a $99 es el micrófono más práctico para grabar amplificadores de guitarra. Aprender a colocarlo bien es más importante que el micrófono mismo. Si necesitas más cuerpo, añade un MD 421. Para blues o jazz, prueba el SM7B con Cloudlifter. Pero el SM57 debería ser la primera compra.';
g.verdict = 'Shure SM57 ($99) is the best choice for most amp recordings. Buy it first.';
g.verdict_es = 'Shure SM57 ($99) es la mejor opción para la mayoría de las grabaciones de amplificadores. Cómpralo primero.';
faqs = [
  { q_en: 'Can I use a ribbon microphone on a guitar amp?', a_en: 'Yes, but with caution. Ribbon mics can be damaged by high SPL and phantom power. Place the mic slightly off-axis to the speaker and keep it at least 6 inches away. Avoid phantom power entirely.', q_es: '¿Puedo usar un micrófono de cinta en un amplificador?', a_es: 'Sí, con cuidado. Las cintas pueden dañarse con alto SPL y alimentación fantasma. Colócalo ligeramente fuera del eje y al menos a 15 cm del altavoz. Nunca actives +48V.' },
  { q_en: 'SM57 vs Sennheiser e609 - which is better for guitar?', a_en: 'The e609 has a slightly darker tone and a supercardioid pattern that rejects more bleed from other instruments. The SM57 has more midrange punch. The e609 can also hang over the amp grille without a stand.', q_es: 'SM57 vs Sennheiser e609 - ¿cuál es mejor para guitarra?', a_es: 'El e609 es un poco más oscuro y tiene patrón supercardioide que rechaza más sangrado. El SM57 tiene más golpe en medios. El e609 se puede colgar de la rejilla sin soporte.' },
  { q_en: 'What mic position gives the heaviest tone for metal?', a_en: 'Point the SM57 directly at the center of the speaker cone, touching the grille, on-axis. This gives maximum attack and high-end bite. For more low-end, add a second mic at the cone edge.', q_es: '¿Qué posición da el tono más pesado para metal?', a_es: 'Apunta el SM57 directamente al centro del cono, tocando la rejilla, on-axis. Da máximo ataque y mordida. Para más graves, añade un segundo micrófono en el borde.' },
  { q_en: 'Should I mic a combo amp or a cabinet differently?', a_en: 'Same technique applies. The speaker in a combo is identical to a cabinet speaker. Position the mic the same way. The main difference is combo amps sit lower, so you may need a shorter stand.', q_es: '¿Debo colocar el micrófono diferente en un combo que en un gabinete?', a_es: 'La misma técnica aplica. El altavoz de un combo es idéntico al de un gabinete. La diferencia es que los combos son más bajos, quizás necesites un soporte más corto.' },
  { q_en: 'What is the best dynamic mic for bass guitar amps?', a_en: 'The Sennheiser MD 421 works well because it captures more low-end. An AKG D112 or Electro-Voice RE20 are also good choices. The SM57 works but lacks low-end extension for bass.', q_es: '¿Cuál es el mejor micrófono dinámico para amplificadores de bajo?', a_es: 'El MD 421 funciona bien porque captura más graves. AKG D112 o EV RE20 también son buenos. El SM57 funciona pero le falta extensión de graves para bajo.' }
];
faqs.forEach(function(f, i) {
  g.featuredSnippet['faq_q' + (i+1) + '_en'] = f.q_en;
  g.featuredSnippet['faq_a' + (i+1) + '_en'] = f.a_en;
  g.featuredSnippet['faq_q' + (i+1) + '_es'] = f.q_es;
  g.featuredSnippet['faq_a' + (i+1) + '_es'] = f.a_es;
});
g.featuredSnippet.text_en = 'The Shure SM57 at $99 is the best dynamic mic for recording guitar amps: focused midrange, handles high SPL, indestructible. Placement matters more than the microphone.';
g.featuredSnippet.text_es = 'El Shure SM57 a $99 es el mejor micrófono dinámico para grabar amplificadores. La colocación importa más que el micrófono.';
console.log('Rewrote: best-mic-for-guitar-amps');

// ---------- best-mic-for-podcasting ----------
g = guides[idx['best-mic-for-podcasting']];
g.intro = 'Choosing a microphone for podcasting depends more on your recording environment than your budget. A dynamic mic in an untreated room sounds better than an expensive condenser in the same space. The priority is getting a clean signal with minimal room noise. These are the mics that deliver best for each situation.';
g.intro_es = 'Elegir un micrófono para podcasting depende más del entorno de grabación que del presupuesto. Un micrófono dinámico en una sala sin tratar suena mejor que un condensador costoso en el mismo espacio. La prioridad es conseguir una señal limpia con el mínimo ruido de ambiente. Estos son los micrófonos que cumplen mejor según cada situación.';
g.sections = [
  {
    heading: 'Dynamic vs Condenser: Pick Based on Your Room',
    heading_es: 'Dinámico vs condensador: la decisión según tu sala',
    content: '<p>The main difference between a dynamic mic and a condenser is sensitivity. Condensers capture more detail: the air around the voice, subtle nuances, full frequency response. They also capture more background noise: the computer fan, street traffic, room reverb.</p><p>Dynamic microphones are less sensitive. Their cardioid pattern focuses on what\'s directly in front of them and rejects ambient sound. In a space without acoustic treatment — most home rooms — a dynamic mic delivers a more usable recording with less editing.</p><p>The practical recommendation: start with a dynamic mic. If your room has acoustic treatment (panels, bass traps, carpets), a condenser can give more detail and a more open sound. If not, the dynamic mic will save you post-production headaches.</p>',
    content_es: '<p>Los condensadores capturan más detalle, pero también más ruido de fondo. Los dinámicos son menos sensibles y rechazan el sonido ambiental.</p><p>En un espacio sin tratamiento, un dinámico da una grabación más usable con menos edición. Si tu sala tiene tratamiento acústico, un condensador puede dar más detalle.</p>',
    products: [1,3,5,50]
  },
  {
    heading: 'Shure SM7B: The Professional Standard',
    heading_es: 'Shure SM7B: el estándar profesional',
    content: '<p>The Shure SM7B is the microphone you see on most professional podcasts. Its frequency response is warm and flat, with a gentle presence boost that makes the voice sound natural without being harsh. It includes a built-in pop filter and shock mount, and its off-axis rejection is excellent.</p><p>The SM7B\'s critical issue is its low output. It needs a lot of gain: around 60-70 dB to reach optimal recording levels. Most interfaces under $500 can\'t deliver that gain without adding noise. The standard fix is a Cloudlifter CL-1 or FetHead, which add 20-25 dB of clean gain before the interface preamp. Without one of these, the SM7B can sound noisy on entry-level interfaces.</p><p>The total cost of an SM7B ($399) plus a Cloudlifter ($149) plus an interface like the Scarlett 2i2 ($199) comes to around $750. It\'s a significant investment, but it\'s a setup that will last for years. If your budget allows, this combination is hard to beat for podcasting.</p>',
    content_es: '<p>El Shure SM7B tiene respuesta cálida y plana, con énfasis suave en presencia. Incluye filtro antipop y suspensión. Su rechazo fuera del eje es excelente.</p><p>Su baja salida requiere mucha ganancia. La mayoría de las interfaces de menos de $500 añaden ruido en ajustes altos. Un Cloudlifter CL-1 o FetHead resuelve el problema.</p><p>El costo total ronda los $750. Es una inversión considerable, pero funciona para años.</p>',
    products: [1,15]
  },
  {
    heading: 'Shure SM58: Professional Quality at $99',
    heading_es: 'Shure SM58: calidad profesional a $99',
    content: '<p>The Shure SM58 costs $99 and is the most used live vocal mic in the world. For podcasting, it delivers perfectly acceptable quality: its frequency response has a slight presence boost that helps the voice come through clearly. In a direct comparison, the difference from an SM7B is subtle, especially after compression and EQ in the mix.</p><p>The SM58 is rugged and needs no extra accessories. It comes with a built-in pop filter and doesn\'t require a special shock mount. For multi-person podcasts, buying several SM58s is far more economical than outfitting everyone with an SM7B.</p><p>The SM58 has one quirk some people mod: the spherical pop filter adds a slight warm coloration. If you prefer a more open sound, you can swap it for the flat grille of an SM57, which lets more highs through.</p>',
    content_es: '<p>El Shure SM58 cuesta $99. Su respuesta tiene un ligero énfasis en presencia. La diferencia con un SM7B es sutil después de procesamiento.</p><p>Es robusto, viene con filtro antipop, y no necesita accesorios adicionales. Para podcasts con múltiples participantes, es mucho más económico.</p><p>El filtro antipop esférico añade coloración cálida. Se puede reemplazar por el filtro de un SM57 para más agudos.</p>',
    products: [50,5]
  },
  {
    heading: 'Rode NT1-A: A Condenser for Treated Rooms',
    heading_es: 'Rode NT1-A: condensador para salas tratadas',
    content: '<p>The Rode NT1-A has a self-noise of only 4.5 dBA, lower than any dynamic microphone. It captures the voice with a level of detail that dynamics can\'t match in its price range. It includes a shock mount and pop filter — accessories that cost extra with other mics.</p><p>The catch is that your room must be acoustically treated. The NT1-A captures everything: the voice, but also the reverb off the walls, traffic noise, the refrigerator hum. In a room with acoustic panels, carpets, and bass treatment, the result is a clarity that no dynamic can deliver. In an untreated room, the result is hollow and amateurish.</p><p>The price is around $159, often on sale for $129. It\'s an excellent value for anyone with the right space. For those who don\'t have it, the SM58 will give a better immediate result.</p>',
    content_es: '<p>El Rode NT1-A tiene ruido propio de 4.5 dBA. Captura la voz con un detalle que los dinámicos no pueden igualar. Incluye soporte antigolpes y filtro antipop.</p><p>La condición es que la sala debe estar tratada. El NT1-A captura todo, incluida la reverberación y el ruido ambiental. En una sala tratada, el resultado es claridad superior. En una sala sin tratar, suena hueco.</p><p>Precio: ~$159. Excelente relación calidad-precio para quien tiene el espacio adecuado.</p>',
    products: [3,15]
  },
  {
    heading: 'USB vs XLR: Which Makes Sense for Your Long-Term Plan',
    heading_es: 'USB vs XLR: qué conviene según tu plan a largo plazo',
    content: '<p>USB microphones are convenient: they work without an interface, connect directly to your computer, and are more portable. For a solo podcast with no plans to expand, a USB mic like the Audio-Technica ATR2100x-USB does the job well.</p><p>The advantage of an XLR system is modularity. An interface like the Scarlett 2i2 ($199) with an SM58 ($99) costs $298. If you later want to add a co-host, you buy another SM58 and the interface already has two inputs. If you want to upgrade the mic, you buy an SM7B and keep the interface. With USB, any change means replacing everything.</p><p>The upfront cost difference isn\'t huge: a good USB mic runs between $130 and $200. An entry-level XLR setup costs around $300. For the difference, you get better sound quality (dedicated interface preamps sound better than USB mic preamps), room to expand, and higher resale value. For anyone planning to take podcasting seriously, XLR is the better investment.</p>',
    content_es: '<p>Los micrófonos USB son prácticos y portátiles. Para un podcast solitario sin intención de expandirse, cumplen bien.</p><p>La ventaja del XLR es la modularidad. Una interfaz con un SM58 cuesta ~$298. Para añadir un co-presentador, compras otro micrófono. Para mejorar, cambias solo el micrófono.</p><p>La diferencia de costo inicial no es grande. Para quienes planean tomar el podcast en serio, XLR es la mejor inversión.</p>',
    products: [15,50,1,5]
  }
];
g.conclusion = 'To start a podcast, the most practical combination is a Shure SM58 ($99) with a Focusrite Scarlett 2i2 ($199). It costs around $300 and delivers professional sound from episode one. If your budget is bigger and your room has acoustic treatment, the SM7B with Cloudlifter is the industry standard. If the room is treated and you want maximum detail, the Rode NT1-A offers exceptional clarity for $159. The most important decision isn\'t the mic — it\'s your recording environment: a dynamic mic in an untreated room will always sound better than a condenser in the same space.';
g.conclusion_es = 'Para empezar un podcast, la combinación más práctica es Shure SM58 ($99) con Scarlett 2i2 ($199). ~$300 y sonido profesional. Si el presupuesto es mayor y la sala tiene tratamiento, SM7B con Cloudlifter. Si la sala está tratada y buscas detalle, Rode NT1-A a $159. La decisión más importante es el entorno de grabación, no el micrófono.';
g.verdict = 'SM58 + Scarlett 2i2 is the best entry point at ~$300. SM7B + Cloudlifter is the professional standard.';
g.verdict_es = 'SM58 + Scarlett 2i2 es el mejor punto de entrada. SM7B + Cloudlifter es el estándar profesional.';
faqs = [
  { q_en: 'Is the Blue Yeti good enough for a professional podcast?', a_en: 'The Blue Yeti is a condenser USB mic that picks up a lot of room sound. In an untreated room, a dynamic mic like the SM58 will sound more professional. The Yeti works best in treated spaces.', q_es: '¿El Blue Yeti es suficientemente bueno para un podcast profesional?', a_es: 'El Blue Yeti es un condensador USB que captura mucho sonido de sala. En una sala sin tratar, un dinámico como el SM58 sonará más profesional.' },
  { q_en: 'Should I record my podcast in mono or stereo?', a_en: 'Mono for each individual voice track. Stereo is only needed for ambience or music. Recording voice in stereo wastes disk space and complicates editing without any benefit.', q_es: '¿Debería grabar mi podcast en mono o estéreo?', a_es: 'Mono para cada pista de voz. El estéreo solo sirve para ambiente o música. La voz en estéreo desperdicia espacio y complica la edición.' },
  { q_en: 'What sample rate and bit depth should I use for podcasting?', a_en: '44.1 kHz / 16-bit for the final delivery. Record at 48 kHz / 24-bit if you want extra headroom for processing, then export to 44.1/16. Higher rates offer no audible benefit for speech.', q_es: '¿Qué tasa de muestreo y profundidad de bits usar para podcasting?', a_es: '44.1 kHz / 16-bit para entrega final. Graba a 48 kHz / 24-bit si quieres margen para procesar, luego exporta a 44.1/16.' },
  { q_en: 'Do voice actors use different mics than podcasters?', a_en: 'Voice actors often prefer large-diaphragm condensers like the Neumann TLM 103 or AKG C414 for their detail. Podcasters favor dynamics like the SM7B that reject room noise. Room treatment matters more for condensers.', q_es: '¿Los actores de voz usan micrófonos diferentes a los podcasters?', a_es: 'Los actores de voz suelen preferir condensadores de diafragma grande como Neumann TLM 103 por su detalle. Los podcasters prefieren dinámicos como el SM7B que rechazan ruido de sala.' },
  { q_en: 'Can I use a gaming headset mic for a podcast?', a_en: 'You can, but the audio quality will be noticeably worse than a dedicated microphone. Headset mics have limited frequency response and pick up breathing and plosives. A $99 SM58 into any interface is a huge upgrade.', q_es: '¿Puedo usar el micrófono de un headset gamer para un podcast?', a_es: 'Puedes, pero la calidad será notablemente peor. Los headsets tienen respuesta limitada y capturan respiración. Un SM58 de $99 es una mejora enorme.' }
];
faqs.forEach(function(f, i) {
  g.featuredSnippet['faq_q' + (i+1) + '_en'] = f.q_en;
  g.featuredSnippet['faq_a' + (i+1) + '_en'] = f.a_en;
  g.featuredSnippet['faq_q' + (i+1) + '_es'] = f.q_es;
  g.featuredSnippet['faq_a' + (i+1) + '_es'] = f.a_es;
});
g.featuredSnippet.text_en = 'The SM7B is the gold standard for podcasting. The SM58 at $99 is the best value. For treated rooms, the Rode NT1-A offers exceptional detail. XLR setups are recommended over USB for quality and expandability.';
g.featuredSnippet.text_es = 'El SM7B es el estándar de oro para podcasting. El SM58 a $99 es el mejor valor. Las configuraciones XLR son recomendadas sobre USB.';
console.log('Rewrote: best-mic-for-podcasting');

