var fs = require('fs');
var g = require('C:/Users/Daniel/projects/topmusiciangear/data/guides.json');
var FROMS = [
  'ththe', 'thany', 'thalmost', 'cleand', 'cadd', 'cadjust', 'carrange', 'cafford', 'calways', 'cthen',
  'makeshaperBox', 'makescaler', 'breaand', 'PreSonustudioLive', 'Yamahand', 'formuland',
  'Live\'session', 'Itsession', 'itsession', 'WavesSL', 'BossD-1', 'vsSL', 'musici cares', 'makee',
  'this it.', 'This the', 'this the', 'Elgato', 'uSB-c', 'MOTU m2', 'u 87 ai', 'LCT1040', 'lCT1040',
  'instantentente', 'instantente', 'No no es solo', 'tusonidos', 'entrado/salida', 'bD-2', 'xR18', 'cQ-18t', 'tR-8s', 'm32r LIVE', 'x32 compact', 'sQ-5', 'sQ-5',
  'Yamaha mG', 'Behringer xenyx', 'montage m8x', 'stage 4', 'nD86',
  'elgato stream deck + xL', 'elgato stream deck+', 'elgato Wave XLR mK.2', 'bEACN mix create',
  'Squier affinity series precision bass pJ', 'music man stingRay ray4',
  'nails aesthetic', 'one of absolute kings', 'preamp c boost', 'At 599, this an investment', 'that cost.',
  'costs, and it works on both Windows and Mac', 'costs — one-time purchase, and', 'tier system: gets you everything',
  'professional audio a, con', 'Komplete Kontrol de Native Instruments', 'por con AI Session Players',
  'motor warping', 'performance en vivo', 'dAW',
  'At the Q2U is', 'At the PD200X is', 'At the SoloCast 2 is', 'For the AmpliTank K688 gives', 'At the AM8 is',
  'At the Seiren V3 Mini is', 'At the AmpliGame A6V is', 'At the NT-USB Mini is', 'At the Yeti Nano is',
  'At the TC-777 is', 'At the PM461 is', 'At the FIFINE T669 is',
  'For the Samson Q2U is', 'if consider a reliable', 'saves you accessory', 'that stays the NT-USB Mini',
  'budget is and you want', 'unlike the original, the 2 adds', 'buyinging', 'at.', 'at the mark',
  'Each, they\'re excellent for beginners and small rooms', "Each, these are the monitors that made me rethink",
  "Each, it's the most accurate monitor", 'revelan..', 'under--per-pair range',
  'the Scarlett 2i2 is the safest bet for beginners.', 'nothing It is easier', 'the Scarlett less is the smarter buy',
  '( each)', '( per pair)', '( a pair)', ' a pair —', '( cada uno)', '( el par)', '(el par)',
  'Pro Toolstudio', '(/year subscription or perpetual)', 'licensing — /year', 'perpetua — /año', '(perpetual)', '/yr or perpetual',
  'es el el DAW', 'At around $699, it delivers', 'Por alrededor de $699, ofrece',
  'Pro-Q 3', 'Pro-C 2',
  'roughly $140',
  'No built-in pad or ground lift switch',
  '0.72 kg', '0.75 kg',
  'The Shure BLX288/PG58 ()', '(,099–,499)', 'two vocalists on stage for.',
  'at nearly the same price point ().', 'at a lower price ().', 'a un precio más bajo. Sin embargo',
  'each — more than the ZLX-12P-G2', ' cada uno — más que el ZLX-12P-G2',
  'Each, it\'s the best value in powered PA speakers', "Each, it's the professional standard",
  'Each, it\'s the premium choice', 'The best-selling monitor for beginners as a pair',
  'El monitor más vendido para principiantes por par',
  ' for per speaker.', 'per speaker.',
  '( each)', '( around $', 'the sub- monitor',
  ' each ( a pair)', ' cada uno ( el par)', 'a pair — more than the JBL', ' el par — más que el par de JBL',
  ' a pair — exceptional value for bedroom producers', ' el par — valor excepcional para productores de dormitorio',
  ' a pair — more than the Kali LP-6 pair', ' el par — más que el par de Kali LP-6',
  ' a pair — it stretches past the budget', ' el par — supera el presupuesto',
  'more each', 'more a pair', 'por más cada una', 'por más el par',
  'Ningún otro monitor por ofrece', 'en lugar con mandos', 'Los extra compran', 'a A diferencia del KRK Rokit',
  ' adds British console mojo more', 'añade el toque de consola británica por más',
  ' and 13 lb (5.9 kg), making it the cheapest', 'Solo y 5,9 kg, el ampli',
  ' offers much deeper control more', 'ofrece control mucho más profundo por más',
  'options each — a pair costs', 'más económicas a cada uno — un par cuesta',
  'at ~ the pair', 'a ~ el par', 'Premium price: for the pair', 'Precio premium: el par',
  'Each, there\'s no excuse',
  'Aim -.', 'a - bass can sound', 'PJ Bass It is the best starter',
  'need to + to get', 'basses costing +.', 'see on + basses.', 'without +.',
  'interruptor activo de 5 posiciones Performance EQ', 'humbucker de Alnico', 'Thunderbird humbucker con EQ activo',
  'pegan muy por encima de su precio',
  'es el el DAW', 'el ATH R50x', '<strong> the ATH-M50x', '</strong> the MDR-7506',
  ' the M50x or the MDR-7506', 'las M50x o las MDR-7506',
  'most accurate monitor ?', ' for per speaker', 'delivers accurate sound for per speaker',
  'considermay ever buying', 'a innovative', 'nails aesthetic'
];

var corpus = JSON.stringify(g);
var missing = FROMS.filter(function (s) { return corpus.indexOf(s) < 0; });
console.log('FROMS total: ' + FROMS.length + '  missing: ' + missing.length);
missing.forEach(function (s) { console.log('  MISSING: ' + JSON.stringify(s)); });