module.exports = {
  "starter-studio|KRK Rokit 7 G5": ["The bass port is rear-firing, so getting them too close to a wall boosts low end noticeably", "El puerto de graves es trasero — cerca de la pared, refuerzan los graves de forma notable"],
  "starter-studio|SSL 2+ MKII": ["No MIDI I/O, so hardware synths and controllers need a separate adapter", "Sin MIDI I/O, así que sintetizadores y controladores hardware necesitan un adaptador aparte"],
  "starter-studio|Rode NT1 5th Generation": ["32-bit float USB mode takes a learnable workflow — levels look tiny until you normalize later", "El modo USB de 32-bit float exige asimilar su flujo — los niveles se ven bajos hasta que normalizas después"],
  "starter-studio|Sony MDR-7506": ["Donut-style earpads press on the ears over very long sessions", "Las almohadillas tipo donut presionan las orejas en sesiones muy largas"],
  "starter-studio|Yamaha HS8": ["No standby mode — they stay powered and humming whenever the interface is on", "Sin modo de reposo — quedan encendidas y zumbando mientras la interfaz está activa"],
  "best-interface|Focusrite Scarlett 2i2 4th Gen": ["No 32-bit float recording — a clipped take can't be recovered in post", "Sin grabación en 32-bit float — una toma saturada no se puede recuperar en post"],
  "best-interface|SSL 2+ MKII": ["No MIDI I/O on the interface, so MIDI gear needs a separate port", "Sin MIDI I/O en la interfaz, así que el equipo MIDI necesita un puerto aparte"],
  "best-interface|Universal Audio Apollo Twin X Gen 2": ["Two analog inputs cap bigger tracking sessions — you'll add the rack for 16+ channels", "Dos entradas analógicas limitan sesiones más grandes — añadirás el rack para 16+ canales"],
  "best-interface|RME Babyface Pro FS": ["USB bus power runs low for two 48V condensers plus high headphone levels", "La alimentación por USB va justa con dos condensadores de 48V y auriculares a alto nivel"],
  "best-interface|Audient iD14 MkII": ["No built-in DSP effects — processing runs in your DAW", "Sin efectos DSP integrados — el procesamiento corre en tu DAW"],
  "best-interface|MOTU M2": ["No pad or polarity switches on the input channels", "Sin interruptores de pad ni de polaridad en los canales de entrada"],
  "best-interface|Universal Audio Volt 2": ["No UAD DSP — you can't run the classic UAD plugins on it", "Sin DSP UAD — no puedes correr los plugins clásicos de UAD en ella"],
  "best-microphone|Shure SM7B": ["Requires a lot of clean gain — most interfaces need a Cloudlifter or a preamp with high gain to sound its best", "Exige mucha ganancia limpia — la mayoría de interfaces necesitan un Cloudlifter o un previo con alta ganancia para sonar al máximo"],
  "best-microphone|Shure SM58": ["No built-in pop filter — plosive-heavy vocals need a foam windscreen or pop shield", "Sin filtro antipop integrado — las voces con muchas oclusivas necesitan espuma o antipop"],
  "best-microphone|Rode PodMic": ["Heavier than USB desk mics of the same size, so it needs a sturdy boom or stand", "Más pesado que los micros USB de escritorio de su tamaño, así que necesita un brazo o soporte robusto"],
  "best-microphone|Rode Procaster": ["No onboard mute or gain control — mixing happens at the interface", "Sin mute ni control de ganancia en el cuerpo — la mezcla ocurre en la interfaz"],
  "best-microphone|Rode NT1 5th Generation": ["32-bit float USB mode takes a learnable workflow — levels look tiny until you normalize later", "El modo USB de 32-bit float exige asimilar su flujo — los niveles se ven bajos hasta que normalizas después"],
  "best-microphone|Shure MV7+": ["Touch-panel mute is easy to hit accidentally when you grab the mic body", "El mute táctil se toca por accidente al agarrar el cuerpo del micro"],
  "best-microphone|Audio-Technica AT2020": ["Cardioid only — no pattern switch for rooms or multi-mic scenes", "Solo cardioide — sin conmutador de patrón para salas o escenas multi-micro"],
  "best-microphone|Elgato Wave:3": ["No XLR output — the capsule is USB-only with no analog path", "Sin salida XLR — la cápsula es solo USB, sin ruta analógica"],
  "best-microphone|Shure SM7dB": ["The built-in preamp adds a touch of hiss at the highest gain settings", "El previo integrado añade un poco de siseo en los ajustes de ganancia más altos"]
};
