module.exports = {
  "starter-monitors|KRK Rokit 7 G5": ["Rear-firing bass port — too close to a wall and the low end swells noticeably", "El puerto de graves es trasero — demasiado cerca de la pared y el extremo grave se engorda de forma notable"],
  "starter-monitors|JBL 305P MkII": ["No Bluetooth — the LSR pair is wired-only", "Sin Bluetooth — el par LSR es solo por cable"],
  "starter-monitors|Kali Audio LP-6 V2": ["Rear-mounted ports need a few inches of back clearance for honest bass", "Los puertos traseros necesitan unos centímetros de holgura posterior para graves honestos"],
  "starter-monitors|Adam Audio D3V": ["No XLR or TRS analog input — USB-C and Bluetooth are the only connections", "Sin entrada analógica XLR ni TRS — solo USB-C y Bluetooth"],
  "starter-monitors|Kali Audio LP-UNF": ["No analog inputs — USB-C and a 3.5mm aux are the only connections", "Sin entradas analógicas — solo USB-C y aux de 3.5mm"],
  "starter-monitors|iLoud Micro Monitor": ["No DSP room correction — placement and the onboard EQ do the work", "Sin corrección DSP de sala — la colocación y el EQ integrado hacen el trabajo"],
  "starter-monitors|Genelec 8010A": ["No room calibration DSP — placement and room acoustics do the work", "Sin DSP de calibración de sala — la colocación y la acústica hacen el trabajo"],
  "starter-monitors|ADAM Audio A3X": ["No built-in DSP — only fixed analog tuning", "Sin DSP integrado — solo ajuste analógico fijo"],
  "best-monitors-for-living-rooms|Kali Audio IN-8 V2": ["Coaxial 8-inch design is big — needs desk space and careful placement", "El diseño coaxial de 8 pulgadas es grande — necesita espacio y colocación cuidadosa"],
  "best-monitors-for-living-rooms|Genelec 8351B SAM": ["Flagship price and full SAM calibration require the separate GLM kit", "Precio insignia y la calibración SAM completa exigen el kit GLM aparte"],
  "best-monitors-for-living-rooms|Neumann KH 150 DSP": ["DSP tuning depth only unlocks via the separate MA 1 measurement kit", "La profundidad de ajuste DSP solo se desbloquea con el kit de medición MA 1 aparte"],
  "best-monitors-for-living-rooms|KEF LS50 Wireless II": ["Sub-bass needs a sub — the 5-inch drivers don't reach deep low end alone", "El sub-bass necesita un sub — los drivers de 5 pulgadas no llegan solos a los graves profundos"],
  "best-monitors-for-living-rooms|B&W 705 S3": ["No built-in room correction — placement and acoustics do the work", "Sin corrección de sala integrada — la colocación y la acústica hacen el trabajo"],
  "best-monitors-for-living-rooms|Focal Aria 926": ["No DSP room correction — placement and room acoustics do the work", "Sin corrección DSP de sala — la colocación y la acústica de la sala hacen el trabajo"],
  "best-monitors-for-living-rooms|Kali Audio LP-UNF": ["No WLAN or network streaming — USB-C, aux and Bluetooth are it", "Sin streaming por red o Wi-Fi — USB-C, aux y Bluetooth son todo"],
  "best-studio-subwoofers|KRK 10s G2": ["No separate volume knob for the crossover's low-pass output", "Sin perilla de volumen independiente para la salida low-pass del crossover"],
  "best-studio-subwoofers|Yamaha HS8S": ["No stereo line-through to a second sub without a splitter", "Sin paso lineal estéreo a un segundo sub sin un splitter"],
  "best-studio-subwoofers|Genelec 7350A SAM": ["Full GLM room calibration needs the separate GLM adapter kit", "La calibración completa GLM de sala exige el kit adaptador GLM aparte"],
  "best-studio-subwoofers|Kali Audio WS-6.2": ["60 Hz top end needs a tight crossover — the LP-6 V2's 47 Hz low end helps slot it in", "Su techo de 60 Hz exige un crossover ajustado — el LP-6 V2 con 47 Hz ayuda a insertarlo"],
  "best-studio-subwoofers|SVS SB-1000 Pro": ["No speakON output for chaining to other subs", "Sin salida speakON para encadenar a otros subs"],
  "best-studio-subwoofers|Adam Audio Sub8": ["No wireless control or app — adjustments are made on the rear panel", "Sin control inalámbrico ni app — los ajustes se hacen en el panel trasero"],
  "best-studio-subwoofers|Mackie CR8S-XBT": ["Bluetooth adds latency, so stay wired for studio work", "El Bluetooth añade latencia, así que quédate con cable en el estudio"]
};
