module.exports = {
  "best-microphone|Shure SM7B": ["Cardioid only — no polar switch for rooms or multi-mic scenes", "Solo cardioide — sin conmutador de patrón para salas o escenas multi-mic"],
  "best-microphone|Shure SM58": ["No windscreen foam included — plosive-heavy vocals need a pop filter or foam add-on", "Sin espuma windscreen incluida — las voces con muchas oclusivas necesitan antipop o espuma extra"],
  "best-microphone|Rode PodMic": ["No internal shock mount — desk or boom vibration reaches the capsule", "Sin montaje antichoque interno — la vibración de escritorio o brazo llega a la cápsula"],
  "best-microphone|Rode Procaster": ["No mute button or built-in pop filter on the body", "Sin botón de mute ni filtro antipop integrado en el cuerpo"],
  "best-microphone|Rode NT1 5th Generation": ["USB mode bypasses the XLR chain but adds a learnable 32-bit float workflow", "El modo USB prescinde de la cadena XLR pero añade un flujo 32-bit float que lleva tiempo asimilar"],
  "best-microphone|Shure MV7+": ["No onboard hard limiter for USB mode — a loud shout can clip the take", "Sin limitador duro integrado en modo USB — un grito fuerte puede saturar la toma"],
  "best-microphone|Audio-Technica AT2020": ["Fixed cardioid — no pattern switch for different recording situations", "Cardioide fijo — sin conmutador de patrón para distintas situaciones de grabación"],
  "best-microphone|Elgato Wave:3": ["The touch-mute panel sits where your thumb lands when grabbing the body", "El panel táctil de mute queda justo donde cae el pulgar al agarrar el cuerpo"],
  "best-microphone|Shure SM7dB": ["No light ring or LCD — status and levels live on the desk or interface", "Sin anillo de luz ni pantalla — el estado y los niveles viven en el escritorio o la interfaz"],
  "best-monitors|KRK Rokit 7 G5": ["The bass port is rear-firing, so wall distance changes the low end a lot", "El puerto de graves es trasero — la distancia a la pared cambia mucho el extremo grave"],
  "best-monitors|Kali Audio LP-6 V2": ["Rear-mounted ports need a few inches of clearance for honest bass", "Los puertos traseros necesitan unos centímetros de holgura para graves honestos"],
  "best-monitors|ADAM Audio D3V": ["No XLR or TRS analog input — USB-C and Bluetooth are the only connections", "Sin entrada analógica XLR ni TRS — solo USB-C y Bluetooth"],
  "best-monitors|Adam T5V": ["The rear EQ switch is coarse — two fixed shelves instead of fine tuning", "El interruptor trasero es tosco — dos shelves fijos en lugar de ajuste fino"],
  "best-monitors|Neumann KH 80 DSP": ["Full DSP room correction needs the separate MA 1 measurement kit", "El DSP de corrección de sala completo exige el kit de medición MA 1 aparte"],
  "best-monitors|Genelec 8010A": ["No DSP room correction on the 8010A — placement does the work", "Sin corrección DSP de sala en la 8010A — la colocación hace el trabajo"],
  "best-monitors|Genelec 8030C": ["No room calibration — placement and acoustics do the work", "Sin calibración de sala — la colocación y la acústica hacen el trabajo"],
  "best-monitors|Yamaha HS8": ["No standby mode — they stay powered and humming whenever the feed is live", "Sin modo de reposo — quedan encendidas y zumbando mientras la señal está activa"],
  "open-headphones|Sennheiser HD 600": ["The fixed cable means a worn lead forces a repair, not a quick swap", "El cable fijo significa que un cable desgastado obliga a reparar, no a un cambio rápido"],
  "open-headphones|Audio-Technica ATH-R70xa": ["Single-sided cable entry concentrates wear near one connector", "La entrada lateral única del cable concentra el desgaste junto a un conector"],
  "open-headphones|Neumann NDH 30": ["No detachable cable — a damaged lead needs service, not a quick swap", "Sin cable desmontable — un cable dañado exige servicio técnico, no un cambio rápido"],
  "open-headphones|Hifiman Sundara": ["The planar drivers need real amplification — weak headphone outs sound thin", "Los drivers planares exigen amplificación real — las salidas débiles suenan pobres"],
  "open-headphones|Sennheiser HD 560S": ["No detachable cable — replacements mean a repair, not a quick swap", "Sin cable desmontable — un repuesto significa reparación, no un cambio rápido"],
  "tracking-headphones|beyerdynamic DT 770 Pro": ["Non-detachable cable — a damaged lead means a repair, not a quick swap", "Cable no desmontable — un cable dañado significa reparación, no un cambio rápido"],
  "tracking-headphones|Shure SRH440A": ["Non-detachable cable — a worn lead means a repair, not a quick swap", "Cable no desmontable — un cable desgastado significa reparación, no un cambio rápido"],
  "tracking-headphones|Sennheiser HD 280 Pro": ["Single-sided cable entry concentrates wear near the connector", "La entrada lateral única del cable concentra el desgaste junto al conector"],
  "tracking-headphones|Audio-Technica ATH-M50x": ["The swivel joints add bulk and the earcups still heat up in long takes", "Las rótulas añaden volumen y las almohadillas calientan en tomas largas"]
};
