module.exports=[
{name:"Universal Audio Volt 2",name_es:"Universal Audio Volt 2",
pros:["Vintage 610 tube-emulation preamp on channel 1 delivers instant classic tone","192kHz/24-bit class-leading for the price","USB-C, bus-powered, portable","Generous bundle (Ableton Live Lite, plugins) and low-latency monitoring"],
pros_es:["El previo con emulación de válvula Vintage 610 en el canal 1 entrega un tono clásico al instante","192kHz/24 bits de primera clase por el precio","USB-C, alimentado por bus, portátil","Paquete generoso (Ableton Live Lite, plugins) y monitoreo de baja latencia"],
cons:["Only channel 1 gets the 610 circuit — channel 2 is a plain solid-state preamp","No MIDI I/O","Fewer routing options than the EVO 4's loopback","Plastic build vs metal rivals"],
cons_es:["Solo el canal 1 recibe el circuito 610 — el canal 2 es un previo de estado sólido normal","Sin MIDI I/O","Menos opciones de ruteo que el loopback del EVO 4","Construcción de plástico frente a rivales de metal"]},
{name:"Audient EVO 4",name_es:"Audient EVO 4",
pros:["Smartgain auto-sets levels in seconds — ideal for podcasters","Built-in loopback makes streaming setup painless","+58dB JFET preamps with plenty of gain for dynamic mics","Compact, bus-powered and sturdy metal shell"],
pros_es:["Smartgain ajusta los niveles automáticamente en segundos — ideal para podcasters","Loopback integrado que simplifica la configuración de streaming","Previos JFET de +58dB con ganancia de sobra para micrófonos dinámicos","Compacto, alimentado por bus y con carcasa de metal resistente"],
cons:["Caps at 96kHz","Less gain than the RME Babyface","Scroll knob has no numeric display","No MIDI I/O"],
cons_es:["Se limita a 96kHz","Menos ganancia que la RME Babyface","El mando giratorio no tiene pantalla numérica","Sin MIDI I/O"]},
{name:"Universal Audio Volt 276",name_es:"Universal Audio Volt 276",
pros:["Built-in 1176-style compressor rides hot vocals on the way in","Vintage 610 tube preamp on both channels","MIDI I/O and 192kHz/24-bit","Compressor and tube tone you don't get elsewhere at this price"],
pros_es:["Compresor integrado estilo 1176 que doma voces calientes a la entrada","Previos de válvula Vintage 610 en ambos canales","MIDI I/O y 192kHz/24 bits","Compresor y tono de válvula que no encuentras en otros a este precio"],
cons:["Costs significantly more than the Volt 2","Compressor adds just one fixed flavor, not full control","No loopback for streaming","No TotalMix-style routing software"],
cons_es:["Cuesta bastante más que la Volt 2","El compresor añade solo un sabor fijo, sin control completo","Sin loopback para streaming","Sin software de ruteo tipo TotalMix"]},
{name:"MOTU M2",name_es:"MOTU M2",
pros:["ESS Sabre32 converters deliver 120dB dynamic range","+60dB preamps with independent 48V and plenty of headroom","Large screen meters both channels clearly","USB-C with MIDI I/O and 192kHz/24-bit"],
pros_es:["Los convertidores ESS Sabre32 entregan 120dB de rango dinámico","Previos de +60dB con 48V independiente y mucho margen","Gran pantalla que mide ambos canales con claridad","USB-C con MIDI I/O y 192kHz/24 bits"],
cons:["No loopback (the M4 adds it)","No built-in compression for hot sources","Bus-powered only via USB-C (no extra power option)","2-in limit pushes you to the M4 for more inputs"],
cons_es:["Sin loopback (el M4 lo añade)","Sin compresión integrada para fuentes calientes","Solo alimentación por bus vía USB-C (sin opción de fuente extra)","El límite de 2 entradas te empuja al M4 si necesitas más"]},
{name:"Audient iD14 MKII",name_es:"Audient iD14 MKII",
pros:["Two independent headphone amps with class-leading clarity","ADAT input expands to 10-in capability","iD scroll control doubles as volume and scroll wheel","Class-A preamps at 96kHz/24-bit"],
pros_es:["Dos amplificadores de auriculares independientes con claridad de primer nivel","La entrada ADAT amplía la capacidad a 10 entradas","El mando iD scroll funciona como volumen y rueda de scroll","Previos Clase A a 96kHz/24 bits"],
cons:["2-in only — you need the iD44 for more line inputs","No MIDI I/O","ADAT expansion requires external gear","Lacks the Volt 276's built-in compression"],
cons_es:["Solo 2 entradas — necesitas la iD44 para más entradas de línea","Sin MIDI I/O","La expansión ADAT requiere equipo externo","Sin la compresión integrada de la Volt 276"]}
];
