var S = JSON.parse(require('fs').readFileSync('temp/_bassamps.json', 'utf8'));
console.log('### title: ' + S.title);
console.log('### title_es: ' + S.title_es);
console.log('### description: ' + S.description.slice(0, 300));
console.log('### description_es: ' + S.description_es.slice(0, 300));
console.log('### relatedGuides: ' + JSON.stringify(S.relatedGuides));
console.log('### featuredProducts: ' + JSON.stringify(S.featuredProducts));
console.log('## productTable.columns: ' + JSON.stringify(S.productTable.columns));
console.log('## productTable.title: ' + JSON.stringify(S.productTable.title));
console.log('## productTable.title_es: ' + JSON.stringify(S.productTable.title_es));
console.log('## productTable.rows sample:');
S.productTable.rows.forEach(function (r, i) { console.log('  row' + i + ': ' + JSON.stringify(r)); });
console.log('## verdictProsCons:');
S.verdictProsCons.forEach(function (p) { console.log('  name: ' + p.name + ' | name_es: ' + p.name_es); console.log('    pros: ' + JSON.stringify(p.pros)); console.log('    pros_es: ' + JSON.stringify(p.pros_es)); console.log('    cons: ' + JSON.stringify(p.cons)); console.log('    cons_es: ' + JSON.stringify(p.cons_es)); });
console.log('## section0 keys/products/conent head:');
var s0 = S.sections[0];
console.log('  heading: ' + s0.heading);
console.log('  heading_es: ' + s0.heading_es);
console.log('  products: ' + JSON.stringify(s0.products));
console.log('  content head: ' + String(s0.content).slice(0, 220));
console.log('  content_es head: ' + String(s0.content_es).slice(0, 220));
console.log('## featuredSnippet price/name values:');
var f = S.featuredSnippet;
console.log('  name1_en=' + f.name1_en + ' name2_en=' + f.name2_en + ' price1=' + f.price1 + ' price2=' + f.price2);
console.log('  brand1=' + f.brand1 + ' brand2=' + f.brand2 + ' rating1=' + f.rating1 + ' rating2=' + f.rating2);
console.log('  type1=' + f.type1 + ' type2=' + f.type2);
console.log('  specs: ' + String(f.specs).slice(0, 300));