var fs = require('fs');
var h = fs.readFileSync('guides/best-bass-practice-amps.html', 'utf8');
function chk(label, needle) { console.log((h.indexOf(needle) >= 0 ? 'OK  ' : 'MISS') + ' ' + label + ' :: ' + needle.slice(0, 60)); }
chk('intro', 'Practicing bass quietly used to mean fighting your amp');
chk('sec1 heading', 'How to Choose the Best Bass Practice Amp');
chk('sec2 heading', 'Rumble 40 V3 the Best All-Round');
chk('table title', 'Best Bass Practice Amps Compared');
chk('table col THR10II', 'Positive Grid Spark MINI');
chk('table row watt', '1 x 10"');
chk('vpc Rumble', 'Real 40W bass tone that covers');
chk('vpc Spark', 'Battery powered, so it works anywhere');
chk('vpc Waza', 'Five IR modes recreate');
chk('faq q1', 'How many watts do I need for a bass practice amp');
chk('faq q6', 'What is the best bass amp for a beginner');
chk('conclusion', 'The Fender Rumble 40 V3 is the best all-round bass practice combo');
chk('related links', 'best-bass-amps');
chk('verdict', 'best all-round pick');
var m = h.match(/data-store="(zzounds|gear4music|andertons|musicstore|reverb|amazon)"/g);
var set = {}; (m || []).forEach(function (s) { set[s.replace('data-store="', '').replace('"', '')] = 1; });
console.log('stores rendered: ' + Object.keys(set).join(', '));
var m2 = h.match(/\$270|\$199|\$299|\$249|\$450/g);
console.log('price strings found: ' + (m2 || []).join(', '));
var m3 = h.match(/Not Available|No disponible|Out of stock|Agotado|oos/g);
console.log('oos/na rows: ' + ((m3 || []).length) + (m3 ? ' :: ' + m3.slice(0, 3).join(' | ') : ''));
var m4 = h.match(/featuredProducts|"id":490|"id":489|"id":293|"id":491|"id":492|"id":485/g);
console.log('jsonld ids: ' + (m4 || []).join(', '));
console.log('jsonld bestRating: ' + (h.match(/bestRating[^,}]*/g) || []).slice(0, 2).join(' | '));
console.log('image cdn: ' + (h.indexOf('2370300000v1_hi') >= 0));
console.log('og:image: ' + ((h.match(/og:image" content="([^"]*)"/) || [])[1] || 'none'));