const fs=require('fs');
const path='C:\\Users\\Daniel\\projects\\topmusiciangear\\index.html';
const buf=fs.readFileSync(path);
let txt=buf.toString('utf8');
const t=Math.random().toString(36).slice(2,10);
const m=txt.match(/shop-buttons\.js\?v=([a-z0-9]+)/);
console.log('old version:', m?m[1]:'none');
txt=txt.replace(/shop-buttons\.js\?v=[a-z0-9]+/g,'shop-buttons.js?v='+t);
fs.writeFileSync(path, txt, 'utf8');
console.log('new version:', t);
