const P = require('C:/Users/Daniel/projects/topmusiciangear/data/products.json');
const names = ["Genelec 8351B","Elgato Wave DX","Samson Q9U XLR/USB","AKG P120 Large-Diaphragm","Behringer B 906","Behringer XM8500 Ultravoice","FIFINE K669D XLR","Samson Q2U USB/XLR","FIFINE AmpliTank K688","Maono PD200X Dynamic","Rode NT1 Signature","Samson C01 Studio","Blue Yeti X","HyperX QuadCast S","Razer Seiren V3 Pro","Samson G-Track Pro","ISO Acoustics ISO-200 (Pair)","Sonarworks SoundID Reference","MiniDSP UMIK-1","Genelec GLM Kit","Auralex MoPADs (4-pack)","Ultimate Support MS-100 (Pair)","Lewitt LCT 440 PURE","Neumann TLM 102","Neumann TLM 103","Warm Audio WA-8000","Sennheiser EW-D Dual","Taylor PS14ce","Arturia DrumBrute Impact","Korg Volca Beats","Behringer RD-8","Elektron Analog Rytm MKII","Polyend Tracker","Fender Player Stratocaster","FL Studio All Plugins Edition","iLoud Micro Monitor Pro","iLoud MTM MKII","Enya Nova Go Sonic","Native Instruments Maschine+","Elektron Model:Samples","Novation Circuit Rhythm","Polyend Play","Teenage Engineering OP-Z","Yamaha THR10II","Orange Crush Bass 50","Darkglass DG210A Microtubes 500","Yamaha THR30II","Darkglass DG210A","Fulltone OCD v2","Wampler Tumnus Deluxe","JHS Morning Glory V4","MXR Distortion+","Boss BD-2W Blues Driver Waza Craft","Strymon TimeLine","Meris LVX","Chase Bliss Habit","Eventide TimeFactor","Source Audio Nemesis","Kawai ES120","Roland FP-90X","Kawai MP11SE","Yamaha CP88","Nord Grand 2","Behringer XR18","Fender Precision Bass","Fender Jazz Bass","NI Komplete 26 Ultimate","Boss RC-500 Loop Station","TC Electronic Ditto X4","Electro-Harmonix 720 Stereo Looper","Pigtronix Infinity Looper","Headrush Looperboard","MXR Clone Looper","Zoom G11","Boss GT-1000 Core","Neural DSP Quad Cortex","Moore GE300","Loupeedeck Live S","Tascam Stream Controller","Audio-Technica AT2020USB-X","MKH 416","NTG5","MKE 600","AT875R","S-Mic 3","VideoMic NTG","VideoMic GO II","MKE 400","MKH 50","EW IEM G4","PSM 300","G4-TWIN","Xvive U4","U4R4","PTM-10","XSW IEM","Jim Dandy","CSF1M","SE P20e","L-00 Studio","CP-60S","Rancher Penguin","Xvive U4 Wireless","Sennheiser EW IEM G4","SOLIDCOM C1","SOLIDCOM C1 Pro","SOLIDCOM SE PRO","Neumann MT 48 (U)","Audient ORIA","Lynx Aurora-n 16 TB3","Antelope Audio Galaxy 32 Synergy Core","DJI Mic 3","DJI Mic Mini 2","FIFINE AmpliGame AM8","Rode NT-USB Mini","Blue Yeti Nano","FIFINE AmpliGame A6V","Ibanez AW54 Artwood","QSC KS118","Sire Marcus Miller V5R","Lewitt LCT 1040","Sennheiser XSW IEM","RØDECaster Pro II","Sennheiser EW-D 835-S Vocal Set","Epiphone DR-100 Acoustic","Yamaha FS800 Acoustic","Taylor PS14ce_dup"];
const seen = new Set();
names.forEach(n => {
  if (n.endsWith('_dup') || seen.has(n)) return;
  seen.add(n);
  const key = n.toLowerCase().replace(/[^a-z0-9]/g, '');
  const cands = P.filter(p => {
    const cn = p.title.toLowerCase().replace(/[^a-z0-9]/g, '');
    return cn.includes(key) || key.includes(cn);
  });
  if (cands.length === 1) console.log('ALIAS: "' + n + '" => ' + cands[0].id + ' ' + cands[0].title);
  else if (cands.length === 0) console.log('MISSING: "' + n + '"');
  else console.log('AMBIG(' + cands.length + '): "' + n + '" => ' + cands.map(p => p.id + ':' + p.title).join(' / '));
});