const fs = require('fs');
const DIR = 'C:/Users/Daniel/projects/topmusiciangear/';
function assertEq(a, b, w) { if (a !== b) throw new Error('ASSERT ' + w + '\nGOT: ' + JSON.stringify(a) + '\nEXP: ' + JSON.stringify(b)); }
const G = JSON.parse(fs.readFileSync(DIR + 'data/guides.json', 'utf8'));
const o = G.find(x => x.id === 'best-drum-machine');
assertEq(o.productTable.columns.length, 8, 'cols');
assertEq(o.verdictProsCons.length, 8, 'verdicts');
assertEq(o.sections.length, 3, 'sections');

const S = (heading, heading_es, content, content_es, products) => ({ heading, heading_es, content, content_es, products });
o.sections = [
S('Pocket Acid: Is the Roland T-8 the Best First Beat Machine?',
'Acid de bolsillo: ¿es el Roland T-8 la mejor primera caja de ritmos?',
'<p><strong>An 808, a 909 and a 303 that fit in a jacket pocket — for the price of a plugin bundle.</strong> The T-8 squeezes genuine ACB Roland drums plus a squelchy TB-303 bassline into 310 grams with a 4.5-hour battery. Commutes and sofas become studios; ideas get captured instead of forgotten.</p><p>The price of tiny is tiny controls and no user sampling — what you hear is what Roland gives you. For absolute beginners and travelers who want real hardware rhythm now, nothing starts faster or cheaper.</p>',
'<p><strong>Una 808, una 909 y una 303 que caben en un bolsillo — por el precio de un paquete de plugins.</strong> El T-8 mete baterías Roland ACB genuinas más un bajo TB-303 en 310 gramos con 4,5 h de batería. Los viajes y el sofá se vuelven estudios; las ideas se capturan en vez de olvidarse.</p><p>El precio de lo diminuto son controles diminutos y sin sampling propio — lo que oyes es lo que Roland te da. Para principiantes absolutos y viajeros que quieren ritmo hardware real ya, nada empieza más rápido ni más barato.</p>',
[610]),
S('No Screen, No Distraction: Is Circuit Tracks the Best First Groovebox?',
'Sin pantalla, sin distracción: ¿es Circuit Tracks la mejor primera groovebox?',
'<p><strong>Two synths, four drum tracks, two MIDI tracks — and not a single menu to get lost in.</strong> Circuit Tracks replaces screens with 32 glowing pads, so beginners arrange with ears instead of eyes. Battery power, microSD packs and a 4-hour charge-free window mean tracks start on the train and finish at home.</p><p>Depth has limits: synth editing needs the Components app, and 32 steps per pattern cap long arrangements. For first-time groovebox owners who want songs instead of learning curves, it is the friendliest start in hardware.</p>',
'<p><strong>Dos sintes, cuatro pistas de batería, dos MIDI — y ni un solo menú donde perderse.</strong> Circuit Tracks cambia pantallas por 32 pads luminosos, así los principiantes arreglan con oídos en vez de ojos. Batería, packs microSD y 4 h sin cables significan temas que empiezan en el tren y terminan en casa.</p><p>La profundidad tiene límites: editar sintes pide la app Components, y los 32 pasos por patrón topan arreglos largos. Para dueños primerizos que quieren canciones en vez de curvas de aprendizaje, es el inicio más amable del hardware.</p>',
[129]),
S('Knobs, Not Menus: Is the DrumBrute Impact Pure Analog Attitude?',
'Mandos, no menús: ¿es DrumBrute Impact pura actitud analógica?',
'<p><strong>Ten analog voices, one knob per function, zero screens — and a Color knob that makes each drum snarl.</strong> The DrumBrute Impact is refusal-as-design: no samples, no presets to hide behind, just a chest-pounding kick, slapping snares and a feral FM drum shaped live. The 64-step polyrhythmic sequencer with roller and looper turns patterns into performances.</p><p>Analog honesty cuts both ways: no total recall, no user samples, and tuning drift is part of the charm. For rock, industrial and dark electronics players who twist knobs instead of clicking mice, it is the most fun per euro in rhythm hardware.</p>',
'<p><strong>Diez voces analógicas, un mando por función, cero pantallas — y un mando Color que hace gruñir cada tambor.</strong> DrumBrute Impact es la negación como diseño: sin samples ni presets donde esconderse, solo un bombo que golpea el pecho, cajas que abofetean y un FM salvaje moldeado en directo. El secuenciador polirrítmico de 64 pasos con roller y looper convierte patrones en actuaciones.</p><p>La honestidad analógica corta en dos direcciones: sin memoria total, sin samples propios, y la deriva de afinación es parte del encanto. Para rock, industrial y electrónica oscura que giran mandos en vez de clicar ratones, es la diversión por euro en hardware rítmico.</p>',
[614]),
S('Faders Up: Is the TR-8S Still the Live Techno Standard?',
'Faders arriba: ¿sigue la TR-8S siendo el estándar del techno en directo?',
'<p><strong>Ask any techno booth what is clocking the room and half the time it is this.</strong> The TR-8S remains the live standard because nothing else puts ACB 808/909 drums, user samples and per-channel faders under ten fingers at once. Scenes morph full kits mid-bar; the crowd hears the arrangement change, not a laptop buffer.</p><p>It is a performer, not a studio brain: no song mode depth for full arrangements, and 2.1 kg plus wall power anchor it to the stage. For live electronic sets where hands beat cursors, it is still the default answer.</p>',
'<p><strong>Pregunta en cualquier cabina techno qué marca el tempo y la mitad de las veces es esta.</strong> La TR-8S sigue siendo el estándar en directo porque nada más pone baterías ACB 808/909, samples propios y faders por canal bajo diez dedos a la vez. Las escenas cambian kits enteros a mitad de compás; el público oye cambiar el arreglo, no un buffer de laptop.</p><p>Es una intérprete, no un cerebro de estudio: sin modo canción profundo para arreglos completos, y 2,1 kg más enchufe la anclan al escenario. Para directos electrónicos donde las manos ganan a los cursores, sigue siendo la respuesta por defecto.</p>',
[33]),
S('Chop Everything: Is the MPC One+ the Hip-Hop Brain?',
'Trocea todo: ¿es la MPC One+ el cerebro del hip-hop?',
'<p><strong>Sixteen pads, forty years of lineage, zero computer required.</strong> The MPC One+ runs the workflow that invented hip-hop production standalone: chop samples on the 7-inch touch screen, sequence 128 MIDI plus 8 audio tracks, and finish songs with plugin synths and 100+ AIR effects inside the box. Red paint, same religion.</p><p>Standalone means standalone limits: a small screen next to a DAW, 2 GB of working RAM, and no battery for the park. Note the changing of the guard — the G2 successor is taking over shelves, so buy new while stocks last. For beatmakers who think in pads, nothing else speaks the mother tongue.</p>',
'<p><strong>Dieciséis pads, cuarenta años de linaje, cero ordenador.</strong> La MPC One+ ejecuta autónoma el flujo que inventó producir hip-hop: trocea samples en la táctil de 7 pulgadas, secuencia 128 MIDI más 8 de audio y termina canciones con sintes plugin y más de 100 efectos AIR dentro de la caja. Pintura roja, misma religión.</p><p>Autónomo significa límites autónomos: pantalla pequeña junto a un DAW, 2 GB de RAM de trabajo y sin batería para el parque. Ojo al cambio de guardia — el sucesor G2 toma las estanterías, así compra nueva mientras haya stock. Para beatmakers que piensan en pads, nada más habla la lengua madre.</p>',
[611]),
S('Sixteen Stereo Tracks of Anything: Is Digitakt II the Sampling God?',
'Dieciséis pistas estéreo de lo que sea: ¿es Digitakt II el dios del muestreo?',
'<p><strong>Sample the thunderclap, stretch it, granulize it, sequence it across 128 steps with locks on every parameter.</strong> Digitakt II takes the beloved original and doubles down: 16 stereo-or-MIDI tracks, 400 MB of sample memory plus a 20 GB drive, machines for slicing and warping, and the Euclidean generator for rhythms math cannot predict.</p><p>Godhood has tuition fees: the Elektron workflow rewards the patient and punishes the casual, and 1.48 kg of steel wants desk space. For advanced electronic producers building entire tracks from splinters of sound, it is the deepest instrument here.</p>',
'<p><strong>Samplea el trueno, estíralo, granulízalo, secuéncialo en 128 pasos con locks en cada parámetro.</strong> Digitakt II toma la querida original y dobla la apuesta: 16 pistas estéreo o MIDI, 400 MB de memoria más 20 GB de disco, máquinas para trocear y deformar, y generador euclídeo para ritmos que las mates no predicen.</p><p>La divinidad tiene matrícula: el flujo Elektron premia al paciente y castiga al casual, y 1,48 kg de acero piden escritorio. Para productores electrónicos avanzados que construyen temas enteros con astillas de sonido, es el instrumento más profundo de aquí.</p>',
[127]),
S('Analog Heart, Digital Brain: Is Syntakt Greater Than Its 12 Tracks?',
'Corazón analógico, cerebro digital: ¿es Syntakt más que sus 12 pistas?',
'<p><strong>Four analog voices growling through real circuits, eight digital voices glitching through FM — one sequencer conducting all of it.</strong> Syntakt fuses both Elektron worlds: 37 machines from thunderous analog kicks to glassy digital bells, each track flippable to MIDI, with parameter locks, song mode and Overbridge tying it to the DAW.</p><p>Fusion means compromise: neither the deepest analog mono nor the widest digital poly, and the small OLED keeps menu-diving alive. For producers who want drums, bass and sparks from a single lap-sized box, it is the hybrid sweet spot.</p>',
'<p><strong>Cuatro voces analógicas rugiendo en circuitos reales, ocho digitales glitcheando en FM — un secuenciador dirigiéndolo todo.</strong> Syntakt fusiona ambos mundos Elektron: 37 máquinas de bombos analógicos atronadores a campanas digitales cristalinas, cada pista cambiable a MIDI, con parameter locks, modo canción y Overbridge atándolo al DAW.</p><p>La fusión implica compromiso: ni el mono analógico más profundo ni la poli digital más amplia, y el pequeño OLED mantiene vivo el buceo en menús. Para productores que quieren batería, bajo y chispas en una caja de regazo, es el punto híbrido ideal.</p>',
[612]),
S('A Suitcase of Knobs: Is the Pērkons HD-01 Worth Flagship Money?',
'Una maleta de mandos: ¿vale el Pērkons HD-01 el dinero insignia?',
'<p><strong>Four voices, one knob per function, zero presets to hide behind — and a sound that eats PA systems for breakfast.</strong> The Pērkons HD-01 routes digital engines through per-voice analog filters into a bucket-brigade delay, with a panel the size of a suitcase that begs to be performed. Sixty-four kits of modern techno thunder, saved or blank.</p><p>Flagship money buys flagship demands: 3.7 kg that never leaves the studio, no sampling engine, and a price that funds entire setups elsewhere. For professional techno producers who perform their rig like an instrument, it is the aspirational grail — nothing else looks or hits like it.</p>',
'<p><strong>Cuatro voces, un mando por función, cero presets donde esconderse — y un sonido que desayuna PAs.</strong> El Pērkons HD-01 pasa motores digitales por filtros analógicos por voz hacia un delay de brigada, con un panel tamaño maleta que pide ser tocado. Sesenta y cuatro kits de trueno techno moderno, guardados o en blanco.</p><p>El dinero insignia exige demandas insignia: 3,7 kg que nunca salen del estudio, sin motor de sampling y un precio que financia equipos enteros en otro lado. Para productores profesionales de techno que tocan su equipo como un instrumento, es el grial aspiracional — nada más se ve ni pega como él.</p>',
[613])
];
console.log('sections written:', o.sections.length);
fs.writeFileSync(DIR + 'data/guides.json', JSON.stringify(G, null, 2) + '\n');
console.log('guides.json written (sections only)');
