const fs = require('fs');
const F = 'C:/Users/Daniel/projects/topmusiciangear/data/guides.json';
const G = require(F);
const g = G.find(x => x.id === 'best-mic-for-podcasting');
const byId = id => g.sections.find(s => (s.products || [])[0] === id);
const set = (id, en, es) => { const s = byId(id); s.content = en; s.content_es = es; console.log('OK ' + id); };

set(50,
'<strong>The vocal mic that survives everything the stage throws at it.</strong> A cardioid dynamic with a pneumatic shock mount and a steel-mesh ball grille: plosives and handling thumps die before reaching the capsule, while the tailored presence rise keeps vocals intelligible over loud bands. No power needed, no switches to bump, no fragility — it works in rain, heat and drops that kill condensers.</p><p>The SM58 is also the practical multi-host choice: every unit sounds identical, so four hosts on four SM58s need almost no per-channel EQ to sit together. The clip grips any standard stand, the cartridge unscrews for a quick field swap, and replacement grilles cost little when one finally dents after years of drops.</p><p>The honest trade-off: it is a live vocal mic first, not a detail mic. A condenser like the NT1 resolves far more air and nuance in a treated room — but in untreated bedrooms, loud stages and guest chairs, the SM58 delivers usable broadcast-adjacent tone where condensers deliver room noise.',
'<strong>El micro de voz que sobrevive a todo lo que le echa el escenario.</strong> Dinámico cardioide con suspensión neumática y rejilla esférica de acero: los golpes de voz y el ruido de manejo mueren antes de llegar a la cápsula, mientras el realce de presencia mantiene la voz inteligible sobre bandas ruidosas. Sin alimentación, sin interruptores que mover por error, sin fragilidad — funciona con lluvia, calor y caídas que matan a un condensador.</p><p>El SM58 también es la opción práctica multivoz: cada unidad suena idéntica, así que cuatro presentadores con cuatro SM58 casi no piden ecualización por canal para encajar. La pinza agarra cualquier pie estándar, la cápsula se desenrosca para un cambio rápido y las rejillas de repuesto cuestan poco cuando una por fin se abolla tras años de caídas.</p><p>El matiz honesto: es ante todo un micro de directo, no un micro de detalle. Un condensador como el NT1 resuelve mucho más aire y matiz en sala tratada — pero en dormitorios sin tratar, escenarios ruidosos y sillas de invitado, el SM58 entrega un tonoBroadcast utilizable donde los condensadores entregan ruido de sala.');

set(197,
'<strong>Broadcast tone without the broadcast budget or the gain headache.</strong> A cardioid dynamic tuned for speech, with an internal pop filter and shock mounting plus a swing mount in the box. The tight pickup keeps untreated rooms and co-hosts out of the recording, and the voicing flatters thin or harsh voices with broadcast-style warmth.</p><p>Setup is deliberately frictionless: standard XLR into any interface, yoke mount that angles silently during a show, and a detachable cable for tidy packing. Gain needs stay moderate, so even entry-level interfaces drive it cleanly without inline boosters — a real cost saving over gain-hungry flagships.</p><p>The honest trade-off: it is tuned for one job — spoken voice. A Procaster or SM7B sounds bigger and more authoritative for deep voices and flagship chains, with more low-end weight at the cost of size, weight and preamp demands. For first serious podcast setups on a budget, the PodMic is the default answer.',
'<strong>Tono broadcast sin presupuesto broadcast ni dolores de ganancia.</strong> Dinámico cardioide ajustado para la voz, con filtro antipop y suspensión internos más soporte giratorio en la caja. Su captación cerrada deja fuera la sala sin tratar y a los compañeros de mesa, y su ecualización favorece voces finas o ásperas con calidez radiofónica.</p><p>El montaje es deliberadamente sin fricción: XLR estándar a cualquier interfaz, soporte de horquilla que se orienta en silencio durante el programa y cable desmontable para recoger ordenado. La ganancia necesaria es moderada, así que hasta las interfaces básicas lo mueven limpio sin boosters en línea — un ahorro real frente a insignias hambrientas de ganancia.</p><p>El matiz honesto: está ajustado para un solo trabajo — la voz hablada. Un Procaster o un SM7B suenan más grandes y autoritarios en voces profundas y cadenas insignia, con más peso en graves a cambio de tamaño, peso y exigencias de previo. Para el primer montaje de podcast serio con presupuesto, el PodMic es la respuesta por defecto.');

set(329,
'<strong>When the PodMic is not enough mic.</strong> A full-size broadcast dynamic with a large neodymium capsule, tight cardioid pattern and 10-year warranty. Compared with its smaller sibling it sounds bigger and more authoritative, with deeper low-end weight for deep voices — at the cost of size, weight and gain hunger that demands a strong preamp or inline booster.</p><p>The package is built for installed booths: end-address form that works on any boom arm, internal pop filtering plus shock mounting, and a voicing that needs almost no EQ to sit in a radio-style mix. The tight pattern rejects co-hosts and room reflections better than wider cardioids, which is exactly what multi-mic tables need.</p><p>The honest trade-off: everything about it assumes a treated booth and a proper signal chain. For travel, kitchens and untreated bedrooms, the smaller PodMic or an SM58 gets usable results with less fuss — the Procaster only pays off where the room and the preamp are already right.',
'<strong>Cuando el PodMic se queda corto.</strong> Dinámico broadcast de tamaño completo con cápsula grande de neodimio, cardioide estrecho y 10 años de garantía. Frente a su hermano pequeño suena más grande y autoritario, con más peso en graves para voces profundas — a cambio de tamaño, peso y un apetito de ganancia que pide un previo potente o un booster en línea.</p><p>El conjunto está construido para cabinas instaladas: formato de dirección frontal que funciona en cualquier brazo articulado, filtrado antipop y suspensión internos, y una ecualización que casi no pide EQ para sentarse en una mezcla estilo radio. El patrón cerrado rechaza compañeros de mesa y reflexiones mejor que cardioides más anchos, justo lo que piden las mesas con varios micros.</p><p>El matiz honesto: todo en él presupone cabina tratada y cadena de señal seria. Para viajes, cocinas y dormitorios sin tratar, el PodMic pequeño o un SM58 dan resultados utilizables con menos lío — el Procaster solo rinde donde la sala y el previo ya están a la altura.');

set(1,
'<strong>The broadcast standard that forgives bad rooms.</strong> A large-diaphragm dynamic with internal shock mounting, detachable windscreens and bass-rolloff plus presence switches. Rejection and a smooth, sibilance-free top end make untreated bedrooms sound treated — the trade is very low output that demands serious clean gain from the interface or an inline booster.</p><p>The SM7B rewards proper gain staging like nothing else in its class: bass rolloff tames proximity boom for close talkers, the presence lift adds broadcast sheen without harshness, and the yoke mount plus detachable close-talk windscreen adapt from radio booth to streaming desk. It takes EQ gracefully, so voices shape fast in post.</p><p>The honest trade-off: price plus gain cost. Between the mic and the clean gain it demands, a PodMic or MV7+ setup costs less and records sooner — and in a treated studio, an NT1 resolves more detail. The SM7B earns its place where rejection, smoothness and a finished broadcast tone matter more than sensitivity.',
'<strong>El estándar broadcast que perdona salas malas.</strong> Dinámico de diafragma grande con suspensión interna, paravientos desmontables e interruptores de recorte de graves y presencia. Su rechazo y su agudo suave sin sibilancia hacen que un dormitorio sin tratar suene tratado — a cambio de una salida muy baja que exige ganancia limpia seria de la interfaz o un booster en línea.</p><p>El SM7B premia una buena estructura de ganancia como ningún otro de su clase: el recorte de graves doma el boom de proximidad en locutores cercanos, el realce de presencia añade brillo broadcast sin dureza, y la horquilla más el paravientos de cercanía se adaptan de la cabina de radio al escritorio de streaming. Acepta EQ con nobleza, así que las voces se moldean rápido en postproducción.</p><p>El matiz honesto: precio más coste de ganancia. Entre el micro y la ganancia limpia que pide, un montaje PodMic o MV7+ cuesta menos y graba antes — y en estudio tratado, un NT1 resuelve más detalle. El SM7B se gana su sitio donde el rechazo, la suavidad y un tono broadcast terminado importan más que la sensibilidad.');

set(3,
'<strong>Silence you can measure, with a USB cable attached.</strong> A 1-inch condenser at 4 dBA self-noise — quieter than most treated rooms — with Dual Connect offering classic 48V XLR and 32-bit float USB-C from the same body. Detail, air and low-end honesty that dynamics cannot reach, provided the room is treated and background noise is controlled.</p><p>The USB path is the real story for podcasters: 32-bit float recording makes clipped takes recoverable, DSP offers high-pass, compressor, gate and APHEX enhancement, and zero-latency headphone monitoring keeps performances natural. One mic covers the treated studio over XLR today and the laptop-only setup over USB tomorrow.</p><p>The honest trade-off: sensitivity is a double-edged sword. In untreated rooms it captures keyboards, traffic and plumbing alongside the voice — where an SM7B simply rejects them. The NT1 5th Gen is the studio vocal upgrade, full stop, but only once the space is ready for it.',
'<strong>Silencio medible, con cable USB incluido.</strong> Condensador de 1 pulgada con 4 dBA de ruido propio — más silencioso que la mayoría de salas tratadas — con Dual Connect que ofrece XLR clásico de 48V y USB-C en flotante de 32 bits en el mismo cuerpo. Detalle, aire y honestidad en graves que ningún dinámico alcanza, siempre que la sala esté tratada y el ruido de fondo controlado.</p><p>La vía USB es la verdadera historia para podcasters: la grabación en flotante de 32 bits recupera tomas saturadas, el DSP ofrece paso alto, compresor, puerta y realce APHEX, y el monitoreo sin latencia mantiene las interpretaciones naturales. Un solo micro cubre el estudio tratado por XLR hoy y el montaje solo-portátil por USB mañana.</p><p>El matiz honesto: la sensibilidad es un arma de doble filo. En salas sin tratar captura teclados, tráfico y tuberías junto a la voz — donde un SM7B simplemente los rechaza. El NT1 de 5.ª generación es la mejora vocal de estudio, sin más, pero solo cuando el espacio está listo para él.');

set(297,
'<strong>Classic NT1 sound without the bundle price.</strong> The same HF6 1-inch capsule and 4 dBA noise floor in a streamlined package with shock mount, pop filter and XLR cable included. Neutral with a gentle 10 kHz lift that puts vocals and acoustic guitars forward without harshness.</p><p>XLR-only and 48V-powered, it slots into any interface-based chain: pop filter and shock mount in the box mean genuinely nothing else to buy except a stand, and the low self-noise keeps quiet passages and fades clean. A favorite for voice-over booths and acoustic singer-songwriters on a budget.</p><p>The honest trade-off: no USB path and no DSP. Podcasters recording straight to a laptop need an interface, where the NT1 5th Gen or MV7+ record with no extra box — but for XLR studio chains, the Signature delivers the same capsule for less. It is the condenser most home studios graduate to after outgrowing a starter mic.',
'<strong>El sonido NT1 clásico sin precio de bundle.</strong> La misma cápsula HF6 de 1 pulgada y 4 dBA de ruido en un paquete esencial con suspensión, antipop y cable XLR incluidos. Neutro con un leve realce sobre 10 kHz que adelanta voces y acústicas sin dureza.</p><p>Solo XLR con phantom de 48V, encaja en cualquier cadena con interfaz: antipop y suspensión en la caja significan que de verdad no hay nada más que comprar salvo el pie, y el bajo ruido propio mantiene limpios pasajes suaves y fundidos. Favorito para cabinas de locución y cantautores acústicos con presupuesto.</p><p>El matiz honesto: sin vía USB ni DSP. Quien graba directo al portátil necesita una interfaz, donde el NT1 de 5.ª generación o el MV7+ graban sin caja extra — pero para cadenas XLR de estudio, el Signature entrega la misma cápsula por menos. Es el condensador al que llegan la mayoría de home studios tras superar el micro inicial.');

set(194,
'<strong>SM7B character with training wheels.</strong> A hybrid dynamic with USB-C and XLR outputs, built-in headphone monitoring, touch panel metering and auto-level DSP that keeps voice consistent on stream. Less demanding than the SM7B on preamp gain, with the XLR path ready when the setup grows.</p><p>The streamer-proof details matter daily: the touch panel shows levels at a glance without opening software, auto-level rides gain for animated talkers, and the USB path records while the XLR feeds a mixer or interface for a backup. The dark steel finish and compact yoke look deliberate on camera instead of improvised.</p><p>The honest trade-off: convenience over ultimate tone. A well-gained SM7B still sounds richer and more authoritative to trained ears, and the MV7+ costs more than mics that need no DSP to sound right. It is the bridge between USB convenience and pro XLR — ideal while the setup is still evolving.',
'<strong>Carácter SM7B con ruedines.</strong> Dinámico híbrido con salidas USB-C y XLR, monitoreo por auriculares integrado, medidores táctiles y DSP de nivel automático que mantiene la voz consistente en directo. Menos exigente que el SM7B con la ganancia del previo, con la vía XLR lista cuando el montaje crece.</p><p>Los detalles a prueba de streamers importan cada día: el panel táctil muestra niveles de un vistazo sin abrir software, el nivel automático cabalga la ganancia de locutores animados y la vía USB graba mientras el XLR alimenta mesa o interfaz de respaldo. El acabado acero oscuro y la horquilla compacta se ven deliberados en cámara en vez de improvisados.</p><p>El matiz honesto: conveniencia frente a tono definitivo. Un SM7B bien alimentado sigue sonando más rico y autoritario para oídos entrenados, y el MV7+ cuesta más que micros que no necesitan DSP para sonar bien. Es el puente entre la comodidad USB y el XLR profesional — ideal mientras el montaje aún evoluciona.');

set(252,
'<strong>The PodMic that plugs straight into the laptop.</strong> The classic broadcast dynamic voice plus USB-C with Revolution preamp and APHEX DSP, zero-latency headphone monitoring and 32-bit float recording that rescues clipped takes in post. Heavier than it looks at nearly 900 grams, so budget a real boom arm.</p><p>The USB path carries the whole studio: high-pass, noise gate, compressor plus Aural Exciter and Big Bottom shape the voice before it hits the recording, and RØDE Connect, Central and Unify manage routing, streaming mixes and firmware. The analog XLR stays live in parallel, so the same mic feeds an interface or mixer whenever the setup grows up.</p><p>The honest trade-off: weight and price over the classic. At nearly 900 grams it demands a serious arm, and it costs more than the XLR-only PodMic plus a basic interface is not far off — but for solo podcasters recording to computer with no interface on the desk, nothing else combines broadcast tone, DSP and 32-bit float in one body.',
'<strong>El PodMic que se enchufa directo al portátil.</strong> La voz broadcast del clásico más USB-C con previo Revolution y DSP APHEX, monitoreo sin latencia y grabación en flotante de 32 bits que rescata tomas saturadas en postproducción. Más pesado de lo que parece con casi 900 gramos, así que reserva un brazo articulado de verdad.</p><p>La vía USB lleva el estudio entero: paso alto, puerta de ruido, compresor más Aural Exciter y Big Bottom moldean la voz antes de la grabación, y RØDE Connect, Central y Unify gestionan ruteo, mezclas de streaming y firmware. El XLR analógico sigue vivo en paralelo, así que el mismo micro alimenta interfaz o mesa cuando el montaje crezca.</p><p>El matiz honesto: peso y precio sobre el clásico. Con casi 900 gramos pide un brazo serio, y cuesta más que el PodMic XLR — una interfaz básica tampoco queda lejos — pero para podcasters en solitario que graban al ordenador sin interfaz en la mesa, nada más combina tono broadcast, DSP y flotante de 32 bits en un cuerpo.');
fs.writeFileSync(F, JSON.stringify(G, null, 2));
console.log('done');