const fs = require('fs');
const F = 'C:/Users/Daniel/projects/topmusiciangear/data/guides.json';
const G = require(F);
const g = G.find(x => x.id === 'best-mic-for-podcasting');
const byId = id => g.sections.find(s => (s.products || [])[0] === id);
const set = (id, en, es) => { const s = byId(id); s.content = en; s.content_es = es; console.log('OK ' + id); };

set(50,
'<strong>Drop it, soak it, shout into it — the show goes on.</strong> The SM58 exists for every situation where the microphone is the least of your worries and has to behave like it. A steel ball grille over a pneumatic shock mount shrugs off plosives, handling thumps and the occasional fall off a stand, while the presence lift keeps speech intelligible even through a muddy bar PA. There is nothing to power, nothing to configure and nothing to break.</p><p>That simplicity is also why multi-host tables standardize on it: one SM58 sounds exactly like the next, so matching four voices takes minutes instead of an hour of corrective EQ. Where it steps aside is pure fidelity — a large-diaphragm condenser in a treated room hears subtleties the 58 never will. For everything else that can go wrong on a gig night, this is the insurance policy.',
'<strong>Tíralo, mójalo, grítale — el programa sigue.</strong> El SM58 existe para cada situación donde el micrófono es lo de menos y tiene que comportarse como tal. Una rejilla esférica de acero sobre suspensión neumática se encoge de hombros ante golpes de voz, ruidos de manejo y alguna caída del pie, mientras el realce de presencia mantiene la voz inteligible hasta por una PA embarrada de bar. Nada que alimentar, nada que configurar, nada que romper.</p><p>Esa simpleza explica que las mesas con varios presentadores lo estandaricen: un SM58 suena exactamente igual que el siguiente, así que igualar cuatro voces lleva minutos en vez de una hora de EQ correctiva. Donde se aparta es en fidelidad pura — un condensador de diafragma grande en sala tratada escucha sutilezas que el 58 jamás oirá. Para todo lo demás que puede torcerse una noche de directo, esto es la póliza de seguros.');

set(197,
'<strong>Two problems kill first podcasts: room noise and weak gain. The PodMic solves both under one grille.</strong> Its tight cardioid pattern narrows the world down to the mouth in front of it, so untreated walls and keyboard clatter mostly stay out of the recording. And unlike flagship broadcast dynamics, it reaches full level on ordinary interface preamps — no booster, no cloudlifter, no second purchase hiding behind the first.</p><p>Inside the all-metal body, an internal pop filter and shock mount handle the mechanical chores, while the broadcast-tailored voicing adds the warmth thin voices need and tames the harshness cheap rooms add. It mounts on any boom arm, packs with a detachable cable, and simply works. Step up to the Procaster only when the room is treated and the voice deserves a bigger, deeper capsule.',
'<strong>Dos problemas matan los primeros podcasts: el ruido de la sala y la ganancia floja. El PodMic resuelve ambos bajo una rejilla.</strong> Su cardioide estrecho reduce el mundo a la boca que tiene delante, así que las paredes sin tratar y el tecleo se quedan fuera de la grabación. Y al contrario que los broadcast insignia, alcanza nivel completo con previos corrientes de interfaz — sin booster, sin cloudlifter, sin segunda compra escondida tras la primera.</p><p>Dentro del cuerpo metálico, el filtro antipop y la suspensión se encargan de la mecánica, mientras la ecualización broadcast suma la calidez que piden las voces finas y doma la aspereza que añaden las salas baratas. Enrosca en cualquier brazo, se recoge con cable desmontable y sin más funciona. Sube al Procaster solo cuando la sala esté tratada y la voz merezca una cápsula mayor y más profunda.');

set(329,
'<strong>Think of it as the PodMic after weight training.</strong> Same broadcast family, same Rode reliability story — but a full-size body around a large neodymium capsule that moves more air and says more at the bottom. Voices come out with chest and authority, the kind of weight that makes a host sound like the show owns the room. The 10-year warranty reads like Rode daring you to wear it out.</p><p>That presence has entry requirements, and they are non-negotiable: a treated space, a sturdy boom that forgets almost a kilo of metal exists, and a preamp with real clean gain — or an inline booster doing the heavy lifting. Skip any of the three and the magic thins out fast. Get them right and there is no dynamic under flagship money that sounds this substantial.',
'<strong>Piensa en él como el PodMic después del gimnasio.</strong> Misma familia broadcast, misma historia de fiabilidad Rode — pero un cuerpo de tamaño completo alrededor de una cápsula grande de neodimio que mueve más aire y dice más abajo. Las voces salen con pecho y autoridad, ese peso que hace sonar al presentador como dueño de la sala. Los 10 años de garantía suenan a Rode retándote a gastarlo.</p><p>Esa presencia pide requisitos de entrada, y no se negocian: espacio tratado, brazo robusto que olvide que sostiene casi un kilo de metal y previo con ganancia limpia de verdad — o un booster en línea haciendo el trabajo duro. Salta uno de los tres y la magia se afina rápido. Clávalos y no hay dinámico por debajo del dinero insignia que suene tan sustancioso.');

set(1,
'<strong>Gain first, glory after — that is the SM7B contract, and it pays out.</strong> The output is famously low, so the interface has to bring serious clean gain or an inline booster has to live between mic and preamp. Meet that price and the reward is the most forgiving broadcast tone ever put in a dynamic body: smooth top end with no sibilance landmines, bass rolloff that tames chesty proximity boom, and a presence switch for broadcast sheen.</p><p>No other dynamic rides an untreated room this gracefully. Reflections, computer hum and street bleed arrive quieter and duller, which is exactly why radio booths, streamers and chart-topping vocalists keep reaching for it decades on. Treat it as a system — mic plus gain — and there is still nothing safer for a voice that has to sound expensive on arrival.',
'<strong>Ganancia primero, gloria después — ese es el contrato del SM7B, y paga.</strong> La salida es famosa por baja, así que la interfaz tiene que traer ganancia limpia seria o un booster en línea tiene que vivir entre micro y previo. Paga ese precio y la recompensa es el tono broadcast más indulgente jamás metido en un cuerpo dinámico: agudo suave sin minas de sibilancia, recorte de graves que doma el boom de proximidad y presencia conmutable para brillo de emisión.</p><p>Ningún otro dinámico cabalga una sala sin tratar con esta elegancia. Reflexiones, zumbido de ordenador y calle llegan más bajos y apagados, y por eso cabinas de radio, streamers y vocalistas de éxito siguen echando mano de él décadas después. Trátalo como un sistema — micro más ganancia — y sigue sin haber nada más seguro para una voz que tiene que sonar cara al llegar.');

set(3,
'<strong>4 dBA. Read that twice: this microphone hears less of itself than the quietest bedroom it will ever record in.</strong> That vanishing noise floor is what the NT1 5th Gen sells, wrapped around a 1-inch condenser with the airy, extended top that makes vocals and acoustic instruments feel three-dimensional. Then Rode bolted a second microphone inside it: a USB-C path with 32-bit float capture, onboard DSP and direct monitoring.</p><p>In practice that means two different purchases in one box. Over XLR into a treated studio chain it behaves like a classic high-end condenser. Over USB into a laptop it becomes a self-contained recording rig where clipped shouts can be rescued after the fact and EQ, compression and de-essing happen before the file even lands. The catch never changed: it hears everything, so the room has to deserve it — barking dogs, radiators and all.',
'<strong>4 dBA. Léelo dos veces: este micrófono se oye a sí mismo menos que el dormitorio más silencioso que jamás grabará.</strong> Ese suelo de ruido evanescente es lo que vende el NT1 de 5.ª generación, envuelto en un condensador de 1 pulgada con el agudo aéreo y extendido que vuelve tridimensionales voces e instrumentos acústicos. Y luego Rode atornilló un segundo micro dentro: una vía USB-C con captura en flotante de 32 bits, DSP a bordo y monitoreo directo.</p><p>En la práctica son dos compras distintas en una caja. Por XLR a una cadena de estudio tratada se comporta como un condensador clásico de altos vuelos. Por USB a un portátil se vuelve un equipo de grabación autónomo donde los gritos saturados se rescatan después y la EQ, la compresión y el de-esser ocurren antes de que el archivo aterrice. La pega no cambió: lo oye todo, así que la sala tiene que merecerlo — perros ladrando, radiadores y todo.');

set(297,
'<strong>Everything the NT1 is, minus everything the NT1 is not.</strong> Same HF6 capsule, same 4 dBA floor, same honest top end — without the USB path, without DSP, without the premium. What remains is the shortest possible road between a voice and a finished-sounding recording: shock mount, pop filter and six meters of XLR in the box, phantom power from any interface, done.</p><p>That stripped-back brief is precisely the appeal for booths and studios that already own their chain. No drivers, no firmware, no app asking for updates before a session — a microphone that behaves like microphones behaved for fifty years, except quieter than nearly all of them. The day the setup grows a treated room and a real preamp, this is the condenser waiting at a price that leaves budget for the treatment itself.',
'<strong>Todo lo que el NT1 es, menos todo lo que no es.</strong> Misma cápsula HF6, mismo suelo de 4 dBA, mismo agudo honesto — sin vía USB, sin DSP, sin el premium. Lo que queda es el camino más corto entre una voz y una grabación con sonido terminado: suspensión, antipop y seis metros de XLR en la caja, phantom de cualquier interfaz, listo.</p><p>Ese planteamiento desnudo es justo el atractivo para cabinas y estudios que ya tienen su cadena. Sin drivers, sin firmware, sin app pidiendo actualizar antes de la sesión — un micro que se comporta como se comportaron cincuenta años, solo que más silencioso que casi todos. El día que el montaje sume sala tratada y previo de verdad, este es el condensador esperando a un precio que deja presupuesto para el tratamiento.');

set(194,
'<strong>Live streaming is hostile to good audio, and the MV7+ was built like it knows.</strong> Animated talkers who drift off-mic, laugh-bursts that clip lesser chains, keyboard warriors clattering two feet away — the auto-level DSP rides the chaos in real time while the touch panel shows exactly what is happening without alt-tabbing out of the game. USB-C carries the stream, XLR quietly records the safety copy for later.</p><p>Underneath sits genuine Shure dynamic character that needs far less preamp muscle than an SM7B, so modest interfaces stay clean all the way up. Nothing here chases the last audiophile percentile; everything chases the show surviving contact with reality. For desks that double as battlestations, it is the most forgiving route to consistently professional voice.',
'<strong>El directo es hostil con el buen audio, y el MV7+ está construido como si lo supiera.</strong> Locutores animados que se salen del eje, carcajadas que saturan cadenas menores, teclados traqueteando a medio metro — el DSP de nivel automático cabalga el caos en tiempo real mientras el panel táctil muestra qué pasa sin salir del juego. El USB-C lleva el directo, el XLR graba en silencio la copia de seguridad para después.</p><p>Debajo hay auténtico carácter dinámico Shure que pide mucho menos músculo de previo que un SM7B, así que las interfaces modestas se mantienen limpias hasta arriba. Nada aquí persigue el último percentil audiófilo; todo persigue que el programa sobreviva al contacto con la realidad. Para escritorios que son a la vez campo de batalla, es la ruta más indulgente hacia una voz profesional constante.');

set(252,
'<strong>One cable. That is the entire PodMic USB pitch, and for solo podcasters it ends most arguments.</strong> The familiar broadcast dynamic — pop filter, shock mount, swing mount and all — gains a USB-C side with Revolution preamp muscle, APHEX processing and a headphone jack with zero-latency monitoring. Plug into the laptop, put the interface money toward a boom arm, because at nearly 900 grams this thing will humble a desk stand.</p><p>The 32-bit float recorder inside deserves its own paragraph: levels stop being a source of fear. Set gain approximately right and shouts, laughs and whispered asides all survive to post-production, where they can be balanced instead of mourned. The analog XLR keeps working in parallel for the day the setup grows an interface — one microphone buys both the present and the future.',
'<strong>Un cable. Ese es todo el argumento del PodMic USB, y para podcasters en solitario zanja casi todo debate.</strong> El dinámico broadcast de siempre — filtro antipop, suspensión, soporte giratorio y todo — suma un lado USB-C con músculo de previo Revolution, procesado APHEX y salida de auriculares sin latencia. Enchufa al portátil y dedica el dinero de la interfaz a un brazo articulado, porque con casi 900 gramos esto humilla a un pie de sobremesa.</p><p>La grabadora en flotante de 32 bits merece párrafo propio: los niveles dejan de dar miedo. Ajusta la ganancia de forma aproximada y gritos, carcajadas y susurros sobreviven hasta la postproducción, donde se equilibran en vez de llorarse. El XLR analógico sigue funcionando en paralelo para el día que el montaje sume una interfaz — un micro compra el presente y el futuro.');
fs.writeFileSync(F, JSON.stringify(G, null, 2));
console.log('done');