var { execSync } = require('child_process');
var fs = require('fs');
var raw = execSync('git show a0587799f0^:data/products.json', { maxBuffer: 64 * 1024 * 1024 }).toString('utf8');
var a = JSON.parse(raw);
console.log('array length:', Array.isArray(a) ? a.length : 'NOT ARRAY');
var hits = a.filter(function (x) { return x && x.id > 315 && x.id < 330; });
hits.forEach(function (x) { console.log(x.id, '|', x.title); });
var sm = a.filter(function (x) { return x && (x.title || '').toLowerCase().indexOf('sm7') >= 0; });
console.log('--- SM7 hits ---');
sm.forEach(function (x) { console.log(x.id, '|', x.title); });