const fs = require('fs');
const g = JSON.parse(fs.readFileSync('data/guides.json','utf8'));
const idx = g.findIndex(x => x.id === 'best-32-channel-digital-mixers');
const guide = g[idx];

// Fix comparison table with CORRECT specs
const table = guide.sections.find(s => s.isTable);
table.content = '<div class="guide-table-wrapper"><table class="guide-table"><thead><tr><th>Product</th><th>Local I/O (XLR)</th><th>Processing Capacity</th><th>Sample Rate / Latency</th><th>Mix Buses</th><th>Multitrack Recording</th><th>Network Protocol</th></tr></thead><tbody><tr><td>Behringer X32</td><td>32 XLR</td><td>40 channels (32 mic + 8 aux)</td><td>48 kHz / 0.8 ms</td><td>16 aux + LR</td><td>USB 32-track</td><td>AES50</td></tr><tr><td>Midas M32 LIVE</td><td>32 XLR</td><td>40 channels (32 mic + 8 aux)</td><td>48 kHz / 0.8 ms</td><td>16 aux + LR</td><td>Dual SD 32-track</td><td>AES50</td></tr><tr><td>Allen &amp; Heath SQ-6</td><td>32 XLR (recallable)</td><td>48 channels</td><td>96 kHz / 0.7 ms</td><td>36 mix buses</td><td>USB 96-track (SQ-Drive)</td><td>SLink (Dante optional)</td></tr><tr><td>Soundcraft Ui24R</td><td>24 XLR</td><td>24 channels</td><td>48 kHz / ~1 ms</td><td>6 aux + LR</td><td>USB 24-track + SD 2-track</td><td>None</td></tr><tr><td>Yamaha TF3</td><td>24 XLR</td><td>48 channels</td><td>48 kHz / ~1 ms</td><td>20 aux + LR</td><td>USB 34-track</td><td>Dante (NY64-D optional)</td></tr><tr><td>PreSonus StudioLive SE 32R</td><td>32 XLR</td><td>32 channels</td><td>48 kHz / ~1 ms</td><td>16 FlexMix + LR</td><td>USB 32-track + SD 2-track</td><td>Dante (optional)</td></tr><tr><td>Midas M32R LIVE</td><td>16 XLR</td><td>32 channels</td><td>48 kHz / 0.8 ms</td><td>16 aux + LR</td><td>Dual SD 32-track</td><td>AES50</td></tr><tr><td>Mackie DL32SE</td><td>32 XLR</td><td>32 channels</td><td>48 kHz / ~1 ms</td><td>32 mix buses</td><td>USB 32-track</td><td>None</td></tr><tr><td>PreSonus StudioLive 32SC</td><td>32 XLR</td><td>32 channels</td><td>48 kHz / ~1 ms</td><td>16 FlexMix + LR</td><td>USB 32-track + SD 2-track</td><td>Dante (optional)</td></tr></tbody></table></div>';

table.content_es = '<div class="guide-table-wrapper"><table class="guide-table"><thead><tr><th>Producto</th><th>E/S Local (XLR)</th><th>Capacidad de Procesamiento</th><th>Frecuencia de Muestreo / Latencia</th><th>Buses de Mezcla</th><th>Grabacion Multipista</th><th>Protocolo de Red</th></tr></thead><tbody><tr><td>Behringer X32</td><td>32 XLR</td><td>40 canales (32 mic + 8 aux)</td><td>48 kHz / 0,8 ms</td><td>16 aux + LR</td><td>USB 32 pistas</td><td>AES50</td></tr><tr><td>Midas M32 LIVE</td><td>32 XLR</td><td>40 canales (32 mic + 8 aux)</td><td>48 kHz / 0,8 ms</td><td>16 aux + LR</td><td>Dual SD 32 pistas</td><td>AES50</td></tr><tr><td>Allen &amp; Heath SQ-6</td><td>32 XLR (recallables)</td><td>48 canales</td><td>96 kHz / 0,7 ms</td><td>36 buses de mezcla</td><td>USB 96 pistas (SQ-Drive)</td><td>SLink (Dante opcional)</td></tr><tr><td>Soundcraft Ui24R</td><td>24 XLR</td><td>24 canales</td><td>48 kHz / ~1 ms</td><td>6 aux + LR</td><td>USB 24 pistas + SD 2 pistas</td><td>Ninguno</td></tr><tr><td>Yamaha TF3</td><td>24 XLR</td><td>48 canales</td><td>48 kHz / ~1 ms</td><td>20 aux + LR</td><td>USB 34 pistas</td><td>Dante (NY64-D opcional)</td></tr><tr><td>PreSonus StudioLive SE 32R</td><td>32 XLR</td><td>32 canales</td><td>48 kHz / ~1 ms</td><td>16 FlexMix + LR</td><td>USB 32 pistas + SD 2 pistas</td><td>Dante (opcional)</td></tr><tr><td>Midas M32R LIVE</td><td>16 XLR</td><td>32 canales</td><td>48 kHz / 0,8 ms</td><td>16 aux + LR</td><td>Dual SD 32 pistas</td><td>AES50</td></tr><tr><td>Mackie DL32SE</td><td>32 XLR</td><td>32 canales</td><td>48 kHz / ~1 ms</td><td>32 buses de mezcla</td><td>USB 32 pistas</td><td>Ninguno</td></tr><tr><td>PreSonus StudioLive 32SC</td><td>32 XLR</td><td>32 canales</td><td>48 kHz / ~1 ms</td><td>16 FlexMix + LR</td><td>USB 32 pistas + SD 2 pistas</td><td>Dante (opcional)</td></tr></tbody></table></div>';

console.log('Table fixed');

fs.writeFileSync('data/guides.json', JSON.stringify(g, null, 2), 'utf8');
console.log('Saved');
