// best-monitors: overview skips media (each product section shows its own
// photo + buy buttons), KRK section links id 20, cons expanded to 4-5.
const fs = require('fs');
const G = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));
const g = G.find(x => x.id === 'best-monitors');
if (!g) throw new Error('guide not found');

g.sections[0].skipMedia = true;
g.sections[3].products = [20];

const C = (name, cons, cons_es) => ({ name, cons, cons_es });
const patch = [
  C('JBL 305P MkII',
    ['Modest 5-inch woofer can run out of headroom on bass-heavy material',
     'Rear-panel controls are minimal compared to room-EQ rivals',
     'No built-in room correction',
     'Faint amplifier hiss audible in very quiet rooms'],
    ['El woofer modesto de 5 pulgadas puede quedarse corto en material con muchos graves',
     'Los controles del panel trasero son mínimos frente a rivales con EQ de sala',
     'Sin corrección de sala integrada',
     'Leve siseo del amplificador audible en salas muy silenciosas']),
  C('Kali Audio LP-6 V2',
    ['No coaxial design, so imaging is not as pinpoint as the IN-8 V2',
     'Room EQ is set via dip switches, not automated software',
     'Analog inputs only — no digital or USB connection',
     'Boundary EQ trims placement issues but cannot replace real acoustic treatment'],
    ['Sin diseño coaxial, así que la imagen no es tan de precisión como la de la IN-8 V2',
     'El EQ de sala se ajusta con interruptores DIP, no con software automatizado',
     'Solo entradas analógicas — sin conexión digital ni USB',
     'El Boundary EQ corrige la colocación pero no sustituye el tratamiento acústico real']),
  C('KRK Rokit 7 G5',
    ['Bass is colored and generous, so it takes practice to mix on',
     'Less flattering top-end than ribbon or MTM rivals',
     'Generous low end can overwhelm small untreated rooms',
     'All tuning lives on the back panel — no app or digital control'],
    ['Los graves son coloreados y generosos, así que requiere práctica para mezclar con ellos',
     'Extremo alto menos halagador que los rivales de cinta o MTM',
     'Los graves generosos pueden saturar salas pequeñas sin tratar',
     'Todo el ajuste está en el panel trasero — sin app ni control digital']),
  C('Yamaha HS8',
    ['Forward, unforgiving midrange requires good room treatment',
     'No built-in room correction or DSP',
     'Large cabinet dominates small desks and needs breathing room',
     'Rear bass port demands wall clearance to avoid boom'],
    ['Medios presentados y exigentes que requieren buen tratamiento de sala',
     'Sin corrección de sala ni DSP integrados',
     'El gabinete grande domina escritorios pequeños y necesita espacio',
     'El puerto de graves trasero exige distancia a la pared para evitar retumbos']),
  C('Adam Audio A7V',
    ['Premium price for the class',
     'Ribbon tweeter is more delicate than a conventional dome',
     'Rear-ported design needs wall clearance unlike front-ported rivals',
     'DSP voicings and settings add complexity for plug-and-play buyers'],
    ['Precio premium para su clase',
     'El tweeter de cinta es más delicado que un domo convencional',
     'El puerto trasero necesita distancia a la pared, al contrario que rivales frontales',
     'Los voicings y ajustes DSP añaden complejidad si buscas enchufar y listo']),
  C('Kali Audio IN-8 V2',
    ['Large 8-inch driver needs more space than small nearfields',
     'Premium price among Kali\u2019s own line',
     'No auto-calibration — all room tuning is manual via rear switches',
     'The 8-inch woofer excites small-room modes, so placement matters'],
    ['El gran driver de 8 pulgadas necesita más espacio que los nearfields pequeños',
     'Precio premium dentro de la propia línea de Kali',
     'Sin autocalibración — todo el ajuste de sala es manual con interruptores traseros',
     'El woofer de 8 pulgadas excita los modos de salas pequeñas — la colocación importa']),
  C('Genelec 8010A',
    ['3-inch woofer keeps the low end present but not deep — bass-heavy mixes need a sub',
     'Priciest per driver in this guide',
     '104 dB max SPL limits loud tracking work',
     'Volume and EQ live on the rear panel — no front controls'],
    ['El woofer de 3 pulgadas mantiene los graves presentes pero no profundos — las mezclas con muchos graves necesitan un sub',
     'El más caro por driver de esta guía',
     'Los 104 dB máximos limitan el trabajo de grabación a volumen alto',
     'Volumen y EQ están en el panel trasero — sin controles frontales']),
  C('Neumann KH 80 DSP',
    ['Small driver limits bass depth on loud material',
     'Premium price for the class',
     'Full calibration needs the MA 1 kit, sold separately',
     'Deep settings require the Neumann.Control app and a network connection'],
    ['El driver pequeño limita la profundidad de graves en material fuerte',
     'Precio premium para su clase',
     'La calibración completa necesita el kit MA 1, vendido por separado',
     'Los ajustes profundos exigen la app Neumann.Control y conexión de red']),
  C('Genelec 8351B',
    ['Costs more than the other eight monitors in this guide combined',
     'Overkill for untreated bedrooms and small desks',
     'GLM AutoCal needs the GLM measurement kit, sold separately',
     '14.3 kg each — demands solid stands, not desktop placement',
     'Sold individually — a stereo pair doubles the already huge outlay'],
    ['Cuesta más que los otros ocho monitores de esta guía juntos',
     'Excesivo para dormitorios sin tratar y escritorios pequeños',
     'GLM AutoCal necesita el kit de medición GLM, vendido por separado',
     '14,3 kg cada uno — exigen soportes sólidos, no el escritorio',
     'Se vende por unidad — un par estéreo duplica el ya enorme desembolso']),
  C('Kali Audio WS-6.2',
    ['It is a subwoofer — you still need a monitor pair on top',
     'Adds another box, another cable run and another cost',
     'No auto-calibration — crossover, phase and level are set by ear',
     '31 lbs of subwoofer — not a box you move around'],
    ['Es un subwoofer — sigues necesitando un par de monitores encima',
     'Añade otra caja, otro cableado y otro coste',
     'Sin autocalibración — cruce, fase y nivel se ajustan a oído',
     '31 libras de subwoofer — no es una caja para mover de un lado a otro']),
  C('Kali Audio IN-UNF',
    ['Designed for 0.8-meter listening — not room monitors',
     'Overkill and over-complex for casual listening',
     'Three-piece system clutters a desk versus single-box monitors',
     'Satellites must be aimed precisely at your ears — fussy positioning',
     'Bass unit has to sit centered between the satellites, limiting desk layouts'],
    ['Diseñado para escucha a 0,8 metros — no son monitores de sala',
     'Excesivo y demasiado complejo para escucha casual',
     'El sistema de tres piezas recarga el escritorio frente a monitores de una sola caja',
     'Los satélites deben apuntarse con precisión a tus oídos — colocación exigente',
     'La unidad de graves debe ir centrada entre los satélites, lo que limita el escritorio']),
  C('Kali Audio LP-UNF',
    ['Small drivers limit output — will not fill a room',
     'Bluetooth is convenient, not for critical mixing',
     'No XLR inputs — RCA, TRS and USB-C only',
     '85 dB continuous output caps loud-tracking headroom'],
    ['Los drivers pequeños limitan la salida — no llenará una sala',
     'El Bluetooth es cómodo, no para mezcla crítica',
     'Sin entradas XLR — solo RCA, TRS y USB-C',
     'Los 85 dB continuos limitan el headroom para grabar fuerte'])
];
patch.forEach(p => {
  const v = g.verdictProsCons.find(x => x.name === p.name);
  if (!v) throw new Error('missing verdict: ' + p.name);
  v.cons = p.cons;
  v.cons_es = p.cons_es;
});
fs.writeFileSync('data/guides.json', JSON.stringify(G, null, 2));
const gg = JSON.parse(fs.readFileSync('data/guides.json', 'utf8')).find(x => x.id === 'best-monitors');
console.log('skipMedia s0: ' + gg.sections[0].skipMedia + ' | s3 products: ' + JSON.stringify(gg.sections[3].products));
console.log('pros/cons por producto:');
gg.verdictProsCons.forEach(v => console.log(' ' + v.name + ': pros=' + v.pros.length + ' cons=' + v.cons.length));
