const fs = require('fs');
const g = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));
const guide = g.find(x => x.id === 'compact-rhythm-devices');

const t = (en) => ({ content: `<p><strong>${en}</strong></p>`, content_es: `<p><strong>${en}</strong></p>` });

const sectionTexts = {
  617: {
    content: "<p><strong>Un potente motor de síntesis granular y veinte efectos master profesionales en un formato de apenas 300 gramos de peso.</strong> El P-6 te permite samplear directamente desde dispositivos móviles por USB-C, retorcer pequeños fragmentos de audio hasta convertirlos en texturas densas y secuenciar hasta 64 pasos con control de probabilidad. Es el sampler de bolsillo más profundo que Roland ha diseñado jamás.</p><p>Su pantalla de tan solo cuatro caracteres te obliga a navegar mediante atajos complejos y sus botones diminutos dificultan el finger-drumming fluido. Sin embargo, para diseñadores de sonido que viajan ligeros, ninguna otra máquina ofrece tanto en un tamaño tan reducido.</p>",
    content_es: "<p><strong>Un potente motor de síntesis granular y veinte efectos master profesionales en un formato de apenas 300 gramos de peso.</strong> El P-6 te permite samplear directamente desde dispositivos móviles por USB-C, retorcer pequeños fragmentos de audio hasta convertirlos en texturas densas y secuenciar hasta 64 pasos con control de probabilidad. Es el sampler de bolsillo más profundo que Roland ha diseñado jamás.</p><p>Su pantalla de tan solo cuatro caracteres te obliga a navegar mediante atajos complejos y sus botones diminutos dificultan el finger-drumming fluido. Sin embargo, para diseñadores de sonido que viajan ligeros, ninguna otra máquina ofrece tanto en un tamaño tan reducido.</p>"
  },
  615: {
    content: "<p><strong>Una calculadora de sampling que compite directamente con las grooveboxes tradicionales gracias a su capacidad para transformar ideas en beats en cuestión de segundos.</strong> El K.O. II captura el entorno mediante su micrófono integrado, trocea muestras con teclas sensibles a la presión y dispara efectos punch-in en vivo, todo bajo un chasis tan estilizado como el de una tablet.</p><p>Sus 128 MB de memoria total pueden quedarse cortos para proyectos complejos, carece de un modo canción tradicional y su cuerpo de plástico requiere un transporte cuidadoso. Pese a ello, como herramienta de diversión portátil e inmediata, sigue invicta en su categoría.</p>",
    content_es: "<p><strong>Una calculadora de sampling que compite directamente con las grooveboxes tradicionales gracias a su capacidad para transformar ideas en beats en cuestión de segundos.</strong> El K.O. II captura el entorno mediante su micrófono integrado, trocea muestras con teclas sensibles a la presión y dispara efectos punch-in en vivo, todo bajo un chasis tan estilizado como el de una tablet.</p><p>Sus 128 MB de memoria total pueden quedarse cortos para proyectos complejos, carece de un modo canción tradicional y su cuerpo de plástico requiere un transporte cuidadoso. Pese a ello, como herramienta de diversión portátil e inmediata, sigue invicta en su categoría.</p>"
  },
  621: {
    content: "<p><strong>Dos mil sonidos, dos motores de síntesis reales y muestreo digital en un chasis alargado de tan solo 500 gramos.</strong> La SEQTRAK fusiona la inmensa biblioteca del motor AWM2 con la profundidad de la síntesis FM de cuatro operadores. Permite grabar muestras, incluye altavoz y micrófono integrados, y se edita de forma impecable desde una aplicación móvil de primer nivel.</p><p>Dado que la edición profunda se delega por completo a la aplicación y la unidad carece de funciones nativas de troceo (chopping) en el propio hardware, el flujo de trabajo es híbrido. Para viajeros que buscan un estudio completo en una sola barra, se ha consolidado como el nuevo estándar.</p>",
    content_es: "<p><strong>Dos mil sonidos, dos motores de síntesis reales y muestreo digital en un chasis alargado de tan solo 500 gramos.</strong> La SEQTRAK fusiona la inmensa biblioteca del motor AWM2 con la profundidad de la síntesis FM de cuatro operadores. Permite grabar muestras, incluye altavoz y micrófono integrados, y se edita de forma impecable desde una aplicación móvil de primer nivel.</p><p>Dado que la edición profunda se delega por completo a la aplicación y la unidad carece de funciones nativas de troceo (chopping) en el propio hardware, el flujo de trabajo es híbrido. Para viajeros que buscan un estudio completo en una sola barra, se ha consolidado como el nuevo estándar.</p>"
  },
  622: {
    content: "<p><strong>Seis pistas de samples vinculadas a los revolucionarios parameter locks y trig conditions por el precio de un paquete de plugins.</strong> Su filosofía de un mando por función, sus secuencias de 64 pasos y una librería nativa de 300 sonidos curados por Splice la convierten en la máquina de Elektron más rápida de aprender.</p><p>Es un dispositivo puramente de reproducción (reproduce muestras importadas pero no graba audio directamente) y sus 64 MB de memoria RAM por proyecto restringen el uso de archivos masivos. Para adentrarse en la secuenciación DAWless con un presupuesto ajustado, no hay una herramienta que enseñe tanto por tan poco.</p>",
    content_es: "<p><strong>Seis pistas de samples vinculadas a los revolucionarios parameter locks y trig conditions por el precio de un paquete de plugins.</strong> Su filosofía de un mando por función, sus secuencias de 64 pasos y una librería nativa de 300 sonidos curados por Splice la convierten en la máquina de Elektron más rápida de aprender.</p><p>Es un dispositivo puramente de reproducción (reproduce muestras importadas pero no graba audio directamente) y sus 64 MB de memoria RAM por proyecto restringen el uso de archivos masivos. Para adentrarse en la secuenciación DAWless con un presupuesto ajustado, no hay una herramienta que enseñe tanto por tan poco.</p>"
  },
  618: {
    content: "<p><strong>Treinta y dos pads luminosos, ocho pistas de sample y cero menús digitales que se interpongan entre tus manos y el beat.</strong> La Circuit Rhythm te permite samplear directamente a la unidad, trocear y hacer resampling interno de forma autónoma, disparar efectos Grid FX desde su interfaz y trabajar hasta cuatro horas sin necesidad de enchufes.</p><p>La gestión y el respaldo de tus proyectos dependen de la aplicación Components, la memoria interna es finita y te tocará memorizar combinaciones de luces para ciertas funciones avanzadas. A cambio, para directos basados en la intuición auditiva, ofrece una velocidad de trabajo adictiva.</p>",
    content_es: "<p><strong>Treinta y dos pads luminosos, ocho pistas de sample y cero menús digitales que se interpongan entre tus manos y el beat.</strong> La Circuit Rhythm te permite samplear directamente a la unidad, trocear y hacer resampling interno de forma autónoma, disparar efectos Grid FX desde su interfaz y trabajar hasta cuatro horas sin necesidad de enchufes.</p><p>La gestión y el respaldo de tus proyectos dependen de la aplicación Components, la memoria interna es finita y te tocará memorizar combinaciones de luces para ciertas funciones avanzadas. A cambio, para directos basados en la intuición auditiva, ofrece una velocidad de trabajo adictiva.</p>"
  },
  623: {
    content: "<p><strong>La crudeza genuina de los 12 bits, un secuenciador de cuatro pistas y el potenciómetro Laidback ideado para inyectar un balanceo (swing) orgánico e imperfecto a tus ritmos al instante.</strong> El Lofi-12 samplea con ese clásico color crujiente de los noventa, permite interpretaciones cromáticas en sus dos octavas de teclas y ofrece doce efectos por pista junto a nueve master.</p><p>El límite de cuatro segundos por muestra puede frenar las composiciones basadas en loops largos y sus algoritmos de time-stretch son básicos. No obstante, para esculpir texturas de hip-hop clásico y boom-bap desde el sofá, es una de las opciones más honestas y con mayor carácter del mercado.</p>",
    content_es: "<p><strong>La crudeza genuina de los 12 bits, un secuenciador de cuatro pistas y el potenciómetro Laidback ideado para inyectar un balanceo (swing) orgánico e imperfecto a tus ritmos al instante.</strong> El Lofi-12 samplea con ese clásico color crujiente de los noventa, permite interpretaciones cromáticas en sus dos octavas de teclas y ofrece doce efectos por pista junto a nueve master.</p><p>El límite de cuatro segundos por muestra puede frenar las composiciones basadas en loops largos y sus algoritmos de time-stretch son básicos. No obstante, para esculpir texturas de hip-hop clásico y boom-bap desde el sofá, es una de las opciones más honestas y con mayor carácter del mercado.</p>"
  },
  624: {
    content: "<p><strong>Doscientas ranuras de memoria para samples, diez partes secuenciables y automatización en tiempo real (motion sequencing) por un precio imbatible.</strong> La segunda generación del Volca Sample dobla la memoria del modelo original, permite encadenar hasta dieciséis patrones para estructurar temas completos y gestiona las librerías vía USB de forma ágil.</p><p>Sus 8 MB de memoria total son reducidos, funciona mediante pilas AA tradicionales en lugar de batería de litio y su paleta de efectos es básica. Pese a ello, como primer paso en el mundo del muestreo por hardware para productores curiosos, no tiene rival en su rango de precio.</p>",
    content_es: "<p><strong>Doscientas ranuras de memoria para samples, diez partes secuenciables y automatización en tiempo real (motion sequencing) por un precio imbatible.</strong> La segunda generación del Volca Sample dobla la memoria del modelo original, permite encadenar hasta dieciséis patrones para estructurar temas completos y gestiona las librerías vía USB de forma ágil.</p><p>Sus 8 MB de memoria total son reducidos, funciona mediante pilas AA tradicionales en lugar de batería de litio y su paleta de efectos es básica. Pese a ello, como primer paso en el mundo del muestreo por hardware para productores curiosos, no tiene rival en su rango de precio.</p>"
  },
  625: {
    content: "<p><strong>Ocho pistas de audio estéreo dedicadas, motores de síntesis digital integrados y micrófono en un peso de tan solo 350 gramos.</strong> El Tracker Mini está diseñado para componer, hacer resampling, mezclar y masterizar temas enteros con una autonomía de hasta 8 horas de batería, permitiendo además exportar sus pistas independientes por USB directas a tu ordenador.</p><p>Su flujo de trabajo basado en pantallas verticales, botones y cursor exige semanas de práctica y el clic mecánico de sus teclas puede resultar sonoro en entornos nocturnos. Para compositores analíticos que disfrutan estructurando la música de forma visual y numérica, ninguna caja portátil llega tan lejos.</p>",
    content_es: "<p><strong>Ocho pistas de audio estéreo dedicadas, motores de síntesis digital integrados y micrófono en un peso de tan solo 350 gramos.</strong> El Tracker Mini está diseñado para componer, hacer resampling, mezclar y masterizar temas enteros con una autonomía de hasta 8 horas de batería, permitiendo además exportar sus pistas independientes por USB directas a tu ordenador.</p><p>Su flujo de trabajo basado en pantallas verticales, botones y cursor exige semanas de práctica y el clic mecánico de sus teclas puede resultar sonoro en entornos nocturnos. Para compositores analíticos que disfrutan estructurando la música de forma visual y numérica, ninguna caja portátil llega tan lejos.</p>"
  },
  144: {
    content: "<p><strong>Seis motores de síntesis FM (machines), la potencia del secuenciador de Elektron y un chasis ultra ligero de 800 gramos.</strong> El Model:Cycles simplifica la complejidad de la modulación FM convirtiendo cada motor en un instrumento sumamente intuitivo y maleable, animando tus grooves gracias a los automatismos de los parameter locks.</p><p>Carece por completo de motor de muestreo (es una máquina de síntesis pura), su pantalla OLED es compacta y los saltos físicos en el recorrido de sus potenciómetros requieren acostumbrarse. Para dar forma a bocetos electrónicos con texturas metálicas en cualquier parte, representa el acceso más económico al sonido Elektron.</p>",
    content_es: "<p><strong>Seis motores de síntesis FM (machines), la potencia del secuenciador de Elektron y un chasis ultra ligero de 800 gramos.</strong> El Model:Cycles simplifica la complejidad de la modulación FM convirtiendo cada motor en un instrumento sumamente intuitivo y maleable, animando tus grooves gracias a los automatismos de los parameter locks.</p><p>Carece por completo de motor de muestreo (es una máquina de síntesis pura), su pantalla OLED es compacta y los saltos físicos en el recorrido de sus potenciómetros requieren acostumbrarse. Para dar forma a bocetos electrónicos con texturas metálicas en cualquier parte, representa el acceso más económico al sonido Elektron.</p>"
  },
  128: {
    content: "<p><strong>El sonido legendario de las cajas 808, 909 y 606 condensado en una unidad a pilas que ocupa la mitad de espacio que su hermana mayor.</strong> La TR-6S ejecuta modelos analógicos virtuales ACB auténticos, añade síntesis FM editable e importación de samples, y cuenta con herramientas avanzadas de probabilidad, sub-pasos y grabación de movimiento.</p><p>Su secuenciador está limitado estrictamente a 6 pistas simultáneas y cuenta con un único mando físico global para ajustar los niveles, lo que ralentiza los cambios rápidos en vivo. Aun así, si buscas la pegada y los bombos clásicos de Roland en un formato de mochila totalmente autónomo, es la compra más inteligente frente al modelo insignia.</p>",
    content_es: "<p><strong>El sonido legendario de las cboxes 808, 909 y 606 condensado en una unidad a pilas que ocupa la mitad de espacio que su hermana mayor.</strong> La TR-6S ejecuta modelos analógicos virtuales ACB auténticos, añade síntesis FM editable e importación de samples, y cuenta con herramientas avanzadas de probabilidad, sub-pasos y grabación de movimiento.</p><p>Su secuenciador está limitado estrictamente a 6 pistas simultáneas y cuenta con un único mando físico global para ajustar los niveles, lo que ralentiza los cambios rápidos en vivo. Aun así, si buscas la pegada y los bombos clásicos de Roland en un formato de mochila totalmente autónomo, es la compra más inteligente frente al modelo insignia.</p>"
  }
};

// Fix intro section (section 0)
guide.sections[0].content = "<p><strong>La autonomía de la batería, el peso y la facilidad para controlar el hardware con una sola mano lo deciden todo cuando el estudio se reduce al espacio de tu mochila.</strong> Los samplers de bolsillo te permiten esbozar ritmos en cualquier parte, pero exigen memorizar bastantes atajos de menú; por contra, las grooveboxes con diseño en barra o rejilla sacrifican esa extrema portabilidad a cambio de una ejecución física mucho más cómoda. A la hora de elegir, prioriza primero tus hábitos de viaje y, en segundo lugar, el motor de sonido.</p><p>Las diez opciones que analizamos a continuación son totalmente portátiles, cuestan menos que cualquier modelo insignia y cada una ofrece un equilibrio honesto entre prestaciones y sacrificios técnicos.</p>";
guide.sections[0].content_es = guide.sections[0].content;

guide.sections.forEach(s => {
  const pid = s.products && s.products[0];
  const fix = sectionTexts[pid];
  if (fix) {
    s.content = fix.content;
    s.content_es = fix.content_es;
    console.log('Updated section for product', pid, ':', s.heading);
  }
});

fs.writeFileSync('data/guides.json', JSON.stringify(g, null, 2) + '\n');
console.log('Done.');
