const fs = require('fs');
const DIR = 'C:/Users/Daniel/projects/topmusiciangear/';
const guides = JSON.parse(fs.readFileSync(DIR + 'data/guides.json', 'utf8'));
const d = guides.find(x => x.id === 'guitar-bass-amps');
const f = d.featuredSnippet;
f.faq_q5_en = 'Is the Markbass CMD 102P IV worth it for gigging bassists?';
f.faq_a5_en = 'If you count kilograms — yes. The CMD 102P IV delivers 300 watts standalone (500W with an extension cab) through dual neodymium tens with the signature bi-band limiter, 4-band EQ and studio XLR out, all at 37.7 lb. It is the pro jazz, funk and rock choice when fidelity matters more than price.';
f.faq_q5_es = '¿Vale la pena el Markbass CMD 102P IV para bajistas de directo?';
f.faq_a5_es = 'Si cuentas kilos — sí. El CMD 102P IV entrega 300 vatios solo (500 W con extensión) por dieces de neodimio con limitador bi-banda, EQ de 4 bandas y XLR de estudio, todo en 17,1 kg. Es la elección pro de jazz, funk y rock cuando la fidelidad importa más que el precio.';
f.faq_q7_en = 'Which amp in this guide handles 5-string low B best?';
f.faq_a7_en = 'The Ampeg RB-115: its 15-inch speaker moves the air a low B needs, with SVT grind on demand. The Rumble 500 keeps up on 4-strings with punch, and the Markbass adds hi-fi headroom — but for sub-low authority, fifteen inches win.';
f.faq_q7_es = '¿Qué ampli de esta guía maneja mejor el Si grave de 5 cuerdas?';
f.faq_a7_es = 'El Ampeg RB-115: su altavoz de 15 pulgadas mueve el aire que el Si grave pide, con grind SVT a demanda. El Rumble 500 aguanta en 4 cuerdas con pegada, y el Markbass suma headroom hi-fi — pero para autoridad sub-grave, quince pulgadas ganan.';
f.faq_q8_en = 'Ampeg RB-115 or Markbass CMD 102P IV for classic vs modern tone?';
f.faq_a8_en = 'Classic SVT grit goes to the RB-115: Legacy preamp, footswitchable SGT overdrive and 15-inch depth. Modern hi-fi clarity goes to the Markbass: bi-band limiter, 4-band EQ and featherweight build. Pick grind or glass.';
f.faq_q8_es = '¿Ampeg RB-115 o Markbass CMD 102P IV para tono clásico vs moderno?';
f.faq_a8_es = 'El grit SVT clásico es del RB-115: previo Legacy, overdrive SGT conmutable y profundidad de 15 pulgadas. La claridad hi-fi moderna es del Markbass: limitador bi-banda, EQ de 4 bandas y construcción pluma. Elige grind o cristal.';
fs.writeFileSync(DIR + 'data/guides.json', JSON.stringify(guides, null, 2));
const s = JSON.stringify(d);
console.log('leftovers:', ['RB-210', 'Rumble 200', 'Spark LIVE'].map(n => n + '=' + s.includes(n)).join(' '));
