const fs = require('fs');
const g = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));
const guide = g.find(x => x.id === 'best-drum-machine');

const sectionTexts = {
  610: {
    content: "<p><strong>Una 808, una 909 y una 303 que caben en un bolsillo — por el precio de un paquete de plugins.</strong> La T-8 mete baterías Roland con tecnología ACB genuina más una línea de bajo TB-303 en apenas 310 gramos de peso y con 4,5 horas de autonomía. Los viajes y el sofá se vuelven estudios; las ideas se capturan al instante en vez de olvidarse.</p><p>El precio de lo diminuto son unos controles muy pequeños y la ausencia de sampling propio: lo que oyes es lo que Roland te da de fábrica. Para principiantes absolutos y viajeros que quieren ritmo en formato hardware real ya, nada arranca de forma más rápida ni económica.</p>",
    content_es: "<p><strong>Una 808, una 909 y una 303 que caben en un bolsillo — por el precio de un paquete de plugins.</strong> La T-8 mete baterías Roland con tecnología ACB genuina más una línea de bajo TB-303 en apenas 310 gramos de peso y con 4,5 horas de autonomía. Los viajes y el sofá se vuelven estudios; las ideas se capturan al instante en vez de olvidarse.</p><p>El precio de lo diminuto son unos controles muy pequeños y la ausencia de sampling propio: lo que oyes es lo que Roland te da de fábrica. Para principiantes absolutos y viajeros que quieren ritmo en formato hardware real ya, nada arranca de forma más rápida ni económica.</p>"
  },
  129: {
    content: "<p><strong>Dos sintetizadores, cuatro pistas de batería, dos canales MIDI — y ni un solo menú en el que perderse.</strong> La Circuit Tracks cambia las pantallas por 32 pads luminosos, haciendo que los principiantes estructuren sus temas guiándose por el oído en vez de por los ojos. Su batería integrada, el soporte para tarjetas microSD y sus 4 horas de autonomía inalámbrica se traducen en temas que empiezan en el tren y se terminan en casa.</p><p>Su edición profunda requiere conectar la aplicación Components para diseñar tus propios parches de sintetizador desde el ordenador. Sin embargo, para productores primerizos que buscan terminar canciones enteras sin lidiar con curvas de aprendizaje complejas, es el inicio más amable del ecosistema hardware gracias a su intuitivo sistema de encadenamiento de escenas.</p>",
    content_es: "<p><strong>Dos sintetizadores, cuatro pistas de batería, dos canales MIDI — y ni un solo menú en el que perderse.</strong> La Circuit Tracks cambia las pantallas por 32 pads luminosos, haciendo que los principiantes estructuren sus temas guiándose por el oído en vez de por los ojos. Su batería integrada, el soporte para tarjetas microSD y sus 4 horas de autonomía inalámbrica se traducen en temas que empiezan en el tren y se terminan en casa.</p><p>Su edición profunda requiere conectar la aplicación Components para diseñar tus propios parches de sintetizador desde el ordenador. Sin embargo, para productores primerizos que buscan terminar canciones enteras sin lidiar con curvas de aprendizaje complejas, es el inicio más amable del ecosistema hardware gracias a su intuitivo sistema de encadenamiento de escenas.</p>"
  },
  614: {
    content: "<p><strong>Diez voces analógicas, un mando por función, cero pantallas — y un potenciómetro \"Color\" que añade agresividad a cada tambor.</strong> La DrumBrute Impact destaca por la honestidad de su diseño: sin samples ni presets tras los que esconderse, ofrece un bombo que golpea el pecho, cajas contundentes y un sintetizador FM moldeable en vivo. Su secuenciador polirrítmico de 64 pasos con funciones roller y looper convierte los patrones en verdaderas actuaciones.</p><p>La naturaleza analógica corta en dos direcciones: no cuenta con almacenamiento para samples propios y la afinación puede sufrir ligeras derivas por la temperatura ambiental, lo cual forma parte de su encanto. Para amantes del rock, el industrial y la electrónica oscura que prefieren girar perillas físicas antes que hacer clic con el ratón, es la mayor diversión por cada libra invertida en hardware rítmico.</p>",
    content_es: "<p><strong>Diez voces analógicas, un mando por función, cero pantallas — y un potenciómetro \"Color\" que añade agresividad a cada tambor.</strong> La DrumBrute Impact destaca por la honestidad de su diseño: sin samples ni presets tras los que esconderse, ofrece un bombo que golpea el pecho, cajas contundentes y un sintetizador FM moldeable en vivo. Su secuenciador polirrítmico de 64 pasos con funciones roller y looper convierte los patrones en verdaderas actuaciones.</p><p>La naturaleza analógica corta en dos direcciones: no cuenta con almacenamiento para samples propios y la afinación puede sufrir ligeras derivas por la temperatura ambiental, lo cual forma parte de su encanto. Para amantes del rock, el industrial y la electrónica oscura que prefieren girar perillas físicas antes que hacer clic con el ratón, es la mayor diversión por cada libra invertida en hardware rítmico.</p>"
  },
  33: {
    content: "<p><strong>Pregunta en cualquier cabina de techno qué máquina marca el tempo de la sesión y la mitad de las veces se tratará de esta unidad.</strong> La TR-8S sigue siendo el estándar en directo porque ninguna otra pone baterías ACB (808/909), muestras importadas y faders dedicados por canal bajo tus diez dedos a la vez. Sus variaciones permiten cambiar kits enteros a mitad de compás; el público escucha la evolución del arreglo en tiempo real, no la congelación de un buffer de ordenador portátil.</p><p>Aunque navegar por sus submenús requiere cierta práctica bajo la superficie, sus seis salidas independientes y su ruteo de audio multicanal por USB la convierten en una herramienta sumamente flexible. Para directos electrónicos donde las manos ganan a los cursores, sigue siendo la respuesta por defecto.</p>",
    content_es: "<p><strong>Pregunta en cualquier cabina de techno qué máquina marca el tempo de la sesión y la mitad de las veces se tratará de esta unidad.</strong> La TR-8S sigue siendo el estándar en directo porque ninguna otra pone baterías ACB (808/909), muestras importadas y faders dedicados por canal bajo tus diez dedos a la vez. Sus variaciones permiten cambiar kits enteros a mitad de compás; el público escucha la evolución del arreglo en tiempo real, no la congelación de un buffer de ordenador portátil.</p><p>Aunque navegar por sus submenús requiere cierta práctica bajo la superficie, sus seis salidas independientes y su ruteo de audio multicanal por USB la convierten en una herramienta sumamente flexible. Para directos electrónicos donde las manos ganan a los cursores, sigue siendo la respuesta por defecto.</p>"
  },
  256: {
    content: "<p><strong>Dieciséis pads, cuarenta años de linaje, cero ordenadores — ahora optimizada con el doble de potencia de procesamiento.</strong> La MPC One G2 ejecuta de forma totalmente autónoma el flujo de trabajo que inventó la producción de hip-hop: trocea samples en su pantalla táctil de 7 pulgadas, secuencia 32 instancias de plugins junto a 16 pistas de audio y finaliza canciones con separación de Stems y más de 100 efectos de la suite AIR integrados.</p><p>Trabajar en formato standalone implica aceptar ciertos límites físicos: la pantalla táctil puede sentirse algo compacta frente a un monitor de estudio, sus 4 GB de RAM marcan el límite para librerías masivas de muestras y no tiene batería integrada para llevarla al parque. No obstante, con sus 64 GB de memoria interna, audio por USB-C de 24 canales y el renovado sistema operativo MPC 3 a bordo, es la One definitiva. Para beatmakers que piensan a través de los pads, nada habla tanto su mismo idioma.</p>",
    content_es: "<p><strong>Dieciséis pads, cuarenta años de linaje, cero ordenadores — ahora optimizada con el doble de potencia de procesamiento.</strong> La MPC One G2 ejecuta de forma totalmente autónoma el flujo de trabajo que inventó la producción de hip-hop: trocea samples en su pantalla táctil de 7 pulgadas, secuencia 32 instancias de plugins junto a 16 pistas de audio y finaliza canciones con separación de Stems y más de 100 efectos de la suite AIR integrados.</p><p>Trabajar en formato standalone implica aceptar ciertos límites físicos: la pantalla táctil puede sentirse algo compacta frente a un monitor de estudio, sus 4 GB de RAM marcan el límite para librerías masivas de muestras y no tiene batería integrada para llevarla al parque. No obstante, con sus 64 GB de memoria interna, audio por USB-C de 24 canales y el renovado sistema operativo MPC 3 a bordo, es la One definitiva. Para beatmakers que piensan a través de los pads, nada habla tanto su mismo idioma.</p>"
  },
  127: {
    content: "<p><strong>Samplea un sonido, estíralo, aplícale síntesis granular y secuéncialo en 128 pasos con automatizaciones (locks) en cada parámetro.</strong> La Digitakt II toma los pilares de la versión original y dobla la apuesta: 16 pistas nativas estéreo o MIDI, 400 MB de memoria de trabajo por proyecto, 20 GB de disco de alta velocidad y un generador euclidiano para ritmos con base matemática abstracta.</p><p>Esta profundidad requiere paciencia: el flujo de trabajo de Elektron premia el diseño minucioso y castiga las prisas, además de requerir un espacio fijo en tu escritorio. Para productores electrónicos avanzados que construyen temas enteros a partir de pequeños fragmentos y texturas de sonido, es uno de los instrumentos más profundos del mercado actual.</p>",
    content_es: "<p><strong>Samplea un sonido, estíralo, aplícale síntesis granular y secuéncialo en 128 pasos con automatizaciones (locks) en cada parámetro.</strong> La Digitakt II toma los pilares de la versión original y dobla la apuesta: 16 pistas nativas estéreo o MIDI, 400 MB de memoria de trabajo por proyecto, 20 GB de disco de alta velocidad y un generador euclidiano para ritmos con base matemática abstracta.</p><p>Esta profundidad requiere paciencia: el flujo de trabajo de Elektron premia el diseño minucioso y castiga las prisas, además de requerir un espacio fijo en tu escritorio. Para productores electrónicos avanzados que construyen temas enteros a partir de pequeños fragmentos y texturas de sonido, es uno de los instrumentos más profundos del mercado actual.</p>"
  },
  612: {
    content: "<p><strong>Cuatro voces analógicas rugiendo en circuitos reales y ocho digitales procesando modulaciones FM — todo ello dirigido por un secuenciador impecable.</strong> La Syntakt fusiona ambos mundos de Elektron: 37 motores de síntesis (machines) capaces de generar desde bombos analógicos atronadores hasta campanas digitales cristalinas, con pistas totalmente asignables a MIDI, parameter locks, modo canción y la tecnología Overbridge para integrarla perfectamente en tu DAW.</p><p>Su naturaleza híbrida implica un compromiso de diseño: no busca ofrecer el mono analógico más profundo ni la polifonía digital más extensa del catálogo, y su pantalla pequeña mantiene viva la dinámica de navegación por menús. Para productores que buscan baterías robustas, líneas de bajo sólidas y texturas experimentales en una sola caja compacta, representa el equilibrio híbrido ideal.</p>",
    content_es: "<p><strong>Cuatro voces analógicas rugiendo en circuitos reales y ocho digitales procesando modulaciones FM — todo ello dirigido por un secuenciador impecable.</strong> La Syntakt fusiona ambos mundos de Elektron: 37 motores de síntesis (machines) capaces de generar desde bombos analógicos atronadores hasta campanas digitales cristalinas, con pistas totalmente asignables a MIDI, parameter locks, modo canción y la tecnología Overbridge para integrarla perfectamente en tu DAW.</p><p>Su naturaleza híbrida implica un compromiso de diseño: no busca ofrecer el mono analógico más profundo ni la polifonía digital más extensa del catálogo, y su pantalla pequeña mantiene viva la dinámica de navegación por menús. Para productores que buscan baterías robustas, líneas de bajo sólidas y texturas experimentales en una sola caja compacta, representa el equilibrio híbrido ideal.</p>"
  },
  613: {
    content: "<p><strong>Cuatro voces híbridas, un mando por función, cero menús digitales tras los que esconderse — y un sonido colosal capaz de exprimir cualquier sistema de sonido.</strong> La Pērkons HD-01 pasa sus motores digitales a través de filtros analógicos dedicados por voz hacia un delay analógico BBD integrado, todo en un chasis reforzado de tamaño maleta concebido para ser tocado con agresividad. Permite almacenar hasta 64 kits de puro techno industrial avanzado.</p><p>Su precio y sus 3,7 kg de peso la anclan permanentemente al estudio, careciendo además de motor de sampling. Sin embargo, para productores profesionales de techno que buscan tocar sus equipos con la expresividad de un instrumento físico analógico, es un objeto de deseo absoluto: nada en el mercado se ve ni golpea con tanta contundencia.</p>",
    content_es: "<p><strong>Cuatro voces híbridas, un mando por función, cero menús digitales tras los que esconderse — y un sonido colosal capaz de exprimir cualquier sistema de sonido.</strong> La Pērkons HD-01 pasa sus motores digitales a través de filtros analógicos dedicados por voz hacia un delay analógico BBD integrado, todo en un chasis reforzado de tamaño maleta concebido para ser tocado con agresividad. Permite almacenar hasta 64 kits de puro techno industrial avanzado.</p><p>Su precio y sus 3,7 kg de peso la anclan permanentemente al estudio, careciendo además de motor de sampling. Sin embargo, para productores profesionales de techno que buscan tocar sus equipos con la expresividad de un instrumento físico analógico, es un objeto de deseo absoluto: nada en el mercado se ve ni golpea con tanta contundencia.</p>"
  }
};

guide.sections.forEach(s => {
  const pid = s.products && s.products[0];
  const fix = sectionTexts[pid];
  if (fix) {
    s.content = fix.content;
    s.content_es = fix.content_es;
    console.log('Updated section for product', pid, ':', s.heading);
  }
});

fs.writeFileSync('data/guides.json', JSON.stringify(g, null, 2) + '\n');
console.log('Done.');
