// beginner-bass-guitars: rewrite 3 stale thematic sections, append 13 per-product sections.
const fs = require('fs');
const G = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));
const S = (heading, heading_es, content, content_es, products) => ({ heading, heading_es, content, content_es, products });

{
  const g = G.find(x => x.id === 'beginner-bass-guitars');
  g.sections[0].content = '<p><strong>A beginner bass needs three things: a comfortable neck, stable tuning, and a sound that makes you pick it up.</strong> Bass frets sit wider apart than guitar frets, so neck profile matters more here — the Precision and Jazz profiles below are the reference because sixty years of players shaped them. Shorter practice sessions on a comfortable neck beat long fights with a baseball bat.</p><p><strong>Start passive if you can.</strong> Passive pickups need no battery, sound warm and natural, and teach your hands dynamics. Active EQ (found on several basses below) adds onboard shaping for modern styles — useful, but one more thing to learn. Either way, prioritize light weight: shoulder pain kills practice streaks.</p><p>For style comparisons, see <a class="guide-link-btn" href="/guides/best-bass-under-700.html">Best basses under $700</a> and <a class="guide-link-btn" href="/guides/fender-bass-guide.html">Fender bass guide</a>.</p>';
  g.sections[0].content_es = '<p><strong>Un bajo para empezar necesita tres cosas: mástil cómodo, afinación estable y un sonido que te haga cogerlo.</strong> Los trastes de bajo están más separados que los de guitarra, así que el perfil del mástil importa más aquí — los perfiles Precision y Jazz de abajo son la referencia porque sesenta años de bajistas los moldearon. Sesiones cortas en mástil cómodo ganan a peleas largas con un bate.</p><p><strong>Empieza pasivo si puedes.</strong> Las pastillas pasivas no piden batería, suenan cálidas y naturales, y enseñan dinámica a tus manos. La EQ activa (presente en varios bajos de abajo) añade moldeo a bordo para estilos modernos — útil, pero una cosa más que aprender. En todo caso, prioriza poco peso: el dolor de hombro mata rachas de práctica.</p><p>Para comparar estilos, revisa <a class="guide-link-btn" href="/guides/best-bass-under-700_es.html">Mejores bajos bajo $700</a> y <a class="guide-link-btn" href="/guides/fender-bass-guide_es.html">Guía de bajos Fender</a>.</p>';
  g.sections[1].content = '<p><strong>Modern manufacturing made affordable basses sound remarkably good — the gap is fit, finish and electronics, not tone.</strong> Look for straight necks, level frets and quiet electronics. Rolled fretboard edges (found on several picks below) make budget necks feel expensive; sealed tuners and bone or compensated nuts hold tuning through real practice.</p><p><strong>Passive versus active is a taste choice, not a quality ladder.</strong> Passive P/J layouts give timeless punch with zero maintenance; active two and three-band EQs give slap-friendly scoop and modern bite at the cost of a 9-volt battery. Both appear across the price range below.</p>';
  g.sections[1].content_es = '<p><strong>La fabricación moderna hizo que los bajos asequibles suenen notablemente bien — la diferencia está en ajuste, acabado y electrónica, no en tono.</strong> Busca mástiles rectos, trastes nivelados y electrónica silenciosa. Los bordes matados (presentes en varias elecciones de abajo) hacen que mástiles económicos se sientan caros; las clavijas selladas y cejuelas compensadas aguantan la afinación en práctica real.</p><p><strong>Pasivo contra activo es gusto, no escalera de calidad.</strong> Los P/J pasivos dan pegada atemporal sin mantenimiento; las EQ activas de dos y tres bandas dan scoop para slap y mordida moderna a cambio de una batería de 9 voltios. Ambos aparecen en todo el rango de abajo.</p>';
  g.sections[2].content = '<p><strong>Fender invented the modern bass guitar twice: the Precision in 1951 and the Jazz in 1960.</strong> The split-coil P pickup gives thick, punchy fundamentals that sit under guitars; the dual single-coil J gives brighter, articulate mids that cut through. Most working bassists eventually own one of each — the Squier and Player II picks below cover both at every budget.</p><p>For the full Fender-only breakdown, see <a class="guide-link-btn" href="/guides/fender-bass-guide.html">Fender bass guide</a>.</p>';
  g.sections[2].content_es = '<p><strong>Fender inventó el bajo moderno dos veces: el Precision en 1951 y el Jazz en 1960.</strong> La pastilla split-coil P da fundamentales gruesos y pegados bajo las guitarras; la J de dos simples da medios brillantes y articulados que cortan. La mayoría de bajistas trabajadores terminan con uno de cada — las elecciones Squier y Player II de abajo cubren ambos en cada presupuesto.</p><p>Para el desglose solo Fender, revisa <a class="guide-link-btn" href="/guides/fender-bass-guide_es.html">Guía de bajos Fender</a>.</p>';

  g.sections.push(
    S('Squier Affinity PJ: Maximum Bass for Minimum Money', 'Squier Affinity PJ: Máximo bajo por mínimo dinero',
      '<strong>Split-coil Precision punch plus a Jazz bridge single-coil in a lightweight poplar body.</strong> Two tones that defined records, twenty maple frets, die-cast tuners. The cheapest honest way into real Fender-family feel and the default first-bass recommendation.',
      '<strong>Pegada Precision split-coil más single-coil Jazz en puente, en cuerpo ligero de álamo.</strong> Dos tonos que definieron discos, veinte trastes de arce, clavijas fundidas. La forma honesta más barata de entrar al tacto familia Fender y la primera recomendación por defecto.', [158]),
    S('Yamaha TRBX304: Active Modern Workhorse', 'Yamaha TRBX304: Caballo de batalla activo moderno',
      '<strong>Dual humbuckers with three-band active EQ and 24 rosewood frets for players who want modern shaping on board.</strong> Sculpted body, die-cast hardware, 34-inch scale. The pick when slap, rock bite and onboard control matter more than vintage vibe.',
      '<strong>Dobles humbuckers con EQ activa de tres bandas y 24 trastes de palisandro para quien quiere moldeo moderno a bordo.</strong> Cuerpo esculpido, hardware fundido, escala 34". La elección cuando el slap, la mordida rock y el control a bordo importan más que la vibra vintage.', [159]),
    S('Ibanez SR300E: The Speed Neck', 'Ibanez SR300E: El mástil de velocidad',
      '<strong>Thin SR5-profile neck, light okoume body and dual PowerSpan coils with two-band active EQ.</strong> Twenty-four frets for players coming from guitar or with small hands. Modern looks, modern tones, minimum shoulder tax.',
      '<strong>Mástil fino perfil SR5, cuerpo ligero de okoume y dobles bobinas PowerSpan con EQ activa de dos bandas.</strong> Veinticuatro trastes para guitarristas convertidos o manos pequeñas. Estética moderna, tonos modernos, impuesto mínimo al hombro.', [160]),
    S('Sterling Ray4: Affordable StingRay Sting', 'Sterling Ray4: Picadura StingRay asequible',
      '<strong>One ceramic humbucker with two-band active preamp: the funk-rock slap voice that defined records.</strong> Schaller-style hardware, 21 maple frets, 34-inch scale. Single-pickup simplicity that forces your hands to find the tones.',
      '<strong>Un humbucker cerámico con previo activo de dos bandas: la voz funk-rock del slap que definió discos.</strong> Hardware estilo Schaller, 21 trastes de arce, escala 34". Simplicidad de una pastilla que obliga a tus manos a buscar los tonos.', [161]),
    S('Squier Classic Vibe 60s Jazz: Vintage for Less', 'Squier Classic Vibe 60s Jazz: Vintage por menos',
      '<strong>Fender-designed alnico J pickups, slim C neck with vintage tint and twenty maple frets.</strong> The growly bridge-pickup voice of countless records, with looks to match. The vintage-spec Jazz Bass experience without vintage money.',
      '<strong>Pastillas J alnico diseñadas por Fender, mástil C fino con tinte vintage y veinte trastes de arce.</strong> La voz gruñona de pastilla de puente de incontables discos, con estética a juego. La experiencia Jazz Bass de specs vintage sin dinero vintage.', [157]),
    S('Sire Marcus Miller V5R: Roasted Passive Value', 'Sire Marcus Miller V5R: Valor pasivo tostado',
      '<strong>Roasted hard-maple neck with rolled Edgeless edges, alder body and passive Vintage-J Revolution pickups.</strong> Open-gear tuners, simple volume-plus-tone wiring, twenty frets. Vintage jazz tone with a neck that feels broken-in from day one.',
      '<strong>Mástil de arce duro tostado con bordes matados Edgeless, cuerpo de aliso y pastillas pasivas Vintage-J Revolution.</strong> Clavijas abiertas, cableado simple volumen-más-tono, veinte trastes. Tono jazz vintage con mástil que se siente rodado desde el día uno.', [326]),
    S('Fender Player II Precision: The Real P-Bass', 'Fender Player II Precision: El P-Bass de verdad',
      '<strong>Alder body, Modern C maple neck and Player Series Alnico V split-coil: the thick Motown-to-punk fundamental.</strong> Rolled edges, medium-jumbo frets, Fender hardware. The bass that sits under guitars in every genre without fighting.',
      '<strong>Cuerpo de aliso, mástil Modern C de arce y split-coil Alnico V Player Series: la fundamental gruesa de Motown a punk.</strong> Bordes matados, trastes medium-jumbo, hardware Fender. El bajo que se sienta bajo las guitarras en cada género sin pelear.', [441]),
    S('Fender Player II Jazz: Articulate and Fast', 'Fender Player II Jazz: Articulado y rápido',
      '<strong>Dual Alnico V Jazz single-coils in alder with a Modern C neck for snappy, detailed mids.</strong> Two volumes plus tone for endless blending, twenty maple frets. The fusion, funk and Latin players choice for definition.',
      '<strong>Dobles simples Jazz Alnico V en aliso con mástil Modern C para medios rápidos y detallados.</strong> Dos volúmenes más tono para mezclas infinitas, veinte trastes de arce. La elección de fusión, funk y latinos por definición.', [442]),
    S('Fender AmPro II Precision: Professional Standard', 'Fender AmPro II Precision: Estándar profesional',
      '<strong>V-Mod II split-coil with modern punch over vintage warmth, Deep C neck and Greasebucket tone circuit.</strong> Twenty maple frets, Fender hardware, rolled edges. The session P-Bass that producers ask for by name.',
      '<strong>Split-coil V-Mod II con pegada moderna sobre calidez vintage, mástil Deep C y circuito Greasebucket.</strong> Veinte trastes de arce, hardware Fender, bordes matados. El P-Bass de sesión que los productores piden por nombre.', [155]),
    S('Fender AmPro II Jazz: The Working Pro J', 'Fender AmPro II Jazz: El J pro trabajador',
      '<strong>Dual V-Mod II single-coils with richer harmonics, slim-taper Deep C neck and treble-bleed volume circuit.</strong> Articulate voice that stays clear when rolling back. The pro Jazz Bass for night-after-night reliability.',
      '<strong>Dobles simples V-Mod II con armónicos más ricos, mástil Deep C de conicidad fina y circuito treble-bleed.</strong> Voz articulada que se mantiene clara al bajar volumen. El Jazz Bass pro para noches de fiabilidad.', [156]),
    S('Fender Ultra II Precision: Flagship Active P', 'Fender Ultra II Precision: P activo insignia',
      '<strong>Noiseless P plus J pickups with S-1 switched active preamp and three-band EQ on a quartersawn Modern D neck.</strong> Compound-radius ebony-or-maple board, HiMass bridge, sculpted heel. Zero hum, total control, flagship money.',
      '<strong>Pastillas P más J Noiseless con previo activo conmutado S-1 y EQ de tres bandas en mástil Modern D de cuartos.</strong> Diapasón radio compuesto ébano-o-arce, puente HiMass, talón esculpido. Cero ruido, control total, dinero insignia.', [185]),
    S('Sire Marcus Miller V5: Modern Price, Vintage Voice', 'Sire Marcus Miller V5: Precio moderno, voz vintage',
      '<strong>Roasted maple C neck, alder body and Marcus Vintage-J set with true passive volume-volume-tone wiring.</strong> Premium open-gear tuners, bone nut, twenty frets. Organic dynamics for players who ride the volume knob.',
      '<strong>Mástil C de arce tostado, cuerpo de aliso y set Marcus Vintage-J con cableado pasivo real volumen-volumen-tono.</strong> Clavijas premium abiertas, cejuela de hueso, veinte trastes. Dinámica orgánica para quien cabalga el knob de volumen.', [163]),
    S('ESP LTD B-204SM: Active Rock Machine', 'ESP LTD B-204SM: Máquina rock activa',
      '<strong>Spalted-maple-topped ash body, thin-U five-piece neck with 24 extra-jumbo jatoba frets, SB-4 pickups and ABQ-3 three-band active EQ.</strong> String-through bridge for sustain. Built for loud stages and fast hands.',
      '<strong>Cuerpo fresno con tapa spalted, mástil U fino de cinco piezas con 24 trastes XJ de jatoba, pastillas SB-4 y EQ activa ABQ-3 de tres bandas.</strong> Puente string-through para sustain. Hecho para escenarios ruidosos y manos rápidas.', [165])
  );
}
fs.writeFileSync('data/guides.json', JSON.stringify(G, null, 2));
const gg = id => JSON.parse(fs.readFileSync('data/guides.json', 'utf8')).find(x => x.id === id);
['guitar-bass-amps', 'beginner-bass-guitars'].forEach(id => {
  const g = gg(id);
  console.log(id + ': cols=' + g.productTable.columns.length + ' verdict=' + g.verdictProsCons.length + ' sections=' + g.sections.length + ' rowsok=' + g.productTable.rows.every(r => r.values.length === g.productTable.columns.length));
});
