const fs = require('fs');
const F = 'C:/Users/Daniel/projects/topmusiciangear/data/guides.json';
const G = require(F);
const g = G.find(x => x.id === 'best-mic-for-podcasting');

// ---- S0 cleanup: duplicated phrases, "in the world" x2, prices in prose, duplicated links ----
g.sections[0].content = '<p><strong>Dynamic microphones are the safe choice for most podcasters.</strong> The Shure SM7B is the reference broadcast microphone for untreated rooms, where rejection and a ready-to-air tone matter. The Audio-Technica AT2005USB is the starter equivalent with USB and XLR outputs for creators who upgrade their setup later.</p><p>Condenser microphones like the Rode NT1 capture more detail and high-frequency presence, making voices sound richer and more present — but they need a treated room and an interface to shine. They also pick up more room noise, keyboard clicks, and computer fans. If your room is not acoustically treated, a condenser will make your podcast sound worse, not better.</p><p>For podcast microphone comparisons, see our <a class="guide-link-btn" href="/guides/best-microphone.html">Best microphones guide</a> <a class="guide-link-btn" href="/guides/usb-mics.html">Best USB microphones</a> <a class="guide-link-btn" href="/guides/mics-for-creators.html">Best mic for streaming</a></p>';
g.sections[0].content_es = '<p><strong>Los micrófonos dinámicos son la opción segura para la mayoría de podcasters.</strong> El Shure SM7B es el micrófono broadcast de referencia para salas sin tratar, donde importan el rechazo al ruido y un tono listo para emitir. El Audio-Technica AT2005USB es su equivalente inicial con salidas USB y XLR para quien mejora su equipo más adelante.</p><p>Los condensadores como el Rode NT1 capturan más detalle y presencia en agudos, con voces más ricas y presentes — pero piden sala tratada e interfaz para brillar. También recogen más ruido de la habitación, clics de teclado y ventiladores del ordenador. Si tu sala no está tratada acústicamente, un condensador hará que tu podcast suene peor, no mejor.</p><p>Para comparar micrófonos de podcast, consulta nuestra <a class="guide-link-btn" href="/guides/best-microphone.html">Guía de micrófonos</a> <a class="guide-link-btn" href="/guides/usb-mics.html">Mejores micrófonos USB</a> <a class="guide-link-btn" href="/guides/mics-for-creators.html">Mejor micrófono para streaming</a></p>';

// ---- S1 cleanup: duplicated sentences, prices in prose, natural ES ----
g.sections[1].content = '<p><strong>Multi-host podcasts need matching microphones and a multi-channel interface.</strong> Each host should use the same microphone model for consistent sound. The Rode PodMic and Shure MV7+ are popular choices for multi-host setups because their tight pickup rejects bleed from the other hosts.</p><p>For larger shows with 3–4 hosts, a multi-channel interface with built-in processing handles every input. For audio recording interfaces specifically, see <a class="guide-link-btn" href="/guides/best-interface.html">Best audio interface guide</a></p>';
g.sections[1].content_es = '<p><strong>Los podcasts con varios presentadores necesitan el mismo micrófono y una interfaz multicanal.</strong> Cada voz debería usar el mismo modelo para un sonido consistente. El Rode PodMic y el Shure MV7+ son elecciones habituales en estos montajes porque su captación cerrada rechaza el sonido de los demás micros.</p><p>En programas grandes de 3–4 voces, una interfaz multicanal con procesado integrado maneja todas las entradas. Para interfaces de grabación, consulta la <a class="guide-link-btn" href="/guides/best-interface.html">Guía de mejores interfaces de audio</a></p>';

// ---- 8 new review sections (template: hook + tech + use + who), no prices, no 1st person ----
const SECS = [
{ h: 'Shure SM58: A Closer Look', hes: 'Shure SM58: análisis detallado', p: [50],
  en: '<strong>The vocal mic that survives everything the stage throws at it.</strong> A cardioid dynamic with a pneumatic shock mount and a steel-mesh ball grille: plosives and handling thumps die before reaching the capsule, while the tailored presence rise keeps vocals intelligible over loud bands. No power needed, no switches to bump, no fragility — it works in rain, heat and drops that kill condensers. The standard nightmare-free choice for live vocals, rehearsals and podcast guests who have never held a mic.',
  es: '<strong>El micro de voz que sobrevive a todo lo que le echa el escenario.</strong> Dinámico cardioide con suspensión neumática y rejilla esférica de acero: los golpes de voz y el ruido de manejo mueren antes de llegar a la cápsula, mientras el realce de presencia mantiene la voz inteligible sobre bandas ruidosas. Sin alimentación, sin interruptores que mover por error, sin fragilidad — funciona con lluvia, calor y caídas que matan a un condensador. La opción sin dramas para directo, ensayos e invitados de podcast que nunca han sujetado un micro.' },
{ h: 'Rode PodMic: A Closer Look', hes: 'Rode PodMic: análisis detallado', p: [197],
  en: '<strong>Broadcast tone without the broadcast budget or the gain headache.</strong> A cardioid dynamic tuned for speech, with an internal pop filter and shock mounting plus a swing mount in the box. The tight pickup keeps untreated rooms and co-hosts out of the recording, and the voicing flatters thin or harsh voices with broadcast-style warmth. Pairs with any interface or mixer — the default recommendation for first serious podcast setups.',
  es: '<strong>Tono broadcast sin presupuesto broadcast ni dolores de ganancia.</strong> Dinámico cardioide ajustado para la voz, con filtro antipop y suspensión internos más soporte giratorio en la caja. Su captación cerrada deja fuera la sala sin tratar y a los compañeros de mesa, y su ecualización favorece voces finas o ásperas con calidez radiofónica. Funciona con cualquier interfaz o mesa — la recomendación por defecto para el primer montaje de podcast serio.' },
{ h: 'Rode Procaster: A Closer Look', hes: 'Rode Procaster: análisis detallado', p: [329],
  en: '<strong>When the PodMic is not enough mic.</strong> A full-size broadcast dynamic with a large neodymium capsule, tight cardioid pattern and 10-year warranty. Compared with its smaller sibling it sounds bigger and more authoritative, with deeper low-end weight for deep voices — at the cost of size, weight and gain hunger that demands a strong preamp or inline booster. Built for dedicated podcast studios and radio booths.',
  es: '<strong>Cuando el PodMic se queda corto.</strong> Dinámico broadcast de tamaño completo con cápsula grande de neodimio, cardioide estrecho y 10 años de garantía. Frente a su hermano pequeño suena más grande y autoritario, con más peso en graves para voces profundas — a cambio de tamaño, peso y un apetito de ganancia que pide un previo potente o un booster en línea. Pensado para estudios de podcast dedicados y cabinas de radio.' },
{ h: 'Shure SM7B: A Closer Look', hes: 'Shure SM7B: análisis detallado', p: [1],
  en: '<strong>The broadcast standard that forgives bad rooms.</strong> A large-diaphragm dynamic with internal shock mounting, detachable windscreens and bass-rolloff plus presence switches. Rejection and a smooth, sibilance-free top end make untreated bedrooms sound treated — the trade is very low output that demands serious clean gain from the interface or an inline booster. The mic of radio legends and the no-risk pick for flagship vocal chains.',
  es: '<strong>El estándar broadcast que perdona salas malas.</strong> Dinámico de diafragma grande con suspensión interna, paravientos desmontables e interruptores de recorte de graves y presencia. Su rechazo y su agudo suave sin sibilancia hacen que un dormitorio sin tratar suene tratado — a cambio de una salida muy baja que exige ganancia limpia seria de la interfaz o un booster en línea. El micro de las leyendas de la radio y la apuesta segura para cadenas vocales insignia.' },
{ h: 'Rode NT1 5th Generation: A Closer Look', hes: 'Rode NT1 5.ª generación: análisis detallado', p: [3],
  en: '<strong>Silence you can measure, with a USB cable attached.</strong> A 1-inch condenser at 4 dBA self-noise — quieter than most treated rooms — with Dual Connect offering classic 48V XLR and 32-bit float USB-C from the same body. Detail, air and low-end honesty that dynamics cannot reach, provided the room is treated and background noise is controlled. The studio vocal upgrade once the space is ready.',
  es: '<strong>Silencio medible, con cable USB incluido.</strong> Condensador de 1 pulgada con 4 dBA de ruido propio — más silencioso que la mayoría de salas tratadas — con Dual Connect que ofrece XLR clásico de 48V y USB-C en flotante de 32 bits en el mismo cuerpo. Detalle, aire y honestidad en graves que ningún dinámico alcanza, siempre que la sala esté tratada y el ruido de fondo controlado. La mejora de estudio cuando el espacio está listo.' },
{ h: 'Rode NT1 Signature Series: A Closer Look', hes: 'Rode NT1 Signature Series: análisis detallado', p: [297],
  en: '<strong>Classic NT1 sound without the bundle price.</strong> The same HF6 1-inch capsule and 4 dBA noise floor in a streamlined package with shock mount, pop filter and XLR cable included. Neutral with a gentle 10 kHz lift that puts vocals and acoustic guitars forward without harshness. XLR-only and 48V-powered, it is the condenser most home studios graduate to after outgrowing a starter mic.',
  es: '<strong>El sonido NT1 clásico sin precio de bundle.</strong> La misma cápsula HF6 de 1 pulgada y 4 dBA de ruido en un paquete esencial con suspensión, antipop y cable XLR incluidos. Neutro con un leve realce sobre 10 kHz que adelanta voces y acústicas sin dureza. Solo XLR con phantom de 48V: el condensador al que llegan la mayoría de home studios tras superar el micro inicial.' },
{ h: 'Shure MV7+: A Closer Look', hes: 'Shure MV7+: análisis detallado', p: [194],
  en: '<strong>SM7B character with training wheels.</strong> A hybrid dynamic with USB-C and XLR outputs, built-in headphone monitoring, touch panel metering and auto-level DSP that keeps voice consistent on stream. Less demanding than the SM7B on preamp gain, with the XLR path ready when the setup grows. The streamer-proof bridge between USB convenience and pro XLR.',
  es: '<strong>Carácter SM7B con ruedines.</strong> Dinámico híbrido con salidas USB-C y XLR, monitoreo por auriculares integrado, medidores táctiles y DSP de nivel automático que mantiene la voz consistente en directo. Menos exigente que el SM7B con la ganancia del previo, con la vía XLR lista cuando el montaje crece. El puente a prueba de streamers entre la comodidad USB y el XLR profesional.' },
{ h: 'Rode PodMic USB: A Closer Look', hes: 'Rode PodMic USB: análisis detallado', p: [252],
  en: '<strong>The PodMic that plugs straight into the laptop.</strong> The classic broadcast dynamic voice plus USB-C with Revolution preamp and APHEX DSP, zero-latency headphone monitoring and 32-bit float recording that rescues clipped takes in post. Heavier than it looks at nearly 900 grams, so budget a real boom arm. Ideal for solo podcasters recording to computer with no interface on the desk.',
  es: '<strong>El PodMic que se enchufa directo al portátil.</strong> La voz broadcast del clásico más USB-C con previo Revolution y DSP APHEX, monitoreo sin latencia y grabación en flotante de 32 bits que rescata tomas saturadas en postproducción. Más pesado de lo que parece con casi 900 gramos, así que reserva un brazo articulado de verdad. Ideal para podcasters en solitario que graban al ordenador sin interfaz en la mesa.' }
];
const insertAt = 2;
SECS.forEach((s, k) => {
  g.sections.splice(insertAt + k, 0, { heading: s.h, heading_es: s.hes, content: s.en, content_es: s.es, products: s.p });
});
console.log('sections now: ' + g.sections.map(s => s.heading).join(' | '));
fs.writeFileSync(F, JSON.stringify(G, null, 2));