const fs = require('fs');
const DIR = 'C:/Users/Daniel/projects/topmusiciangear/';
const guides = JSON.parse(fs.readFileSync(DIR + 'data/guides.json', 'utf8'));
const d = guides.find(x => x.id === 'guitar-bass-amps');
const s = d.sections.find(x => x.heading === 'Bass Amps: What You Actually Need');
s.content = '<p><strong>Bass amplification is about moving air: a guitar amp distorts and can damage itself on low frequencies, so bass needs dedicated speakers and headroom.</strong> The combos in this guide solve it the modern way — lightweight Class-D power, XLR direct out for the house, effects loop, aux in and headphone out for silent practice.</p><p><strong>Speaker size matters for 5-string players.</strong> Dual 10-inch speakers (on the Rumble 500 and Markbass CMD 102P IV) favor punch but can struggle with the low B string at stage volume, sounding compressed or muddy. For serious 5-string work, a 15-inch speaker moves the necessary air — the Ampeg Rocket Bass RB-115 (1×15", 200W with ext. cab / 100W standalone) handles the low B with authority.</p><p><strong>The choice is character.</strong> The Ampeg Rocket Bass RB-115 brings the SVT-family grind with Super Grit Technology overdrive on demand (200W with ext. cab, 100W standalone); the Fender Rumble 500 V3 brings clean, punchy modern tone with built-in overdrive for edge (500W with ext. cab, 350W standalone). For featherweight pro fidelity, the Markbass CMD 102P IV adds hi-fi thump at 37.7 lb (300W standalone, 500W with extension). Any covers rehearsal, stage and recording without a separate rig.</p>';
s.content_es = '<p><strong>Amplificar bajo es mover aire: un ampli de guitarra distorsiona y puede dañarse con graves, así que el bajo pide altavoces dedicados y margen dinámico.</strong> Los combos de esta guía lo resuelven a la moderna — potencia Clase-D ligera, salida directa XLR a mesa, loop de efectos, entrada aux y salida de auriculares para practicar en silencio.</p><p><strong>El tamaño del altavoz importa para 5 cuerdas.</strong> Los dobles altavoces de 10" (en el Rumble 500 y el Markbass CMD 102P IV) favorecen la pegada pero pueden fallar con el Si grave a volumen de escenario, sonando comprimido o ahogado. Para 5 cuerdas en serio, un altavoz de 15 pulgadas mueve el aire necesario — el Ampeg Rocket Bass RB-115 (1×15", 200W con cab. de extensión / 100W solo) maneja el Si grave con autoridad.</p><p><strong>La elección es carácter.</strong> El Ampeg Rocket Bass RB-115 trae el grind familia SVT con overdrive Super Grit Technology a demanda (200W con cab. de extensión, 100W solo); el Fender Rumble 500 V3 trae tono moderno limpio y pegado con overdrive integrado (500W con cab. de extensión, 350W solo). Para fidelidad pro pluma, el Markbass CMD 102P IV suma pegada hi-fi en 17,1 kg (300W solo, 500W con extensión). Cualquiera de ellos cubre ensayo, escenario y grabación sin rack aparte.</p>';
fs.writeFileSync(DIR + 'data/guides.json', JSON.stringify(guides, null, 2));
console.log('bass section rewritten');
