const fs = require('fs');
const DIR = 'C:/Users/Daniel/projects/topmusiciangear/';
const G = require(DIR + 'data/guides.json');
// [guide, product, exact EN pro, new EN, new ES]
const F = [
['best-32-channel-digital-mixers','Behringer X32','Battle-tested in churches, studios, and touring rigs worldwide','32-channel USB interface plus AES50 and Ultranet cover recording, stage boxes and personal monitoring','Interfaz USB de 32 canales más AES50 y Ultranet cubren grabación, stage boxes y monitoreo personal'],
['starter-studio','Rode NT1 Signature Series','Great value','Large-diaphragm condenser detail with shock mount and pop filter included','Detalle de condensador de diafragma grande con suspensión y filtro antipop incluidos'],
['best-microphone','Shure SM7B','A proven, long-term investment for voice work','Detachable windscreen plus internal shock mounting for broadcast-ready vocals out of the box','Paravientos desmontable más suspensión interna para voces listas para broadcast desde el primer día'],
['best-monitors','Adam Audio A7V','X-ART ribbon tweeter delivers stunning transient response','X-ART ribbon tweeter resolves fine transient detail with a wide sweet spot','El tweeter de cinta X-ART resuelve transitorios finos con un punto dulce amplio'],
['budget-mics','Shure SM58','The most popular vocal microphone in the world — proven on every stage','Pneumatic shock mount kills handling noise for handheld stage use','La suspensión neumática elimina el ruido de manejo para uso en mano en escenario'],
['usb-mics','TONOR TC-777 USB Microphone','Roughly 34,000 ratings — incredibly well proven','Cardioid pickup rejects keyboard clatter behind the mic','La captación cardioide rechaza el tecleo detrás del micro'],
['budget-usb-mics','TONOR TC-777 USB Microphone','Roughly 34,000 ratings — incredibly well proven','Cardioid pickup rejects keyboard clatter behind the mic','La captación cardioide rechaza el tecleo detrás del micro'],
['stage-mics','Shure Beta 58A','Pneumatic shock mount kills handling thumps; trusted by McCartney, Chris Martin, and Trent Reznor','Pneumatic shock mount kills handling thumps for active singers','La suspensión neumática elimina golpes para cantantes activos'],
['open-headphones','Audeze LCD-X','Reference tuning trusted by top mixers','Planar magnetic drivers with deep sub-bass extension and low distortion','Drivers magnéticos planares con extensión grave profunda y baja distorsión'],
['pro-headphones','Audeze LCD-X','Proven gold standard trusted by Grammy-winning engineers worldwide','Planar magnetic drivers with deep sub-bass extension and low distortion','Drivers magnéticos planares con extensión grave profunda y baja distorsión'],
['studio-furniture','K&M Monitor Stands (Pair)','German-engineered steel built for decades of studio life','German steel construction with replaceable parts that outlasts the monitors','Construcción alemana de acero con repuestos que duran más que los monitores'],
['stage-wireless','Shure BLX24R/SM58 Wireless','Same cardioid pickup pattern that made the SM58 a stage standard for decades','SM58 capsule sound without the cable','Sonido de cápsula SM58 sin cable'],
['stage-wireless','Shure BLX24R/SM58 Wireless','Familiar and trusted by sound engineers worldwide','QuickScan frequency setup finds clean channels in seconds','El ajuste QuickScan encuentra canales limpios en segundos'],
['daw-guide','Avid Pro Tools Studio','The standard in professional studios worldwide','Session format opens natively in almost any commercial studio','El formato de sesión abre nativo en casi cualquier estudio comercial'],
['pro-tools-vs-cubase','Avid Pro Tools Studio','Industry-standard for professional studios worldwide session compatibility with major facilities','Session format opens natively in almost any commercial studio','El formato de sesión abre nativo en casi cualquier estudio comercial'],
['pro-daw','Avid Pro Tools Studio','The DAW most commercial studios worldwide run on','Session format opens natively in almost any commercial studio','El formato de sesión abre nativo en casi cualquier estudio comercial'],
['budget-interfaces','Audient EVO 4','Smartgain sets input levels automatically — ideal for beginners','Smartgain auto-sets input levels for solo recording','Smartgain ajusta niveles de entrada solo para grabar sin ayuda'],
['beginner-guitar','Yamaha C40 Classical (Nylon) Guitar','Proven reliability and consistent quality make it the classic student pick','Nylon strings with low action that spares beginner fingertips','Cuerdas de nailon con acción baja que cuidan dedos principiantes'],
['best-keyboard','Nord Stage 4 88','The standard in professional touring rigs worldwide','Instant-access knobs plus seamless program transitions for live sets','Mandos de acceso directo más transiciones fluidas para directos'],
['best-keyboard','Roland FP-30X','Great value for the keybed quality and sound it delivers','Graded PHA-4 action with escapement at a mid-range price','Acción graduada PHA-4 con escape a precio de gama media'],
['best-drum-machine','Roland TR-6S','Great value for Roland sound','Battery-powered ACB drums that fit in a backpack','Baterías ACB a pilas que caben en una mochila'],
['best-grooveboxes','Roland TR-6S','Great value for Roland sound','Battery-powered ACB drums that fit in a backpack','Baterías ACB a pilas que caben en una mochila'],
['best-grooveboxes','Novation Circuit Tracks','Great value, fun workflow','Battery-powered standalone groovebox with two synth tracks and four drum tracks','Groovebox autónoma a pilas con dos pistas de sinte y cuatro de batería'],
['best-monitors-for-small-rooms','ADAM Audio D3V','The most affordable way into ADAM ribbon-tweeter sound at ~$350 for the pair','Coaxial USB-powered monitors that fit on crowded desks','Monitores coaxiales alimentados por USB que caben en escritorios llenos'],
['best-beginner-electric-guitar','Squier Affinity Series Stratocaster','Iconic Stratocaster look and feel — the most recorded guitar shape in history','Comfortable contoured body with three single-coils for clean-to-crunch versatility','Cuerpo contorneado cómodo con tres single-coils versátiles de limpio a crunch'],
['best-electric-guitars-2026','Squier Affinity Series Stratocaster',"The classic beginner's Strat — iconic look and feel",'Comfortable contoured body with three single-coils for clean-to-crunch versatility','Cuerpo contorneado cómodo con tres single-coils versátiles de limpio a crunch'],
['best-electric-guitars-2026','Squier Classic Vibe','Vintage-tint gloss neck and','Narrow-tall frets plus vintage-tint gloss neck for a broken-in feel','Trastes narrow-tall más mástil brillante con tinte vintage para tacto rodado'],
['best-bass-amps','Markbass Mini CMD 121P V','The best-selling Markbass amp worldwide with the iconic yellow-on-black design','Single-knob Old School Filter rolls off highs for instant vintage thump','El filtro Old School de una perilla recorta agudos para thump vintage instantáneo'],
['budget-pa-systems','EV ZLX-12P-G2 Powered Speaker','Best-selling professional PA speaker with 8,900+ reviews','1000W Class-D power with DSP presets and Bluetooth control','1000W Clase-D con presets DSP y control Bluetooth'],
['fender-bass-guide','Fender Player II Jazz Bass',' it is the most versatile Fender bass at a fair price','Two single-coils with independent volumes cover fingerstyle, slap and pick','Dos single-coils con volúmenes independientes cubren dedos, slap y púa'],
['budget-bass-like-expensive','Squier Affinity Series Precision Bass PJ',"The world's best-selling bass at an accessible price",'Split-coil P plus Jazz bridge pickup cover vintage thump and modern growl','Pastilla P split-coil más puente Jazz cubren thump vintage y growl moderno'],
['beginner-bass-guitars','Squier Affinity Series Precision Bass PJ',"The world's best-selling bass — proven by thousands of beginners",'Split-coil P plus Jazz bridge pickup cover vintage thump and modern growl','Pastilla P split-coil más puente Jazz cubren thump vintage y growl moderno'],
['beginner-bass-guitars','Fender Player II Jazz Bass',' it is the most versatile Fender bass at a fair price','Two single-coils with independent volumes cover fingerstyle, slap and pick','Dos single-coils con volúmenes independientes cubren dedos, slap y púa'],
['best-bass-under-700','Yamaha TRBX304','Most versatile bass with a 5-way active EQ','5-way active EQ switch with humbucking pickups for slap-ready tones','Selector activo de 5 vías con humbuckers para tonos listos para slap'],
['pro-microphones','Lewitt LCT 1040 Ultimate Microphone System','Five polar patterns selectable via remote control — most versatile in its class','Five polar patterns with tube and solid-state voicings via remote control','Cinco patrones polares con voces de válvulas y estado sólido por control remoto'],
['beat-making','Focusrite Scarlett 2i2 4th Gen',"The world's best-selling audio interface for a reason",'Clean preamps with Air mode and rock-solid USB-C drivers','Previos limpios con modo Air y drivers USB-C sólidos'],
['best-instrument-mics','Shure SM57','The most recorded instrument microphone in history','Handles screaming guitar cabs without distortion or damage','Aguanta pantallas a todo volumen sin distorsión ni daños'],
['best-hardware-samplers','Akai MPC Sample','Best-selling budget sampler','16 iconic velocity-sensitive pads with chop and time-stretch','16 pads icónicos sensibles a la velocidad con chop y time-stretch'],
['best-acoustic-guitars-for-beginners','Fender CD-60S Acoustic',"Proven reliability from the world's most famous guitar brand",'Dreadnought with rolled fingerboard edges for easy chording','Dreadnought con bordes de diapasón redondeados para cejillas fáciles'],
['best-parlor-guitars','Gretsch G9500 Jim Dandy','Authentic 1930s bark at an unbeatable price','Ladder-braced parlor tone for couch picking and recording','Tono parlor con varetaje ladder para tocar en el sofá y grabar'],
['best-ribbon-mics','Coles 4038','Legendary BBC broadcast heritage — decades of proven performance','Figure-8 ribbon with smooth top end for overheads and brass','Cinta en 8 con agudos suaves para overheads y metales'],
['sidechain-modulation-plugins','Cableguys ShaperBox 3','Most versatile rhythmic modulation toolkit available','Volume, filter, pan, width and time modules in one window','Módulos de volumen, filtro, paneo, anchura y tiempo en una ventana'],
['best-bass-amps','Fender Rumble 40 V3','Proven first amp with thousands of positive reviews from gigging bassists','Ported lightweight cabinet that sounds big in rehearsals and small gigs','Caja portada ligera que suena grande en ensayos y conciertos pequeños'],
['best-reverb-delay','Boss DD-8 Digital Delay','Great value for features','Stereo ins/outs with tap tempo and 40-second looper','Entradas/salidas estéreo con tap tempo y looper de 40 segundos'],
['best-reverb-delay','TC Electronic Hall of Fame 2','Great value','TonePrint slots plus Mash expression footswitch','Slots TonePrint más footswitch de expresión Mash'],
['best-bass-amps','Fender Rumble 500 V3','XLR D.I. out for straight-to-FOH; the backline standard at venues worldwide','Footswitchable overdrive plus Bright/Contour/Vintage voicing onboard','Overdrive conmutable por pedal más voicing Bright/Contour/Vintage a bordo'],
['best-overdrive-distortion','Ibanez TS9 Tube Screamer','Industry standard for decades','Mid-hump drive that pushes tube amps into singing sustain','Drive con empuje de medios que lleva amplis de válvulas al sustain cantarín'],
['ts9-vs-bd2','Ibanez TS9 Tube Screamer','Proven classic on countless records','Mid-hump drive that pushes tube amps into singing sustain','Drive con empuje de medios que lleva amplis de válvulas al sustain cantarín'],
['best-digital-pianos','Kawai ES120','Harmonic Imaging XL, beautiful tone','Harmonic Imaging XL with 88-key Responsive Hammer Compact action','Harmonic Imaging XL con 88 teclas de acción Responsive Hammer Compact'],
['best-synthesizers','Sequential Take 5','44-key Fatar semi-weighted keybed that plays beautifully','44-key Fatar semi-weighted keybed with vintage knob-per-function panel','Teclado Fatar de 44 teclas semipesadas con panel vintage de un mando por función'],
['xr18-vs-cq18t','Behringer X Air XR18','Proven reliability since 2013 — over a decade of field use on real stages','16 MIDAS preamps with 18x18 USB interface in a stage-box footprint','16 previos MIDAS con interfaz USB 18x18 en formato stage box'],
['scarlett-vs-motu','Focusrite Scarlett 2i2 4th Gen','Decade-long record of dependable, stable drivers with universal compatibility across Windows, Mac, and iPad','Class-compliant USB-C that works on Windows, Mac and iPad without drivers','USB-C class-compliant que funciona en Windows, Mac e iPad sin drivers'],
['active-vs-passive-pa','EV ZLX-12P-G2 Powered Speaker','Proven reliability backed by a 3-year warranty','1000W Class-D with 127 dB peak for small venues without a sub','1000W Clase-D con 127 dB de pico para locales pequeños sin sub'],
['active-vs-passive-pa','JBL JRX215','250W continuous / 1000W peak at 8Ω — proven, road-tested passive mainstay','Dual 15-inch woofers move serious air for DJ and live use without power','Dobles woofers de 15 pulgadas mueven aire de sobra para DJ y directo sin corriente'],
['best-bass-under-700','Sire Marcus Miller V5R','Vintage appointments — open-gear tuners, vintage bridge, block inlays — deliver classic looks','Roasted maple neck with rolled edges for broken-in comfort','Mástil de arce tostado con bordes redondeados para tacto rodado'],
['pro-headphones','Audeze LCD-X','Proven gold standard trusted by Grammy-winning engineers worldwide','Planar magnetic drivers with deep sub-bass extension and low distortion','Drivers magnéticos planares con extensión grave profunda y baja distorsión'],
['pro-monitors','Focal Trio11 Be','Pure beryllium inverted dome tweeter delivers stunning top-end detail and air','Pure beryllium inverted-dome tweeter with exceptional top-end air and detail','Tweeter de berilio puro de cúpula invertida con aire y detalle excepcionales en agudos'],
['pro-plugins','FabFilter Total Bundle','Pro-Q 4 is the most used EQ on professional mixes worldwide','Dynamic EQ bands with per-band mid/side and external sidechain','Bandas de EQ dinámica con mid/side por banda y sidechain externo'],
['pro-live-sound','Behringer X32 Compact','Proven ecosystem with years of reliability and community support','AES50 ports plus Ultranet cover stage boxes and personal monitoring','Puertos AES50 más Ultranet cubren stage boxes y monitoreo personal'],
['pro-mixers','Midas M32R LIVE','Industry-standard workflow trusted by touring engineers','Midas PRO preamps with 192 kHz converters and 1-million-cycle faders','Previos Midas PRO con conversores a 192 kHz y faders de un millón de ciclos'],
['beat-making','Beyerdynamic DT 770 Pro','Studio-standard reliability — the same 250-Ohm model has sat on studio headphone stands for decades','250-ohm drivers with velour pads comfortable for full tracking days','Drivers de 250 ohmios con almohadillas de terciopelo cómodos en jornadas completas'],
['best-multi-effects-pedals','Moore GE300','Great value for features','Amp modeling plus synth engine and Tone Capture for direct recording','Modelado de amplis más motor de sinte y Tone Capture para grabar directo'],
['stream-controllers','Rode Streamer X','Great value for streamers','4K30 capture with 4K60 passthrough plus XLR mic input in one box','Captura 4K30 con paso 4K60 más entrada de micro XLR en una caja'],
['mics-for-creators','Blue Yeti USB Microphone','Most reviewed USB mic ever — proven by millions','Four pickup patterns (cardioid, stereo, omni, bidirectional) cover podcasting and music','Cuatro patrones (cardioide, estéreo, omni, bidireccional) cubren pódcast y música'],
['best-hardware-samplers','Roland SP-404MKII','4.8/5 across 75,000+ reviews — the most proven','32-voice polyphony with skip-back sampling that never loses an idea','Polifonía de 32 voces con muestreo retrospectivo que nunca pierde una idea'],
['budget-usb-mics','HyperX SoloCast 2','Proven reliability with thousands of reviews','Tap-to-mute with LED indicator for hassle-free streaming','Silencio táctil con LED para streaming sin líos'],
['best-beginner-electric-guitar','Squier Affinity Series Stratocaster','Iconic Stratocaster look and feel — the most recorded guitar shape in history','Comfortable contoured body with three single-coils for clean-to-crunch versatility','Cuerpo contorneado cómodo con tres single-coils versátiles de limpio a crunch'],
['best-acoustic-guitars-for-beginners','Ibanez AW54 Artwood','Great value for players who want to grow','Solid mahogany top that opens up with playing','Tapa maciza de caoba que se abre al tocarla'],
['best-condenser-mics','Rode NT1 Signature Series','Great value','Large-diaphragm condenser detail with shock mount and pop filter included','Detalle de condensador de diafragma grande con suspensión y filtro antipop incluidos']
];
let ok = 0, miss = 0;
for (const [gid, name, en, newEn, newEs] of F) {
  const g = G.find(x => x.id === gid);
  if (!g) { console.log('MISS guide ' + gid); miss++; continue; }
  const v = (g.verdictProsCons || []).find(v => v.name === name);
  if (!v) { console.log('MISS product ' + gid + ' ' + name); miss++; continue; }
  const i = (v.pros || []).findIndex(s => s.includes(en.slice(0, 50)));
  if (i === -1) { console.log('MISS text ' + gid + ' ' + name + ': ' + en.slice(0, 60)); miss++; continue; }
  v.pros[i] = newEn; v.pros_es[i] = newEs; ok++;
}
fs.writeFileSync(DIR + 'data/guides.json', JSON.stringify(G, null, 2));
console.log('DONE ok=' + ok + ' miss=' + miss);