const fs = require('fs');
const g = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));
const guide = g.find(x => x.id === 'best-drum-machine');
const snip = guide.featuredSnippet;

const map = {
  'faq_q1': "¿Qué caja de ritmos debería comprar un principiante absoluto?",
  'faq_a1': "La Roland T-8 si manejas un presupuesto ajustado, o la Novation Circuit Tracks si buscas una groovebox completa y real. La T-8 te ofrece los sonidos genuinos de las cajas 808/909/606 junto a una línea de bajo TB-303 con batería integrada. Por su parte, la Circuit Tracks suma la gestión de sintetizadores, muestras y pistas MIDI en un entorno sin pantallas que resulta sumamente intuitivo. Ambos dispositivos te permitirán estructurar canciones sin tocar el ordenador desde el primer día.",
  'faq_q1_es': "¿Qué caja de ritmos debería comprar un principiante absoluto?",
  'faq_a1_es': "La Roland T-8 si manejas un presupuesto ajustado, o la Novation Circuit Tracks si buscas una groovebox completa y real. La T-8 te ofrece los sonidos genuinos de las cajas 808/909/606 junto a una línea de bajo TB-303 con batería integrada. Por su parte, la Circuit Tracks suma la gestión de sintetizadores, muestras y pistas MIDI en un entorno sin pantallas que resulta sumamente intuitivo. Ambos dispositivos te permitirán estructurar canciones sin tocar el ordenador desde el primer día.",
  'faq_q2': "¿Es la MPC One G2 mejor que utilizar un ordenador y un DAW para hacer beats?",
  'faq_a2': "Para disfrutar de un flujo de trabajo puramente táctil y libre de las distracciones de internet, sí. La Akai MPC One G2 funciona de manera 100% autónoma, permitiéndote samplear, secuenciar y finalizar producciones completas directamente desde sus pads. Cuenta con soporte para 32 instancias de plugins, separación de Stems y más de 100 efectos de fábrica. Un DAW en ordenador te dará más pantallas y potencia bruta de procesado, pero la MPC te encierra en un entorno clásico de Hip-Hop que resulta mucho más rápido e inspirador para muchos beatmakers.",
  'faq_q2_es': "¿Es la MPC One G2 mejor que utilizar un ordenador y un DAW para hacer beats?",
  'faq_a2_es': "Para disfrutar de un flujo de trabajo puramente táctil y libre de las distracciones de internet, sí. La Akai MPC One G2 funciona de manera 100% autónoma, permitiéndote samplear, secuenciar y finalizar producciones completas directamente desde sus pads. Cuenta con soporte para 32 instancias de plugins, separación de Stems y más de 100 efectos de fábrica. Un DAW en ordenador te dará más pantallas y potencia bruta de procesado, pero la MPC te encierra en un entorno clásico de Hip-Hop que resulta mucho más rápido e inspirador para muchos beatmakers.",
  'faq_q3': "¿Necesito una caja de ritmos si ya tengo un DAW en mi estudio?",
  'faq_a3': "No es obligatorio, pero transforma radicalmente tu forma de producir. Hardware como la Roland TR-8S, el Digitakt II o el Syntakt eliminan el ratón de tu bucle creativo, obligándote a improvisar, esculpir el sonido y estructurar arreglos utilizando únicamente las manos y el oído. Dispositivos compactos como la T-8 o la Circuit Tracks son perfectos para plasmar ideas sobre la marcha, mientras que estaciones como la MPC One G2 o la imponente Pērkons HD-01 actúan como centros de producción definitivos.",
  'faq_q3_es': "¿Necesito una caja de ritmos si ya tengo un DAW en mi estudio?",
  'faq_a3_es': "No es obligatorio, pero transforma radicalmente tu forma de producir. Hardware como la Roland TR-8S, el Digitakt II o el Syntakt eliminan el ratón de tu bucle creativo, obligándote a improvisar, esculpir el sonido y estructurar arreglos utilizando únicamente las manos y el oído. Dispositivos compactos como la T-8 o la Circuit Tracks son perfectos para plasmar ideas sobre la marcha, mientras que estaciones como la MPC One G2 o la imponente Pērkons HD-01 actúan como centros de producción definitivos.",
  'faq_q4': "Digitakt II o Syntakt: ¿Qué máquina de Elektron debería elegir?",
  'faq_a4': "La regla de oro es sencilla: Digitakt II para samplear, Syntakt para sintetizar. El Digitakt II te ofrece 16 pistas estéreo nativas, 400 MB de memoria de trabajo por proyecto y algoritmos avanzados para trocear y modular audio externo a lo largo de un potente secuenciador de 128 pasos. El Syntakt, en cambio, es un sintetizador multitimbral que cuenta con 12 pistas híbridas (analógicas y digitales) alimentadas por 37 motores de síntesis virtuales. Ambos comparten los revolucionarios parameter locks y el modo canción de la marca.",
  'faq_q4_es': "Digitakt II o Syntakt: ¿Qué máquina de Elektron debería elegir?",
  'faq_a4_es': "La regla de oro es sencilla: Digitakt II para samplear, Syntakt para sintetizar. El Digitakt II te ofrece 16 pistas estéreo nativas, 400 MB de memoria de trabajo por proyecto y algoritmos avanzados para trocear y modular audio externo a lo largo de un potente secuenciador de 128 pasos. El Syntakt, en cambio, es un sintetizador multitimbral que cuenta con 12 pistas híbridas (analógicas y digitales) alimentadas por 37 motores de síntesis virtuales. Ambos comparten los revolucionarios parameter locks y el modo canción de la marca.",
  'faq_q5': "¿Qué caja es la mejor opción para producir y tocar Techno: TR-8S, Syntakt o Pērkons?",
  'faq_a5': "Depende de tu rol en el escenario: elige la Roland TR-8S si buscas el control absoluto en directo mediante faders físicos por canal y transiciones de escenas fluidas; opta por el Elektron Syntakt si quieres diseñar parches híbridos complejos y texturas rítmicas en una sola caja compacta; o lánzate a por la Erica Synths Pērkons HD-01 si buscas un instrumento de Techno industrial premium con un control absoluto de un mando por función. Las tres son herramientas profesionales excelentes; tu presupuesto decidirá entre un caballo de batalla todoterreno o un grial aspiracional de estudio.",
  'faq_q5_es': "¿Qué caja es la mejor opción para producir y tocar Techno: TR-8S, Syntakt o Pērkons?",
  'faq_a5_es': "Depende de tu rol en el escenario: elige la Roland TR-8S si buscas el control absoluto en directo mediante faders físicos por canal y transiciones de escenas fluidas; opta por el Elektron Syntakt si quieres diseñar parches híbridos complejos y texturas rítmicas en una sola caja compacta; o lánzate a por la Erica Synths Pērkons HD-01 si buscas un instrumento de Techno industrial premium con un control absoluto de un mando por función. Las tres son herramientas profesionales excelentes; tu presupuesto decidirá entre un caballo de batalla todoterreno o un grial aspiracional de estudio."
};

Object.keys(map).forEach(k => { snip[k] = map[k]; });

guide.conclusion = "Ocho máquinas excelentes divididas en tres misiones muy claras: viajar ligero, dominar el directo en el escenario o gobernar las sesiones de tu estudio. La Roland T-8 y la Novation Circuit Tracks demuestran que un presupuesto ajustado es más que suficiente para acceder a un ritmo real y profesional. En el peldaño intermedio, la DrumBrute Impact, la TR-8S y la MPC One G2 representan las herramientas definitivas de trabajo: actitud analógica pura, faders físicos para el directo y el cerebro por excelencia de la producción urbana. Por último, el Digitakt II, el Syntakt y la Pērkons HD-01 abren las puertas al diseño de sonido más profundo a través de laboratorios de sampling estéreo masivos, síntesis híbrida avanzada y paneles de control colosales sin menús digitales. Elige cuál es tu formato ideal, fija tu objetivo y empieza a crear tus ritmos de forma autónoma fuera del ordenador.";

guide.conclusion_es = "Ocho máquinas excelentes divididas en tres misiones muy claras: viajar ligero, dominar el directo en el escenario o gobernar las sesiones de tu estudio. La Roland T-8 y la Novation Circuit Tracks demuestran que un presupuesto ajustado es más que suficiente para acceder a un ritmo real y profesional. En el peldaño intermedio, la DrumBrute Impact, la TR-8S y la MPC One G2 representan las herramientas definitivas de trabajo: actitud analógica pura, faders físicos para el directo y el cerebro por excelencia de la producción urbana. Por último, el Digitakt II, el Syntakt y la Pērkons HD-01 abren las puertas al diseño de sonido más profundo a través de laboratorios de sampling estéreo masivos, síntesis híbrida avanzada y paneles de control colosales sin menús digitales. Elige cuál es tu formato ideal, fija tu objetivo y empieza a crear tus ritmos de forma autónoma fuera del ordenador.";

fs.writeFileSync('data/guides.json', JSON.stringify(g, null, 2) + '\n');
console.log('Done.');
