const fs = require('fs');
const g = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));
const guide = g.find(x => x.id === 'best-samplers-drum-computers');
const snip = guide.featuredSnippet;

const map = {
  'faq_a1_en': "Yes, the Elektron Digitakt II is an exceptional sampler for that purpose. Its digital 16-track stereo engine combined with interchangeable filters and a digital saturation/overdrive circuit per track offers a level of surgical control over audio that is very hard to beat in hardware format.",
  'faq_a2_en': "For those seeking a purely tactile workflow, yes. The Akai MPC One G2 works 100% standalone; it has Wi-Fi and Bluetooth connectivity for downloading content wirelessly, letting you structure complete songs without touching a mouse. A computer with a DAW will always offer more raw power and third-party plugins, but the MPC gets you out of the screen and into a dedicated environment that favors creative concentration.",
  'faq_a3_en': "Because the MPC Key 37 Gen 2 unifies Akai's standalone engine with 37 full-size aftertouch keys. This lets you compose complex harmonic progressions and program drums in the same box, plus massive connectivity including CV/Gate outputs to control modular synthesizers. Desktop versions are more compact, but if you have a keyboard or piano background, you will finish your songs much faster here.",
  'faq_a5_en': "Yes, that is its main reason for being. The MPC One G2 is a standalone music production station that includes its own touchscreen, 16 backlit pads, 64 GB of internal storage, and built-in virtual instruments. You can sample, sequence, mix, and master a track from start to finish independently. If you wish, you can also connect it to your PC to use it as a controller for its desktop software.",
  'faq_a6_en': "It is not strictly necessary, but it completely transforms your workflow and inspiration. Working with machines like the Digitakt II or MPC One G2 forces you to make definitive decisions with your ears instead of getting lost editing visually with the mouse. Many producers combine both worlds: they use standalone hardware for the initial creative spark and sound design, then export tracks to the DAW for mixing and final arrangement.",
  'faq_a1_es': "Sí, el Elektron Digitakt II es un sampler excepcional para ese propósito. Su motor digital de 16 pistas estéreo combinado con filtros intercambiables y un circuito de saturación/overdrive digital por pista ofrece un nivel de control quirúrgico sobre el audio que es muy difícil de superar en formato hardware.",
  'faq_a2_es': "Para quienes buscan un flujo de trabajo puramente táctil, sí. El Akai MPC One G2 funciona de manera 100% independiente; cuenta con conectividad Wi-Fi y Bluetooth para descargar contenido inalámbrico, permitiéndote estructurar canciones completas sin tocar el ratón. Un ordenador con un DAW siempre ofrecerá más potencia bruta y plugins de terceros, pero el MPC te saca de la pantalla y te encierra en un entorno dedicado que favorece la concentración creativa.",
  'faq_a3_es': "Porque el MPC Key 37 Gen 2 unifica el motor autónomo de Akai con 37 teclas de tamaño real con aftertouch. Esto te permite componer progresiones armónicas complejas y programar baterías en la misma caja, sumando además una conectividad masiva que incluye salidas CV/Gate para controlar sintetizadores modulares. Las versiones de escritorio son más compactas, pero si tienes formación de teclista o pianista, terminarás tus canciones mucho más rápido aquí.",
  'faq_a5_es': "Sí, esa es su principal razón de ser. La MPC One G2 es una estación de producción musical autónoma que incluye su propia pantalla táctil, 16 pads retroiluminados, 64 GB de almacenamiento interno e instrumentos virtuales integrados. Puedes samplear, secuenciar, mezclar y masterizar un tema de principio a fin de forma independiente. Si lo deseas, también puedes conectarla al PC para usarla como controlador de su software de escritorio.",
  'faq_a6_es': "No es estrictamente necesario, pero transforma por completo tu flujo de trabajo y tu inspiración. Trabajar con máquinas como el Digitakt II o el MPC One G2 te obliga a tomar decisiones definitivas con el oído en lugar de perderte editando visualmente con el ratón. Muchos productores combinan ambos mundos: utilizan el hardware autónomo para la chispa creativa inicial y el diseño de sonido, y después exportan las pistas al DAW para la mezcla y el arreglo final."
};

Object.keys(map).forEach(k => { snip[k] = map[k]; });

guide.conclusion = "Choose your machine by workflow and habits, not by hype: if you want to make quick sketches anywhere, your place is with the EP-133 K.O. II or the Roland P-6; if live transitions and effects are your thing, your flow will fit Circuit Rhythm or the SP-404MKII; for massive productions and full-song arrangement, you need the Maschine+ ecosystem or the MPC range. The Digitakt II will reward analytical minds who love step sequencing, the Key 37 Gen 2 will give wings to those who think through keys, and the imposing MPC XL will be the definitive centerpiece for studios that want to rule everything from a single hardware throne.";

guide.conclusion_es = "Elige tu máquina por flujo de trabajo y hábitos, no por el ruido mediático (hype): si buscas hacer bocetos rápidos en cualquier lugar, tu sitio está en el EP-133 K.O. II o el Roland P-6; si lo tuyo son las transiciones y los efectos en vivo, tu flujo encajará con el Circuit Rhythm o el SP-404MKII; para producciones masivas y maquetación de temas enteros, necesitas el ecosistema de Maschine+ o la gama MPC. El Digitakt II recompensará a las mentes analíticas que aman el secuenciador por pasos, el Key 37 Gen 2 dará alas a quienes piensen a través de las teclas, y el imponente MPC XL será la pieza central definitiva para los estudios que quieran gobernarlo todo desde un único trono de hardware.";

fs.writeFileSync('data/guides.json', JSON.stringify(g, null, 2) + '\n');
console.log('FAQ + conclusion updated.');
