const fs = require('fs');
const DIR = 'C:/Users/Daniel/projects/topmusiciangear/';
const pairs = [
  ['bolos pequeños de blues y rock', 'presentaciones pequeñas de blues y rock'],
  ['bolos de bajo con tono clásico', 'presentaciones de bajo con tono clásico'],
  ['Bolos pequeños y ensayos económicos', 'Presentaciones pequeñas y ensayos económicos'],
  ['bolos pequeños y monitorización', 'presentaciones pequeñas y monitorización'],
  ['Sistema de columna todo-en-uno para bolos pequeños', 'Sistema de columna todo-en-uno para presentaciones pequeñas'],
  ['bolos potentes y eventos al aire libre', 'presentaciones potentes y eventos al aire libre'],
  ['bolos móviles y actuaciones callejeras', 'presentaciones móviles y actuaciones callejeras'],
  ['La rutina de carga añade logística de bolo', 'La rutina de carga añade logística de presentaciones'],
  ['He mezclado bolos en bares con cajas de preajustes', 'He mezclado presentaciones en bares con cajas de preajustes'],
  ['aguanten bolos semanales', 'aguanten presentaciones semanales'],
  ['la respuesta neutra de Yamaha gana bolos', 'la respuesta neutra de Yamaha consigue presentaciones'],
  ['Distintos bolos, distintas', 'Distintas presentaciones, distintas'],
  ['para shows solistas', 'para actuaciones como solista'],
  ['Toco blues en casa y bolos pequeños', 'Toco blues en casa y presentaciones pequeñas'],
  ['Acabado y rejilla se gastan antes con bolos', 'Acabado y rejilla se gastan antes con las presentaciones'],
  ['los bolos pequeños sin pedalera', 'las presentaciones pequeñas sin pedalera'],
  ['un crunch listo para el bolo', 'un crunch listo para la presentación'],
  ['20W no dan para bolos sin PA', '20W no dan para presentaciones sin PA'],
  ['su lado práctico para bolos, con EQ', 'su lado práctico para presentaciones, con EQ'],
  ['ideal para bolos, ensayos y grabación silenciosa', 'ideal para presentaciones, ensayos y grabación silenciosa'],
  ['casa, ensayo y algún bolo pequeño, esta es', 'casa, ensayo y alguna presentación pequeña, esta es'],
  ['el combo de modelado listo para bolos, el Rumble', 'el combo de modelado listo para presentaciones, el Rumble'],
  ['Compara combos para bolos y ensayo', 'Compara combos para presentaciones y ensayo'],
  ['Combo de modelado para bolos', 'Combo de modelado para presentaciones'],
  ['Tono clásico de casa al bolo', 'Tono clásico de casa a la presentación'],
  ['Volumen de bolo para ensayos', 'Volumen de presentación para ensayos'],
  ['17,3 kg hasta el bolo', '17,3 kg para llevar a la presentación'],
  ['ensayos fuertes e incluso bolos pequeños', 'ensayos fuertes e incluso presentaciones pequeñas'],
  ['que usará en un bolo o una sesión', 'que usará en una presentación o una sesión'],
  ['en casa que en un bolo o una sesión', 'en casa que en una presentación o una sesión'],
  ['que aguanta bolos', 'que aguanta presentaciones'],
  ['enormes en el mismo bolo', 'enormes en la misma presentación'],
  ['captura ensayos o bolos directo al portátil', 'captura ensayos o presentaciones directo al portátil'],
  ['Ideal para bolos pequeños y pódcast', 'Ideal para presentaciones pequeñas y pódcast'],
  ['He salido de un bolo con la multipista', 'He salido de una presentación con la multipista'],
  ['funcione para bolos, ensayos y grabación', 'funcione para presentaciones, ensayos y grabación'],
  ['He mezclado bolos en bares desde el fondo', 'He mezclado presentaciones en bares desde el fondo'],
  ['como la captura del bolo', 'como la captura de la presentación'],
  ['Si mezclas y grabas los mismos bolos', 'Si mezclas y grabas las mismas presentaciones'],
  ['Mezcla USB compacta para streaming/bolos pequeños', 'Mezcla USB compacta para streaming/presentaciones pequeñas'],
  ['Chasis metal aguanta fundas de bolo', 'Chasis metal aguanta fundas para presentaciones'],
  ['permite grabar cada bolo para prueba', 'permite grabar cada presentación para prueba'],
  ['He mezclado bolos de fin de semana con el XR18', 'He mezclado presentaciones de fin de semana con el XR18'],
  ['para repasar el bolo', 'para repasar la presentación'],
  ['Mismo bolo, distintas', 'Misma presentación, distintas'],
  ['para ensayos y bolos pequeños que no se rompa', 'para ensayos y presentaciones pequeñas que no se rompa'],
  ['Bolos pequeños para bandas activas', 'Presentaciones pequeñas para bandas activas'],
  ['PA portátil para bolos pequeños', 'PA portátil para presentaciones pequeñas'],
  ['bolos de rock y Motown', 'presentaciones de rock y Motown'],
  ['Práctica y bolos P/J para empezar', 'Práctica y presentaciones P/J para empezar'],
  ['El acabado fino se gasta antes con bolos', 'El acabado fino se gasta antes con las presentaciones'],
  ['si la pila muere a mitad del bolo', 'si la pila muere a mitad de la presentación'],
  ['Bajo activo versátil para bolos', 'Bajo activo versátil para presentaciones'],
  ['peso en bolos largos', 'peso en presentaciones largas'],
  ['He tocado bolos largos de bodas', 'He tocado presentaciones largas de bodas'],
  ['sobrevivir a bolos nocturnos', 'sobrevivir a presentaciones nocturnas'],
  ['para bolos de fin de semana y encajó', 'para presentaciones de fin de semana y encajó'],
  ['Perfecto para músicos de sesión, bolos versátiles y versiones', 'Perfecto para músicos de sesión, presentaciones versátiles y versiones'],
  ['facilitan los bolos largos', 'facilitan las presentaciones largas'],
  ['mantiene la entonación bolo tras bolo', 'mantiene la entonación presentación tras presentación'],
  ['P/J contundente para bolos', 'P/J contundente para presentaciones'],
  ['¿Cuál es más cómoda para un bolo de tres horas?', '¿Cuál es más cómoda para una presentación de tres horas?'],
  ['He tocado bolos con bajos estilo P', 'He tocado presentaciones con bajos estilo P'],
  ['cuando los bolos pidan el si grave', 'cuando las presentaciones pidan el Si grave'],
  ['¿La CQ puede grabar el bolo?', '¿La CQ puede grabar la presentación?'],
  ['retransmitir mis bolos', 'retransmitir mis presentaciones'],
  ['Sonidos compactos para bolos', 'Sonidos compactos para presentaciones'],
  ['clubes y bolos al aire libre de tamaño medio', 'clubes y presentaciones al aire libre de tamaño medio'],
  ['potencia de sobra para bolos reales', 'potencia de sobra para presentaciones reales'],
  ['potente para bolos reales', 'potente para presentaciones reales'],
  ['pero para un bolo de PA de verdad', 'pero para una presentación con PA de verdad'],
  ['bares y bolos pequeños al aire libre', 'bares y presentaciones pequeñas al aire libre'],
  ['clubs y bolos al aire libre pequeños', 'clubs y presentaciones pequeñas al aire libre'],
  ['no compiten por el mismo bolo', 'no compiten por la misma presentación'],
  ['si tus bolos son ruidosos', 'si tus presentaciones son ruidosas'],
  ['Para bolos en clubes y bares', 'Para presentaciones en clubes y bares'],
  ['La mayoría de bandas, clubes y bolos al aire libre', 'La mayoría de bandas, clubes y presentaciones al aire libre'],
  ['cubren la gama más amplia de bolos', 'cubren la gama más amplia de presentaciones'],
  ['cumpla en el bolo', 'cumpla en la presentación'],
  ['Petaca metal aguanta fundas bolo', 'Petaca metal aguanta fundas para presentaciones'],
  ['cuando el bolo no puede parar', 'cuando la presentación no puede parar'],
  ['no lleva pastilla para bolos ni grabar', 'no lleva pastilla para presentaciones ni grabar'],
  ['Sin pastilla en el modelo base para bolos o grabación directa', 'Sin pastilla en el modelo base para presentaciones o grabación directa'],
  ['El cuerpo de tilo mantiene amables los bolos largos', 'El cuerpo de tilo hace más llevaderas las presentaciones largas'],
  ['encaja con bajistas de bolo y presupuesto', 'encaja con bajistas que tocan en presentaciones con presupuesto ajustado'],
  ['El rey de la versatilidad para bolos', 'El rey de la versatilidad para presentaciones'],
  ['Si tocas bodas, versiones y bolos de iglesia', 'Si tocas bodas, haces versiones y tocas en iglesias'],
  ['la fatiga cae notablemente en bolos largos', 'la fatiga cae notablemente en presentaciones largas'],
  ['mantiene ligeros los bolos largos', 'mantiene ligeras las presentaciones largas'],
  ['Ajusta la gama a tus bolos, no a tus sueños', 'Ajusta la gama a tus presentaciones, no a tus sueños'],
  ['los músicos de bolo aprovechan la EQ activa', 'quienes tocan en presentaciones aprovechan la EQ activa'],
  ['Pegada funk para bolos', 'Pegada funk para presentaciones'],
  ['Cinco cuerdas activo y versátil para bolos', 'Cinco cuerdas activo y versátil para presentaciones'],
  ['Mástil brillo se pega en bolos húmedos', 'Mástil brillo se pega en presentaciones con humedad'],
  ['Voz metalera menos versátil para bolos vintage', 'Voz metalera menos versátil para presentaciones vintage'],
  ['solo la caja equivocada para el bolo equivocado', 'solo la caja equivocada para la presentación equivocada'],
  ['para casa, ensayos y bolos pequeños.', 'para casa, ensayos y presentaciones pequeñas.']
];
for (const f of [DIR + 'data/guides.json', DIR + 'data/products.json']) {
  let t = fs.readFileSync(f, 'utf8');
  let c = 0;
  const ordered = [...pairs].sort((a, b) => b[0].length - a[0].length);
  for (const [oldS, newS] of ordered) {
    if (t.includes(oldS)) { t = t.split(oldS).join(newS); c++; }
  }
  fs.writeFileSync(f, t);
  console.log(f.split('/').pop() + ': ' + c + ' rules applied');
}
for (const f of [DIR + 'data/guides.json', DIR + 'data/products.json']) {
  const t = fs.readFileSync(f, 'utf8');
  const m = t.match(/\b[Bb]olos?\b/g);
  console.log(f.split('/').pop() + ' remaining: ' + (m ? m.length : 0));
  if (m) console.log([...new Set(m)].join(','));
}