// best-5-string-basses PART 2: sections + conclusion + faq + snippet.
const fs = require('fs');
const G = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));
const g = G.find(x => x.id === 'best-5-string-basses');
const S = (heading, heading_es, content, content_es, products) => ({ heading, heading_es, content, content_es, products });
const F = (q, a, q_es, a_es) => ({ q, a, q_es, a_es });

g.sections.push(
  S('Why Five Strings, and Why Price Tiers Decide Everything', 'Por qué cinco cuerdas, y por qué el precio lo decide todo',
    '<p><strong>A low B only works if the whole bass supports it: scale length, bridge coupling, nut width and preamp headroom.</strong> Cheap five-strings fail exactly there — floppy B, muddy definition. This guide splits twelve verified basses into three honest tiers so you pay for support, not logos.</p><p><strong>Budget (under $500)</strong> proves the concept: Yamaha build quality, StingRay thump and Fender voice with compromises you can hear around the edges. <strong>Mid-range ($500–$1,100)</strong> is where working bassists live — pro components, stable tuning, session-ready tone. <strong>Premium (over $1,300)</strong> buys definitive B-strings: multiscale geometry, neodymium magnets and 18-volt headroom.</p>',
    '<p><strong>Un Si grave solo funciona si todo el bajo lo sostiene: escala, acople del puente, cejuela ancha y headroom del previo.</strong> Los cinco cuerdas baratos fallan justo ahí — Si flojo, definición embarrada. Esta guía divide doce bajos verificados en tres gamas honestas para pagar soporte, no logos.</p><p><strong>Económicos (menos de $500)</strong> prueban el concepto: calidad Yamaha, thump StingRay y voz Fender con concesiones audibles en los bordes. <strong>Medios ($500–$1.100)</strong> es donde viven los bajistas trabajadores — componentes pro, afinación estable, tono listo para sesión. <strong>Premium (más de $1.300)</strong> compra Si graves definitivos: geometría multiescala, imanes de neodimio y headroom de 18 voltios.</p>',
    []),
  S('Ibanez GSR205B: The Cheapest Honest Five', 'Ibanez GSR205B: El cinco cuerdas honesto más barato',
    '<strong>Thirty-four inches, dual Dynamix H humbuckers and a Phat II bass boost for $299.99 street.</strong> The okoume body and thin GSR5 maple neck keep it fast, the B15 bridge holds 16.5 mm spacing, and 22 medium frets cover real repertoire. Engage the boost and the low B gains genuine weight — the entry ticket done right.',
    '<strong>Treinta y cuatro pulgadas, dobles humbuckers Dynamix H y boost Phat II por $299,99 de calle.</strong> El cuerpo de okoume y el fino mástil GSR5 de arce lo mantienen rápido, el puente B15 sujeta spacing 16,5 mm y 22 trastes medium cubren repertorio real. Activa el boost y el Si grave gana peso genuino — la entrada hecha bien.', [538]),
  S('Sterling SUB Ray5: StingRay Thump Near $450', 'Sterling SUB Ray5: Thump StingRay cerca de $450',
    '<strong>One ceramic humbucker plus 9V two-band preamp equals instant funk-rock authority.</strong> Jabon body keeps weight down, hard maple neck and board with 12-inch radius and 21 medium frets play fast, 45 mm nut fits five comfortably. Note the real street price hovers near $460 (£449 at Andertons) — the old ~$350 is gone.',
    '<strong>Un humbucker cerámico más previo 9V de dos bandas igualan autoridad funk-rock instantánea.</strong> El cuerpo de jabón baja el peso, el mástil y diapasón de arce duro con radio 12" y 21 trastes medium tocan rápido, la cejuela 45 mm acomoda cinco con comodidad. Ojo: el precio real ronda ~$460 (£449 en Andertons) — los viejos ~$350 se fueron.', [539]),
  S('Yamaha TRBX305: The Versatility King Under $500', 'Yamaha TRBX305: El rey de la versatilidad bajo $500',
    '<strong>Dual M3 ceramics with a 5-way Performance EQ switch: slap, pick and fingers without touching an amp.</strong> Solid mahogany body, five-piece maple-mahogany neck, 24 medium frets on rosewood. Street sits near $500 (£416 at G4M, £429 at Andertons) — up from the old ~$400, still the smart budget stretch.',
    '<strong>Dobles cerámicas M3 con switch Performance EQ de 5 posiciones: slap, púa y dedos sin tocar un ampli.</strong> Cuerpo sólido de caoba, mástil cinco piezas arce-caoba, 24 trastes medium en palisandro. La calle ronda ~$500 (£416 en G4M, £429 en Andertons) — más que los viejos ~$400, aún el estirón económico inteligente.', [540]),
  S('Squier Affinity Jazz V: Classic Voice, Passive Honesty', 'Squier Affinity Jazz V: Voz clásica, honestidad pasiva',
    '<strong>Two ceramic J single-coils with honest passive VVT wiring near $400 street.</strong> Poplar body, satin maple C neck, laurel 9.5-inch board with 20 medium-jumbo frets and 47.6 mm bone nut. Check the listing twice: this is the passive model, not the Active with Noiseless pickups and 9V preamp.',
    '<strong>Dos single-coils J cerámicas con cableado VVT pasivo honesto cerca de $400 de calle.</strong> Cuerpo de álamo, mástil C de arce satinado, diapasón laurel 9,5" con 20 trastes medium-jumbo y cejuela hueso 47,6 mm. Revisa el anuncio dos veces: este es el modelo pasivo, no el Active con Noiseless y previo 9V.', [541]),
  S('Sire V7 New Gen: The Buyable V7 With Stainless Frets', 'Sire V7 New Gen: El V7 comprable con trastes inox',
    '<strong>The current V7 you can actually buy: simplified 4-knob active preamp with push-pull active/passive, stainless medium-jumbo frets and Edgeless ebony board.</strong> Alder body, hard maple C neck, bone 46 mm nut, £729 in stock at Andertons. The famous Gen 2 ran 18 volts across two 9V batteries; New Gen streamlines the controls — voltage unstated, tone intact.',
    '<strong>El V7 actual que sí puedes comprar: previo activo simplificado de 4 perillas con push/pull activo/pasivo, trastes inox medium-jumbo y diapasón ébano Edgeless.</strong> Cuerpo de aliso, mástil C de arce duro, cejuela hueso 46 mm, £729 en stock en Andertons. La famosa Gen 2 corría 18 voltios en dos pilas 9V; la New Gen simplifica controles — voltaje no declarado, tono intacto.', [542]),
  S('Yamaha BB435: Passive Tone Done Right', 'Yamaha BB435: Tono pasivo bien hecho',
    '<strong>YGD Custom V5 Alnico PJ pickups with passive VVT through a convertible Vintage Plus bridge.</strong> Solid alder, five-piece maple-mahogany neck with 6-bolt miter joint, 21 medium frets on rosewood. String it through-body for maximum B sustain or top-load for snap. $659.99 street — the passive mid-range reference.',
    '<strong>Pastillas PJ YGD Custom V5 Alnico V con VVT pasiva por puente convertible Vintage Plus.</strong> Aliso sólido, mástil cinco piezas arce-caoba con unión miter 6 tornillos, 21 trastes medium en palisandro. Encuerda a través del cuerpo para máximo sustain del Si o top-load para ataque. $659,99 de calle — la referencia pasiva media.', [543]),
  S('Ibanez SR505E: Featherweight Speed, Read This First', 'Ibanez SR505E: Velocidad pluma, lee esto primero',
    '<strong>Okoume body, five-piece jatoba-walnut neck and Custom 3-band EQ with bypass and mid switch — but the pickups are Bartolini BH2, not Nordstrand.</strong> Nordstrand Big Breaks belong to the SR505N, a different model. Accu-cast B505 bridge at 16.5 mm, 24 medium frets on rosewood. Also note: discontinued in favor of the SR505A, so hunt remaining stock.',
    '<strong>Cuerpo okoume, mástil cinco piezas jatoba-nogal y EQ Custom 3 bandas con bypass y switch de medios — pero las pastillas son Bartolini BH2, no Nordstrand.</strong> Las Nordstrand Big Break son de la SR505N, otro modelo. Puente Accu-cast B505 a 16,5 mm, 24 trastes medium en palisandro. Nota: descontinuado a favor de la SR505A, caza stock restante.', [544]),
  S("Squier Classic Vibe '70s Jazz V: Vintage Looks, Modern Price", "Squier Classic Vibe '70s Jazz V: Estética vintage, precio moderno",
    '<strong>Seventies Jazz Bass down to the black blocks, binding and nickel hardware, with Fender-Designed alnico single-coils.</strong> Fully passive VVT, narrow-tall frets, $479.99 street at zzounds and £439 at G4M. Body wood varies by finish (poplar or soft maple) — tone does not.',
    '<strong>Jazz Bass setentero hasta los bloques negros, binding y níquel, con single-coils alnico diseñadas por Fender.</strong> Totalmente pasivo VVT, trastes narrow tall, $479,99 de calle en zzounds y £439 en G4M. La madera varía por acabado (álamo o arce blando) — el tono no.', [545]),
  S('Fender AmPro II Jazz V: The US Standard', 'Fender AmPro II Jazz V: El estándar USA',
    '<strong>Corona-built flagship with dual V-Mod II pickups, rolled edges, sculpted heel and convertible HiMass Vintage bridge.</strong> Alder (roasted pine on select colors), satin Slim C maple neck, molded hardshell included. Street runs $1,999 and up — budget $2,100 for roasted pine colors, not the old ~$1,900.',
    '<strong>Insignia hecha en Corona con dobles V-Mod II, bordes matados, talón esculpido y puente convertible HiMass Vintage.</strong> Aliso (pino tostado en colores selectos), mástil Slim C satinado, estuche rígido incluido. La calle es $1.999 hacia arriba — calcula $2.100 para colores pino tostado, no los viejos ~$1.900.', [546]),
  S('StingRay Special 5: The Funk Punch Benchmark', 'StingRay Special 5: La referencia del punch funk',
    '<strong>Neodymium humbucker with 18 volts of 3-band headroom — the most aggressive clean punch in bass.</strong> Roasted maple 5-bolt neck, 11-inch board with 22 stainless wide frets, vintage top-loaded bridge, H or HH layouts. $2,799 street verified. One core voice, executed perfectly.',
    '<strong>Humbucker de neodimio con 18 voltios de headroom 3 bandas — el punch limpio más agresivo del bajo.</strong> Mástil arce tostado 5 tornillos, diapasón 11" con 22 trastes inox anchos, puente vintage top-loaded, formatos H o HH. $2.799 de calle verificado. Una voz central, ejecutada perfecta.', [547]),
  S('EHB1005MS: The Clearest Low B Under $1,500', 'EHB1005MS: El Si grave más claro bajo $1.500',
    '<strong>Thirty-three inches on the G, thirty-five on the B: fan geometry that keeps the fifth string piano-tight.</strong> Passive Bartolini BH2 pair with Vari-mid 3-band EQ and bypass, chambered basswood, graphite-reinforced roasted neck with stainless frets, MR5HS bridge at 18 mm, gig bag included. £1,044 at G4M, $1,349.99 street.',
    '<strong>Treinta y tres pulgadas en Sol, treinta y cinco en Si: geometría abanico que mantiene la quinta cuerda tensa como piano.</strong> Par pasivo Bartolini BH2 con EQ Vari-mid 3 bandas y bypass, chambered de tilo, mástil tostado con grafito y trastes inox, puente MR5HS a 18 mm, funda incluida. £1.044 en G4M, $1.349,99 de calle.', [548]),
  S('Dingwall Combustion: The 37-Inch Answer to Djent', 'Dingwall Combustion: La respuesta 37" al djent',
    '<strong>Thirty-four to thirty-seven inches of fan with two or three FD-3N neodymium pickups and EMG 3-band preamp with Quad-tone rotary.</strong> Swamp-ash body averaging 8.75 lb, five-piece maple neck, active/passive switch. Street runs about $2,699 and up (£2,049 preorder at Andertons) — the old ~$2,000 is long gone.',
    '<strong>Treinta y cuatro a treinta y siete pulgadas de abanico con dos o tres pastillas FD-3N neodimio y previo EMG 3 bandas con rotary Quad-tone.</strong> Cuerpo de fresno promedio 8,75 lb, mástil cinco piezas de arce, switch activo/pasivo. La calle ronda ~$2.699 hacia arriba (£2.049 preorder en Andertons) — los viejos ~$2.000 se fueron hace tiempo.', [549]),
  S('Buying Advice: What Actually Holds a Low B Together', 'Guía de compra: qué sostiene de verdad un Si grave',
    '<p><strong>Scale length first.</strong> Thirty-four inches works with the right bridge and setup; fan designs (33–35 in on the EHB1005MS, 34–37 in on the Combustion) tune each string to its ideal tension, which is why multiscale B-strings sound like piano wire. Through-body stringing (BB435, AmPro II) adds a second layer of sustain.</p><p><strong>Headroom second.</strong> Eighteen-volt preamps (StingRay Special, Gen 2 Sire heritage) stay clean where 9-volt circuits clip — that is clean punch, not more volume. Passive basses (BB435, CV 70s, Affinity) skip the issue entirely with zero batteries.</p><p><strong>Fit third.</strong> Nut widths here run 43 to 47.6 mm and spacing 16.5 to 19 mm: narrow and tight for small hands (GSR205B, SR505E), wide and roomy for slap (Affinity, CV 70s, AmPro II). For starting points by budget see <a class="guide-link-btn" href="/guides/beginner-bass-guitars.html">beginner bass guitars</a> and <a class="guide-link-btn" href="/guides/best-bass-under-700.html">best basses under $700</a>.</p>',
    '<p><strong>Primero la escala.</strong> Treinta y cuatro pulgadas funcionan con puente y setup correctos; los diseños abanico (33–35" en el EHB1005MS, 34–37" en el Combustion) afinan cada cuerda a su tensión ideal, por eso sus Si graves suenan a cuerda de piano. El encordado a través del cuerpo (BB435, AmPro II) añade una segunda capa de sustain.</p><p><strong>Segundo el headroom.</strong> Los previos de 18 voltios (StingRay Special, herencia Gen 2 de Sire) se mantienen limpios donde los de 9 recortan — eso es punch limpio, no más volumen. Los pasivos (BB435, CV 70s, Affinity) evitan el tema con cero baterías.</p><p><strong>Tercero el ajuste.</strong> Las cejuelas aquí van de 43 a 47,6 mm y el spacing de 16,5 a 19 mm: estrecho y ajustado para manos pequeñas (GSR205B, SR505E), amplio para slap (Affinity, CV 70s, AmPro II). Para puntos de partida por presupuesto revisa <a class="guide-link-btn" href="/guides/beginner-bass-guitars_es.html">bajos para principiantes</a> y <a class="guide-link-btn" href="/guides/best-bass-under-700_es.html">mejores bajos bajo $700</a>.</p>',
    [])
);

g.conclusion = 'Budget winners: the Yamaha TRBX305 for versatility and the Squier Affinity Jazz V for classic voice near $400. Mid-range winners: the Yamaha BB435 for passive tone and the Sire V7 New Gen for modern active flexibility. Premium winners: the StingRay Special 5 for funk punch, the EHB1005MS for the clearest low B, and the Dingwall Combustion for progressive metal. Match the tier to your gigs, not your dreams.';
g.conclusion_es = 'Ganadores económicos: Yamaha TRBX305 por versatilidad y Squier Affinity Jazz V por voz clásica cerca de $400. Ganadores medios: Yamaha BB435 por tono pasivo y Sire V7 New Gen por flexibilidad activa moderna. Ganadores premium: StingRay Special 5 por punch funk, EHB1005MS por el Si grave más claro y Dingwall Combustion por metal progresivo. Ajusta la gama a tus bolos, no a tus sueños.';
g.verdict = 'Starting on five under $500? GSR205B, Ray5, TRBX305 or Affinity Jazz V. Gigging weekly $500–$1,100? V7 New Gen, BB435, SR505E or Classic Vibe 70s Jazz V. Recording flagship over $1,300? AmPro II Jazz V, StingRay Special 5, EHB1005MS or Dingwall Combustion.';
g.verdict_es = '¿Empezando en cinco por menos de $500? GSR205B, Ray5, TRBX305 o Affinity Jazz V. ¿Tocando semanal $500–$1.100? V7 New Gen, BB435, SR505E o Classic Vibe 70s Jazz V. ¿Insignia de grabación más de $1.300? AmPro II Jazz V, StingRay Special 5, EHB1005MS o Dingwall Combustion.';
g.faq.push(
  { q: 'Is a 5-string bass harder for beginners?', a: 'Slightly: wider necks and a low B to mute. Budget picks like the GSR205B (thin neck, 16.5 mm spacing) and TRBX305 minimize the adjustment. Start on five only if your music needs the low B; otherwise master four first.', q_es: '¿Un bajo de 5 cuerdas es más difícil para principiantes?', a_es: 'Un poco: mástiles anchos y un Si grave que mutear. Opciones como GSR205B (mástil fino, spacing 16,5 mm) y TRBX305 minimizan el ajuste. Empieza en cinco solo si tu música pide el Si grave; si no, domina cuatro primero.' },
  { q: 'How do I stop my low B from sounding floppy?', a: 'Tension comes from scale plus setup: 34-inch basses need proper setup and through-body stringing helps (BB435, AmPro II). Multiscale basses (EHB1005MS 33-35 in, Combustion 34-37 in) tune each string to ideal tension. Higher-voltage preamps (18V StingRay) keep the boosted lows clean.', q_es: '¿Cómo evito un Si grave flojo?', a_es: 'La tensión viene de escala más setup: los 34" piden ajuste correcto y el encordado a través del cuerpo ayuda (BB435, AmPro II). Los multiescala (EHB1005MS 33-35", Combustion 34-37") afinan cada cuerda a su tensión ideal. Los previos de mayor voltaje (StingRay 18V) mantienen limpios los graves realzados.' },
  { q: 'Active or passive for a first 5-string?', a: 'Passive (Affinity, BB435, CV 70s) means zero batteries and timeless tone. Active (Ray5, TRBX305, V7, StingRay, EHB1005MS, Dingwall) means onboard shaping and hotter outputs. Beginners should start passive; gigging players benefit from active EQ.', q_es: '¿Activo o pasivo para un primer cinco cuerdas?', a_es: 'Pasivo (Affinity, BB435, CV 70s) significa cero baterías y tono atemporal. Activo (Ray5, TRBX305, V7, StingRay, EHB1005MS, Dingwall) significa moldeo a bordo y salidas calientes. Principiantes mejor pasivo; músicos de bolo aprovechan la EQ activa.' },
  { q: 'Is multiscale worth it on a 5-string?', a: 'For the low B, yes: the EHB1005MS (33-35 in) and Dingwall Combustion (34-37 in) produce the clearest, most piano-like fifth strings tested anywhere near these prices. The tradeoff is fanned frets that take left-hand adjustment.', q_es: '¿Vale la pena el multiescala en cinco cuerdas?', a_es: 'Para el Si grave, sí: EHB1005MS (33-35") y Dingwall Combustion (34-37") producen las quintas más claras, casi piano, a estos precios. El costo es trastes abanico que piden adaptar la izquierda.' },
  { q: 'Sire V7 Gen 2 or New Gen?', a_es: '¿Sire V7 Gen 2 o New Gen?', a: 'Gen 2 runs 18 volts across two 9V batteries with a fuller control set — buy used if you find one. New Gen streamlines to a 4-knob preamp with stainless frets and Edgeless board, £729 new at Andertons. Same V7 platform, simpler workflow.', q_es: 'La Gen 2 corre 18 voltios en dos pilas 9V con más controles — cómprala usada si aparece. La New Gen simplifica a previo de 4 perillas con trastes inox y diapasón Edgeless, £729 nueva en Andertons. Misma plataforma V7, flujo más simple.' },
  { q: 'Dingwall Combustion 2PU or 3PU?', a: '2PU covers bridge punch and neck warmth with the Quad-tone rotary. 3PU adds the middle pickup for MM-style and J-style in-between voices. Both share the 34-37 in fan, EMG preamp and 8.75 lb average. Buy 3PU only if you will use the middle positions.', q_es: '¿Dingwall Combustion 2PU o 3PU?', a_es: 'La 2PU cubre pegada de puente y calidez de mástil con el rotary Quad-tone. La 3PU añade pastilla central para voces intermedias estilo MM y J. Ambas comparten abanico 34-37", previo EMG y 8,75 lb promedio. Compra 3PU solo si usarás las posiciones centrales.' }
);
g.featuredSnippet = {
  title_en: 'Best 5-String Basses by Price',
  text_en: 'The Yamaha TRBX305 is the best budget 5-string bass with M3 pickups and 5-way EQ. The Yamaha BB435 is the best mid-range passive 5-string. The StingRay Special 5 is the premium funk benchmark with 18V headroom.',
  name1_en: "Squier Classic Vibe '70s Jazz Bass V", name2_en: 'Ibanez EHB1005MS Headless Bass',
  price1: '', price2: '', type1: 'basses', type2: 'basses',
  key1_en: '70s J voice with blocks and nickel hardware', key2_en: 'Clearest low B with 33-35 in multiscale',
  best1_en: 'Best mid-range passive 5-string value', best2_en: 'Best multiscale 5-string under $1,500',
  brand1: 'Squier', brand2: 'Ibanez', rating1: 4.5, rating2: 4.7,
  title_es: 'Mejores bajos de 5 cuerdas por precio',
  text_es: 'El Yamaha TRBX305 es el mejor bajo de 5 cuerdas económico con pastillas M3 y EQ de 5 posiciones. El Yamaha BB435 es el mejor pasivo medio. El StingRay Special 5 es la referencia funk premium con headroom 18V.',
  name1_es: "Squier Classic Vibe '70s Jazz Bass V", name2_es: 'Ibanez EHB1005MS Headless Bass',
  best1_es: 'Mejor pasivo medio calidad-precio en 5 cuerdas', best2_es: 'Mejor multiescala 5 cuerdas bajo $1.500',
  key1_es: 'Voz J 70s con bloques y níquel', key2_es: 'Si grave más claro con multiescala 33-35"',
  faq_q1_en: 'Is a 5-string bass harder for beginners?', faq_a1_en: g.faq[0].a,
  faq_q2_en: 'How do I stop my low B from sounding floppy?', faq_a2_en: g.faq[1].a,
  faq_q3_en: 'Active or passive for a first 5-string?', faq_a3_en: g.faq[2].a,
  faq_q4_en: 'Is multiscale worth it on a 5-string?', faq_a4_en: g.faq[3].a,
  faq_q5_en: 'Sire V7 Gen 2 or New Gen?', faq_a5_en: g.faq[4].a,
  faq_q6_en: 'Dingwall Combustion 2PU or 3PU?', faq_a6_en: g.faq[5].a,
  faq_q1_es: '¿Un bajo de 5 cuerdas es más difícil para principiantes?', faq_a1_es: g.faq[0].a_es,
  faq_q2_es: '¿Cómo evito un Si grave flojo?', faq_a2_es: g.faq[1].a_es,
  faq_q3_es: '¿Activo o pasivo para un primer cinco cuerdas?', faq_a3_es: g.faq[2].a_es,
  faq_q4_es: '¿Vale la pena el multiescala en cinco cuerdas?', faq_a4_es: g.faq[3].a_es,
  faq_q5_es: '¿Sire V7 Gen 2 o New Gen?', faq_a5_es: g.faq[4].a_es,
  faq_q6_es: '¿Dingwall Combustion 2PU o 3PU?', faq_a6_es: g.faq[5].a_es,
  specs: '12 five-string basses: 4 budget, 4 mid-range, 4 premium'
};
G.push(g);
fs.writeFileSync('data/guides.json', JSON.stringify(G, null, 2));
const gg = JSON.parse(fs.readFileSync('data/guides.json', 'utf8')).find(x => x.id === 'best-5-string-basses');
console.log('part2: sections=' + gg.sections.length + ' faq=' + gg.faq.length + ' titleTag=' + gg.titleTag.length + 'ch desc=' + gg.description.length + 'ch');
