// Create best-bass-home-office guide (mirrors best-guitar-home-office).
const fs = require('fs');
const G = JSON.parse(fs.readFileSync('data/guides.json', 'utf8'));
if (G.some(x => x.id === 'best-bass-home-office')) { console.log('EXISTS - abort'); process.exit(1); }
const V = (value, value_es) => ({ value, value_es });
const W = (t) => ({ title: t, title_es: t });
const VD = (name, pros, cons, pros_es, cons_es) => ({ name, name_es: name, pros, cons, pros_es, cons_es });
const S = (heading, heading_es, content, content_es, products) => ({ heading, heading_es, content, content_es, products });
const F = (q, a, q_es, a_es) => ({ q, a, q_es, a_es });
const AUTHOR = { '@type': 'Person', name: 'Daniel Carnago', givenName: 'Daniel', familyName: 'Carnago', alternateName: 'Cuban3Beats', jobTitle: 'Professional Musician & Audio Engineer', description: 'Touring musician with 20+ years of experience performing on world stages including Glastonbury, Broadway, and Abbey Road.', url: 'https://topmusiciangear.com/about.html', sameAs: ['https://www.youtube.com/@Cuban3Beats', 'https://open.spotify.com/artist/3HMtcts1AYCzkI4pBQKRzX', 'https://www.tiktok.com/@cuban3beats', 'https://www.facebook.com/Cuban3Beats/', 'https://www.instagram.com/cuban3beats', 'https://x.com/Cuban3Beats'], knowsAbout: ['Audio Engineering', 'Music Production', 'Live Sound', 'Studio Recording', 'Music Gear'] };

const g = {
  id: 'best-bass-home-office',
  title: 'Best Bass for Remote Workers & Home Offices',
  title_es: 'Mejor bajo para Home Office y Trabajo Remoto',
  titleTag: '8 Quiet Basses for Home Offices Compared (2026)',
  titleTag_es: '8 bajos silenciosos para home office comparados (2026)',
  category: 'basses',
  image: 'https://r2.gear4music.com/media/109/1095787/1200/preview.jpg',
  badge: 'recommended',
  intro: 'A full-size bass is a home-office hazard: a long headstock that hits shelves and monitors, weight that punishes your shoulder between meetings, and volume that travels through walls. The eight basses in this guide solve it three ways — headless designs that cut length without cutting scale, ultra-portable travel basses that fly overhead, and short-scale classics that shrink reach while keeping real tone.',
  intro_es: 'Un bajo de tamaño completo es un peligro en la oficina de casa: pala larga que golpea estantes y monitores, peso que castiga el hombro entre reuniones y volumen que viaja por paredes. Los ocho bajos de esta guía lo resuelven de tres formas — diseños headless que recortan longitud sin recortar escala, bajos de viaje ultra-portátiles que vuelan en cabina y clásicos de escala corta que reducen alcance con tono real.',
  sections: [
    S('Why a Normal Bass Fails in a Home Office', 'Por qué un bajo normal falla en la oficina de casa',
      '<p><strong>A 34-inch bass with a headstock is over 45 inches of leverage swinging next to your monitors.</strong> That is the core problem: length, not sound. Headless designs remove the headstock entirely, keeping full 34-inch string tension in a body that fits beside a desk. Travel basses go further, shrinking to carry-on size for flights and hotel rooms.</p><p><strong>Short-scale basses attack the other end: reach.</strong> A 30-inch (or shorter) scale brings frets closer together, which suits small hands, guitarists doubling on bass, and long writing sessions. You trade a little low-end tightness for a lot of comfort — through headphones or a small interface, nobody notices.</p><p><strong>The three categories below cover every desk.</strong> Headless for maximum ergonomics at home, ultra-portable for travel, short-scale for classic feel in less space. Then read how scale lengths differ and how to play silently.</p>',
      '<p><strong>Un bajo de 34" con pala supera 45 pulgadas de palanca junto a tus monitores.</strong> Ese es el problema central: longitud, no sonido. Los diseños headless eliminan la pala por completo, manteniendo tensión completa de 34" en un cuerpo que cabe junto al escritorio. Los bajos de viaje van más allá, encogiendo a tamaño cabina para vuelos y hoteles.</p><p><strong>Los bajos de escala corta atacan el otro extremo: alcance.</strong> Una escala de 30" (o menos) acerca los trastes, ideal para manos pequeñas, guitarristas doblando bajo y sesiones largas. Cambias un poco de firmeza en graves por mucha comodidad — por auriculares o interfaz pequeña, nadie lo nota.</p><p><strong>Las tres categorías de abajo cubren cada escritorio.</strong> Headless para máxima ergonomía en casa, ultra-portátiles para viajar, escala corta para tacto clásico en menos espacio. Después lee cómo difieren las escalas y cómo tocar en silencio.</p>',
      []),
    S('Ibanez EHB1000: Full 34-Inch Scale, Zero Headstock', 'Ibanez EHB1000: Escala completa 34", cero pala',
      '<strong>The EHB1000 keeps standard 34-inch string tension while the headless body cuts overall length dramatically.</strong> Chambered American basswood body, Bartolini BH2 pickups with Vari-mid three-band EQ and bypass switch, five-piece roasted maple and walnut neck with stainless-steel frets, MR5HS bridge, locking output jack, finger ramp and gig bag included. The pro desk bass for players who refuse to downscale their sound.',
      '<strong>El EHB1000 mantiene tensión estándar de 34" mientras el cuerpo headless recorta la longitud total drásticamente.</strong> Cuerpo chambered de tilo americano, pastillas Bartolini BH2 con EQ Vari-mid de tres bandas y bypass, mástil de cinco piezas arce tostado y nogal con trastes inoxidables, puente MR5HS, jack con bloqueo, rampa y funda incluidos. El bajo de escritorio pro para quien se niega a reducir su sonido.', [528]),
    S('Sire Marcus Miller M6 Headless: Multiscale Ergonomics', 'Sire Marcus Miller M6 Headless: Ergonomía multiescala',
      '<strong>A headless multiscale — 33 to 34.5 inches across the four strings — that balances tension string by string.</strong> Marcus Pure-H Revolution humbuckers feed the Heritage-3 preamp with active/passive switching, mahogany body, five-piece maple and mahogany C neck, Edgeless rosewood board and stainless frets. Available in 4, 5 and 6-string versions for extended-range writers.',
      '<strong>Un headless multiescala — 33 a 34,5" entre cuerdas — que balancea la tensión cuerda por cuerda.</strong> Humbuckers Marcus Pure-H Revolution alimentan el previo Heritage-3 con conmutación activo/pasivo, cuerpo de caoba, mástil C de cinco piezas arce/caoba, diapasón palisandro Edgeless y trastes inoxidables. Disponible en versiones de 4, 5 y 6 cuerdas para compositores de rango extendido.', [529]),
    S('Traveler Ultra-Light Bass: 1.55 kg That Flies Overhead', 'Traveler Ultra-Light Bass: 1,55 kg que vuela en cabina',
      '<strong>Thirty-inch scale, 33.75 inches total, 1.55 kilograms: the smallest honest bass that still feels like a bass.</strong> Passive Shadow piezo pickup with no battery to die mid-trip, detachable lap-rest frame for seated playing, neck-through maple construction, gig bag included. Fits airline overhead bins; runs into any amp or interface.',
      '<strong>Escala 30", 85,7 cm total, 1,55 kilos: el bajo honesto más pequeño que aún se siente bajo.</strong> Piezo pasivo Shadow sin batería que muera a mitad de viaje, marco lap-rest desmontable para tocar sentado, construcción neck-through de arce, funda incluida. Cabe en compartimentos de avión; funciona con cualquier ampli o interfaz.', [530]),
    S('Traveler TB-4P: Silent Practice Built Into the Bass', 'Traveler TB-4P: Práctica silenciosa integrada en el bajo',
      '<strong>The only bass here you can practice with wearing headphones and nothing else.</strong> A built-in headphone amp with clean, boost, overdrive and distortion plus aux-in runs on two AAA batteries, feeding a 32-inch medium-scale bass with Duncan Designed split-coil P pickup and active Volume plus Tone. Traditional closed alder body for players who want normal looks with travel size.',
      '<strong>El único bajo aquí practicable solo con auriculares y nada más.</strong> Un amplificador de auriculares integrado con clean, boost, overdrive y distorsión más aux-in funciona con dos AAA, alimentando un bajo de escala media 32" con split-coil P Duncan Designed y Volumen más Tono activos. Cuerpo cerrado tradicional de aliso para quien quiere estética normal en tamaño viaje.', [531]),
    S('Kala U-Bass Solid Body: Ukulele Size, Real Bass Lows', 'Kala U-Bass Solid Body: Tamaño ukelele, graves reales',
      '<strong>Tuned EADG like a full bass on a 23.5-inch solid body that fits in a backpack.</strong> Passive split-coil pickup with Volume and Tone, offset okoume body, maple neck with 22 laurel frets. The sub lows surprise every first-time listener — the producer secret for bass lines from hotel rooms.',
      '<strong>Afinado EADG como un bajo real en cuerpo sólido de 23,5" que cabe en una mochila.</strong> Pastilla split-coil pasiva con Volumen y Tono, cuerpo offset de okoume, mástil de arce con 22 trastes de laurel. Los subgraves sorprenden a cada oyente primerizo — el secreto de productores para líneas de bajo desde hoteles.', [532]),
    S('Fender Player II Mustang PJ: The Classic Short-Scale', 'Fender Player II Mustang PJ: El clásico de escala corta',
      '<strong>Thirty inches of Fender short-scale history with modern PJ versatility.</strong> Player Series Alnico 5 split-coil Precision plus single-coil Jazz in an alder body, Modern C maple neck, 19 medium-jumbo frets and three-way switching. Real Fender feel, real resale value, zero learning curve for P and J players.',
      '<strong>Treinta pulgadas de historia Fender de escala corta con versatilidad PJ moderna.</strong> Split-coil Precision más single-coil Jazz Alnico 5 Player Series en cuerpo de aliso, mástil Modern C de arce, 19 trastes medium-jumbo y conmutador de tres posiciones. Tacto Fender real, reventa real, cero curva para bajistas P y J.', [533]),
    S('Gretsch G2220 Junior Jet II: Classic Looks, Easy Reach', 'Gretsch G2220 Junior Jet II: Estética clásica, alcance fácil',
      '<strong>A 30.3-inch single-cut with unmistakable Jet style for the smallest budget here.</strong> Note the current production runs dual single-coil pickups — bright and open, but not hum-cancelling (older mini-humbucker versions are the ones to hunt used). Basswood body, bolt-on maple neck, 20 medium-jumbo frets. New stock is scarce right now, so check availability.',
      '<strong>Un single-cut de 30,3" con estilo Jet inconfundible por el menor presupuesto aquí.</strong> Ojo: la producción actual lleva dos single-coils — brillantes y abiertas, pero sin cancelación de hum (las versiones mini-humbucker anteriores son las buscadas de segunda mano). Cuerpo de tilo, mástil atornillado de arce, 20 trastes medium-jumbo. El stock nuevo escasea ahora, revisa disponibilidad.', [534]),
    S('Jackson JS1X Minion: The Shortest Real-Wood Bass', 'Jackson JS1X Minion: El bajo de madera real más corto',
      '<strong>Twenty-eight-point-six inches of passive PJ in a poplar Concert body — built for guitarists who need bass lines fast.</strong> P-style neck plus J-style bridge pickups with dual volumes and master tone, one-piece maple speed neck, amaranth board with 22 jumbo frets and sharkfin inlays. The cheapest seat at this desk.',
      '<strong>Veintiocho coma seis pulgadas de PJ pasivo en cuerpo Concert de álamo — hecho para guitarristas que necesitan líneas de bajo rápido.</strong> Pastillas estilo P en mástil más J en puente con dos volúmenes y tono master, mástil speed de arce de una pieza, diapasón amaranto con 22 trastes jumbo e incrustaciones sharkfin. El asiento más barato de este escritorio.', [535]),
    S('Scale Lengths Explained: 34 vs 30 vs Headless Multiscale', 'Escalas explicadas: 34 contra 30 contra multiescala headless',
      '<p><strong>Scale length sets string tension, fret spacing and low-end tightness.</strong> Standard 34-inch gives the firmest lows and widest stretches — headless designs like the EHB1000 keep it while removing the headstock. Short-scale 30-inch (and below) shortens stretches for small hands at the cost of slightly looser lows. Multiscale (like the Sire M6 at 33 to 34.5 inches) gives each string its ideal tension: tight lows, singing highs.</p><p><strong>For desk playing, prioritize reach over tradition.</strong> Guitarists doubling on bass should start at 30 inches or below; career bassists keeping technique should stay at 34 inches headless or multiscale. For starting points by budget, see <a class="guide-link-btn" href="/guides/beginner-bass-guitars.html">beginner bass guitars</a> and the full <a class="guide-link-btn" href="/guides/fender-bass-guide.html">Fender bass guide</a>.</p>',
      '<p><strong>La escala define tensión, separación de trastes y firmeza de graves.</strong> La estándar 34" da graves más firmes y trastes más separados — los headless como el EHB1000 la conservan eliminando la pala. La corta 30" (o menos) acorta trastes para manos pequeñas a cambio de graves algo más sueltos. La multiescala (como el Sire M6 de 33 a 34,5") da a cada cuerda su tensión ideal: graves tensos, agudos cantantes.</p><p><strong>Para escritorio, prioriza alcance sobre tradición.</strong> Guitarristas doblando bajo empiezan en 30" o menos; bajistas de carrera mantienen 34" headless o multiescala. Para puntos de partida por presupuesto, revisa <a class="guide-link-btn" href="/guides/beginner-bass-guitars_es.html">bajos para principiantes</a> y la <a class="guide-link-btn" href="/guides/fender-bass-guide_es.html">guía de bajos Fender</a>.</p>',
      []),
    S('Sounding Big Without Noise: Interfaces and Practice Amps', 'Sonar grande sin ruido: interfaces y amplis de práctica',
      '<p><strong>Only one bass here makes sound alone with headphones — for the rest, the silent chain is bass, small interface, headphones.</strong> The Traveler TB-4P covers hotels with its built-in amp; at the desk, any USB interface plus closed-back headphones gives full tone at midnight. Skip traditional amps entirely in shared spaces.</p><p><strong>When you want air movement, go small and bass-specific.</strong> Practice combos voiced for bass keep lows tight at conversation volume where guitar amps would distort. See <a class="guide-link-btn" href="/guides/best-bass-practice-amps.html">best bass practice amps</a> and <a class="guide-link-btn" href="/guides/best-bass-amps.html">best bass amps</a> for the full breakdown.</p>',
      '<p><strong>Solo un bajo aquí suena solo con auriculares — para el resto, la cadena silenciosa es bajo, interfaz pequeña, auriculares.</strong> El Traveler TB-4P cubre hoteles con su ampli integrado; en el escritorio, cualquier interfaz USB más auriculares cerrados da tono completo a medianoche. Olvida amplis tradicionales en espacios compartidos.</p><p><strong>Cuando quieras mover aire, ve pequeño y específico de bajo.</strong> Los combos de práctica voiced para bajo mantienen graves firmes a volumen conversación donde un ampli de guitarra distorsionaría. Revisa <a class="guide-link-btn" href="/guides/best-bass-practice-amps_es.html">mejores amplis de bajo para practicar</a> y <a class="guide-link-btn" href="/guides/best-bass-amps_es.html">mejores amplis de bajo</a> para el desglose.</p>',
      [])
  ],
  conclusion: 'For most home offices, the Ibanez EHB1000 is the no-compromise answer: full 34-inch scale and pro hardware in a headless body that fits beside a desk. If you fly constantly, the Traveler Ultra-Light Bass disappears into overhead bins, and the TB-4P adds silent headphone practice anywhere. For classic feel in less space, the Fender Player II Mustang PJ is the safe short-scale that holds resale value, while the Jackson Minion is the cheapest way to keep real bass lines at arm\'s reach.',
  conclusion_es: 'Para la mayoría de oficinas en casa, el Ibanez EHB1000 es la respuesta sin concesiones: escala completa 34" y hardware pro en cuerpo headless que cabe junto al escritorio. Si vuelas constantemente, el Traveler Ultra-Light Bass desaparece en compartimentos superiores, y el TB-4P añade práctica silenciosa con auriculares en cualquier lugar. Para tacto clásico en menos espacio, el Fender Player II Mustang PJ es el escala corta seguro que mantiene reventa, mientras el Jackson Minion es la forma más barata de tener líneas de bajo reales al alcance.',
  verdict: 'Need full-scale tone with zero headstock? Ibanez EHB1000. Need multiscale ergonomics? Sire M6 Headless. Need the lightest flyable bass? Traveler Ultra-Light. Need silent hotel practice with nothing else? Traveler TB-4P. Need ukulele-size lows? Kala U-Bass. Need the classic short-scale that resells? Fender Mustang PJ. Need classic looks cheapest? Gretsch G2220. Need the shortest real-wood bass for quick lines? Jackson Minion.',
  verdict_es: '¿Tono de escala completa sin pala? Ibanez EHB1000. ¿Ergonomía multiescala? Sire M6 Headless. ¿El bajo volable más ligero? Traveler Ultra-Light. ¿Práctica silenciosa de hotel sin nada más? Traveler TB-4P. ¿Graves tamaño ukelele? Kala U-Bass. ¿El clásico escala corta que se revende? Fender Mustang PJ. ¿Estética clásica lo más barato? Gretsch G2220. ¿El bajo de madera real más corto para líneas rápidas? Jackson Minion.',
  featuredProducts: [528, 529, 530, 531, 532, 533, 534, 535],
  description: '8 quiet, desk-friendly basses for home offices: headless, travel and short-scale picks with silent practice options. (2026 comparison)',
  description_es: '8 bajos silenciosos de escritorio para home office: headless, viaje y escala corta con opciones de práctica silenciosa. (comparativa 2026)',
  featuredSnippet: {
    title_en: 'Best Bass for Remote Workers & Home Offices',
    text_en: 'The Ibanez EHB1000 is the best headless bass for home offices with a full 34-inch scale and pro Bartolini hardware. The Traveler Ultra-Light Bass is the lightest flyable bass at 1.55 kg. The Fender Player II Mustang PJ is the best classic short-scale.',
    name1_en: 'Fender Player II Mustang Bass PJ', name2_en: 'Jackson JS1X Concert Bass Minion',
    price1: '', price2: '', type1: 'basses', type2: 'basses',
    key1_en: 'Classic 30-inch short-scale PJ versatility', key2_en: 'Shortest real-wood bass for quick lines',
    best1_en: 'Best classic short-scale for home office', best2_en: 'Best budget micro-scale bass',
    brand1: 'Fender', brand2: 'Jackson', rating1: 4.9, rating2: 4.6,
    title_es: 'Mejor bajo para Home Office y Trabajo Remoto',
    text_es: 'El Ibanez EHB1000 es el mejor bajo headless para oficinas en casa, con escala completa 34" y hardware Bartolini pro. El Traveler Ultra-Light Bass es el bajo volable más ligero con 1,55 kg. El Fender Player II Mustang PJ es el mejor clásico de escala corta.',
    name1_es: 'Fender Player II Mustang Bass PJ', name2_es: 'Jackson JS1X Concert Bass Minion',
    best1_es: 'Mejor clásico escala corta para home office', best2_es: 'Mejor bajo micro-escala económico',
    key1_es: 'Versatilidad PJ clásica 30 pulgadas', key2_es: 'Bajo de madera real más corto para líneas rápidas',
    faq_q1_en: 'Is a headless bass better for a home office desk?',
    faq_a1_en: 'Yes. A headless bass removes the headstock, cutting 6 to 8 inches of total length while keeping full 34-inch string tension, like the Ibanez EHB1000. Nothing hits your monitors or shelves, tuning happens at the bridge, and balance improves seated. It is the simplest ergonomic upgrade for desk playing.',
    faq_q2_en: 'Can I practice bass silently in an apartment?',
    faq_a2_en: 'Yes. The Traveler TB-4P has a built-in headphone amp with aux-in, so you need nothing else. For the other seven basses, plug into any small USB interface and closed-back headphones for full tone at midnight. Skip traditional amps in shared spaces.',
    faq_q3_en: 'Is a 30-inch short-scale bass easier to play?',
    faq_a3_en: 'For small hands and guitarists doubling on bass, yes. Frets sit closer together, stretches shrink and weight usually drops. You trade a little low-end tightness versus 34-inch scale, which nobody notices through headphones or a small interface.',
    faq_q4_en: 'Can I take these basses on a plane?',
    faq_a4_en: 'The Traveler Ultra-Light Bass at 33.75 inches and the Kala U-Bass fit airline overhead bins and backpacks. The TB-4P at 35.25 inches usually fits too. Headless basses like the EHB1000 are dramatically shorter than headed basses and travel far easier, though a gig bag may still need gate check.',
    faq_q5_en: 'Does the Kala U-Bass really sound like a bass?',
    faq_a5_en: 'Yes. It is tuned EADG exactly like a full bass, and its small body produces massive sub lows that surprise first-time listeners. The solid-body version behaves like an electric: silent unplugged, full voice through an amp or interface.',
    faq_q6_en: 'Ibanez EHB1000 or Sire M6 Headless?',
    faq_a6_en: 'Pick fixed 34-inch scale and Bartolini plus Vari-mid electronics with the EHB1000, or multiscale ergonomics from 33 to 34.5 inches with Heritage-3 preamp on the Sire M6. Both are pro-grade headless basses; fixed scale suits traditionalists, multiscale suits low-tension seekers.',
    faq_q1_es: '¿Un bajo headless es mejor para el escritorio?',
    faq_a1_es: 'Sí. Un bajo headless elimina la pala, recortando 6 a 8 pulgadas de longitud total manteniendo tensión completa de 34", como el Ibanez EHB1000. Nada golpea monitores o estantes, se afina en el puente y el balance sentado mejora. Es la mejora ergonómica más simple para tocar en escritorio.',
    faq_q2_es: '¿Puedo practicar bajo en silencio en un apartamento?',
    faq_a2_es: 'Sí. El Traveler TB-4P trae amplificador de auriculares con aux-in, no necesitas nada más. Para los otros siete, conéctate a cualquier interfaz USB pequeña y auriculares cerrados para tono completo a medianoche. Olvida amplis tradicionales en espacios compartidos.',
    faq_q3_es: '¿Un bajo de escala corta 30" es más fácil?',
    faq_a3_es: 'Para manos pequeñas y guitarristas doblando bajo, sí. Los trastes quedan más juntos, los estiramientos se reducen y el peso suele bajar. Cambias un poco de firmeza en graves frente a 34", que nadie nota por auriculares o interfaz pequeña.',
    faq_q4_es: '¿Puedo llevar estos bajos en avión?',
    faq_a4_es: 'El Traveler Ultra-Light Bass con 85,7 cm y el Kala U-Bass caben en compartimentos superiores y mochilas. El TB-4P con 89,5 cm suele caber también. Los headless como el EHB1000 son dramáticamente más cortos y viajan mucho más fácil, aunque la funda a veces pide entrega en puerta.',
    faq_q5_es: '¿El Kala U-Bass suena de verdad como un bajo?',
    faq_a5_es: 'Sí. Está afinado EADG exactamente como un bajo real, y su cuerpo pequeño produce subgraves masivos que sorprenden a primerizos. La versión solid-body se comporta como eléctrica: silenciosa desenchufada, voz completa por ampli o interfaz.',
    faq_q6_es: '¿Ibanez EHB1000 o Sire M6 Headless?',
    faq_a6_es: 'Elige escala fija 34" con Bartolini más Vari-mid en el EHB1000, o ergonomía multiescala de 33 a 34,5" con previo Heritage-3 en el Sire M6. Ambos son headless pro; la escala fija conviene a tradicionalistas, la multiescala a buscadores de baja tensión.',
    specs: '8 basses: 2 headless, 3 travel, 3 short-scale'
  },
  relatedGuides: ['best-bass-practice-amps', 'beginner-bass-guitars', 'fender-bass-guide', 'best-guitar-home-office', 'best-bass-amps', 'budget-bass-like-expensive'],
  author: AUTHOR,
  aboutName: 'Basses',
  productTable: { columns: [], rows: [] },
  verdictProsCons: [],
  datePublished: '2026-10-02',
  titleTag: '8 Quiet Basses for Home Offices Compared (2026)',
  faq: []
};

const cols = ['Ibanez EHB1000 Headless Bass', 'Sire Marcus Miller M6 Headless Bass', 'Traveler Guitar Ultra-Light Bass', 'Traveler Guitar TB-4P Bass', 'Kala U-Bass Solid Body', 'Fender Player II Mustang Bass PJ', 'Gretsch G2220 Junior Jet Bass II', 'Jackson JS1X Concert Bass Minion'];
cols.forEach(t => g.productTable.columns.push(W(t)));
const rows = {};
const putRow = (label, arr) => { const r = { label, values: arr }; g.productTable.rows.push(r); rows[r.label] = r; };
putRow('Best For', [V('Pro headless with full 34-inch scale', 'Headless pro con escala completa 34"'), V('Multiscale headless with studio preamp', 'Headless multiescala con previo de estudio'), V('Lightest honest bass for flights', 'Bajo honesto más ligero para vuelos'), V('Travel bass with silent practice built in', 'Bajo de viaje con práctica silenciosa integrada'), V('Ukulele-size bass with real low end', 'Bajo tamaño ukelele con graves reales'), V('Classic 30-inch short-scale PJ', 'Clásico PJ de escala corta 30"'), V('Budget short-scale with classic looks', 'Escala corta económica con estética clásica'), V('Shortest real-wood bass for the desk', 'Bajo de madera real más corto para el escritorio')]);
putRow('Type', [V('Headless solid-body', 'Headless cuerpo sólido'), V('Headless multi-scale', 'Headless multiescala'), V('Travel solid-body', 'Sólido de viaje'), V('Travel solid-body', 'Sólido de viaje'), V('Solid-body short-scale', 'Sólido escala corta'), V('Short-scale solid-body', 'Sólido escala corta'), V('Short-scale single-cut', 'Single-cut escala corta'), V('Micro-scale solid-body', 'Sólido micro-escala')]);
putRow('Scale Length', [V('34 in (864 mm)', '34" (864 mm)'), V('33-34.5 in (838-876 mm)', '33-34,5" (838-876 mm)'), V('30 in', '30"'), V('32 in (812 mm)', '32" (812 mm)'), V('23.5 in', '23,5"'), V('30 in (762 mm)', '30" (762 mm)'), V('30.3 in (770 mm)', '30,3" (770 mm)'), V('28.6 in (726 mm)', '28,6" (726 mm)')]);
putRow('Weight', [V('Not published (varies by unit)', 'No publicado (varía por unidad)'), V('Under 8 lb (maker-quoted samples)', 'Menos de 8 lb (muestras del fabricante)'), V('3.4 lb (1.55 kg)', '3,4 lb (1,55 kg)'), V('6.5 lb (2.95 kg)', '6,5 lb (2,95 kg)'), V('Not published (varies by unit)', 'No publicado (varía por unidad)'), V('Not published (varies by unit)', 'No publicado (varía por unidad)'), V('Not published (varies by unit)', 'No publicado (varía por unidad)'), V('Not published (varies by unit)', 'No publicado (varía por unidad)')]);
putRow('Body', [V('Chambered American basswood', 'Tilo americano chambered'), V('Mahogany (ash on sandblasted)', 'Caoba (fresno en sandblasted)'), V('Neck-through hard maple, minimal body', 'Arce neck-through, cuerpo mínimo'), V('Alder, closed traditional shape', 'Aliso, forma cerrada tradicional'), V('Okoume offset, gloss', 'Okoume offset, brillo'), V('Alder, gloss polyester', 'Aliso, poliéster brillo'), V('Basswood Jet single-cut', 'Tilo Jet single-cut'), V('Poplar Concert', 'Álamo Concert')]);
putRow('Neck & Fretboard', [V('5-pc roasted maple/walnut, 24 stainless', '5 piezas arce tostado/nogal, 24 inox'), V('5-pc maple/mahogany C, Edgeless rosewood 16 in, 24 stainless', '5 piezas arce/caoba C, palisandro Edgeless 16", 24 inox'), V('Black walnut board, 22 medium', 'Diapasón nogal negro, 22 medium'), V('Maple bolt-on, 9.5 in, 22 jumbo', 'Arce atornillado, 9,5", 22 jumbo'), V('Maple, laurel board, 22 frets', 'Arce, diapasón laurel, 22 trastes'), V('Modern C maple, 9.5 in, 19 medium jumbo', 'Modern C arce, 9,5", 19 medium jumbo'), V('Maple bolt-on, 12 in, 20 medium jumbo', 'Arce atornillado, 12", 20 medium jumbo'), V('1-pc maple speed neck, amaranth 12 in, 22 jumbo', 'Arce 1 pieza speed, amaranto 12", 22 jumbo')]);
putRow('Pickups', [V('2x Bartolini BH2', '2x Bartolini BH2'), V('2x Marcus Pure-H Revolution humbuckers', '2x humbuckers Marcus Pure-H Revolution'), V('Shadow under-saddle piezo (passive)', 'Piezo Shadow bajo cejuela (pasivo)'), V('Duncan Designed split-coil P', 'Split-coil P Duncan Designed'), V('Passive split-coil', 'Split-coil pasiva'), V('Alnico 5 split P + single J', 'Alnico 5 split P + single J'), V('2x single-coil (current prod.)', '2x single-coil (prod. actual)'), V('P + J passive', 'P + J pasivas')]);
putRow('Electronics', [V('Vari-mid 3-band EQ + bypass', 'EQ Vari-mid 3 bandas + bypass'), V('Heritage-3 preamp (active/passive)', 'Previo Heritage-3 (activo/pasivo)'), V('Passive, no battery', 'Pasivo, sin batería'), V('Active Volume + Tone', 'Volumen + Tono activos'), V('Volume + Tone', 'Volumen + Tono'), V('Master Vol + Tone, 3-way', 'Vol + Tono master, 3 posic.'), V('Master Vol + Tone, 3-way toggle', 'Vol + Tono master, toggle 3 posic.'), V('2x Vol + Master Tone', '2x Vol + Tono master')]);
putRow('Headphone Output', [V('No', 'No'), V('No', 'No'), V('No', 'No'), V('Yes — built-in amp', 'Sí — ampli integrado'), V('No', 'No'), V('No', 'No'), V('No', 'No'), V('No', 'No')]);

g.verdictProsCons.push(
  VD('Ibanez EHB1000 Headless Bass',
    ['Full 34-inch scale with zero headstock', 'Bartolini BH2 plus Vari-mid 3-band EQ with bypass', 'Chambered body, stainless frets, pro hardware throughout', 'Gig bag and finger ramp included'],
    ['Premium price for a desk bass', 'No headphone output — needs interface or amp', 'Weight unpublished, varies by unit', 'Active EQ needs battery unless bypassed'],
    ['Escala completa 34" sin pala', 'Bartolini BH2 más EQ Vari-mid 3 bandas con bypass', 'Cuerpo chambered, trastes inox, hardware pro', 'Funda y rampa incluidos'],
    ['Precio premium para bajo de escritorio', 'Sin salida auriculares — pide interfaz o ampli', 'Peso no publicado, varía por unidad', 'La EQ activa pide batería salvo bypass']),
  VD('Sire Marcus Miller M6 Headless Bass',
    ['Multiscale 33 to 34.5 inches balances every string', 'Heritage-3 preamp with active/passive switching', 'Stainless frets and Edgeless board, 4/5/6-string range', 'Under 8 lb in maker-quoted samples'],
    ['Only one verified store carries it', 'Multiscale takes adjustment for traditionalists', 'No headphone output', 'Heavier than true travel basses'],
    ['Multiescala 33 a 34,5" balancea cada cuerda', 'Previo Heritage-3 con conmutación activo/pasivo', 'Trastes inox y diapasón Edgeless, rango 4/5/6 cuerdas', 'Menos de 8 lb en muestras del fabricante'],
    ['Solo una tienda verificada lo vende', 'La multiescala pide adaptación a tradicionalistas', 'Sin salida de auriculares', 'Más pesado que bajos de viaje reales']),
  VD('Traveler Guitar Ultra-Light Bass',
    ['1.55 kg and 85.7 cm — flies in overhead bins', 'Real 30-inch bass scale', 'Passive piezo, no battery ever dies', 'Lap-rest frame and gig bag included'],
    ['No headphone amp — needs interface or amp', 'Minimal body takes seated getting-used-to', 'Single piezo voice, no magnetic options', 'Only 22 medium frets'],
    ['1,55 kg y 85,7 cm — vuela en cabina', 'Escala real de bajo 30"', 'Piezo pasivo, ninguna batería muere', 'Marco lap-rest y funda incluidos'],
    ['Sin ampli de auriculares — pide interfaz o ampli', 'Cuerpo mínimo pide adaptación sentado', 'Una sola voz piezo, sin opciones magnéticas', 'Solo 22 trastes medium']),
  VD('Traveler Guitar TB-4P Bass',
    ['Built-in headphone amp plus aux-in — practice anywhere alone', 'Familiar 32-inch medium scale', 'Duncan Designed P plus active EQ', 'Traditional closed alder body'],
    ['2.95 kg — heavier than the Ultra-Light', 'No output without 2xAAA batteries', 'Single-pickup layout limits voices', 'No USB recording like smart amps'],
    ['Ampli de auriculares más aux-in — practica solo en cualquier lugar', 'Familiar escala media 32"', 'P Duncan Designed más EQ activa', 'Cuerpo tradicional cerrado de aliso'],
    ['2,95 kg — más pesado que el Ultra-Light', 'Sin salida sin 2 pilas AAA', 'Diseño una pastilla limita voces', 'Sin grabación USB como amplis smart']),
  VD('Kala U-Bass Solid Body',
    ['EADG tuning like a full bass in ukulele size', 'Massive sub lows from a tiny body', 'Passive simplicity — Volume plus Tone', 'Backpack-portable with gig bag'],
    ['Gear4Music currently unavailable', 'Silent unplugged — needs amp or interface', 'Only 22 frets', 'Tight spacing challenges big hands'],
    ['Afinación EADG como bajo real en tamaño ukelele', 'Subgraves masivos de cuerpo diminuto', 'Simplicidad pasiva — Volumen más Tono', 'Portátil en mochila con funda'],
    ['Gear4Music sin stock ahora', 'Silencioso desenchufado — pide ampli o interfaz', 'Solo 22 trastes', 'Espaciado estrecho reta manos grandes']),
  VD('Fender Player II Mustang Bass PJ',
    ['True 30-inch Fender short-scale', 'PJ versatility — split P plus single J', 'Alder body and Modern C quality finish', 'Strong resale value'],
    ['Premium price for a short-scale', 'Only 19 frets', 'No active option', 'Gloss polyester neck divides satin lovers'],
    ['Verdadera escala corta Fender 30"', 'Versatilidad PJ — split P más single J', 'Cuerpo aliso y acabado Modern C de calidad', 'Fuerte valor de reventa'],
    ['Precio premium para escala corta', 'Solo 19 trastes', 'Sin opción activa', 'Mástil poliéster brillo divide amantes del satén']),
  VD('Gretsch G2220 Junior Jet Bass II',
    ['Unmistakable Jet style, easiest reach here', '30.3-inch scale suits small hands', 'Light single-cut body', 'Cheapest entry of the eight'],
    ['Current single-coils hum — not cancelling', 'New stock scarce everywhere right now', 'Basic hardware throughout', 'Mixed 3.9-star Amazon reception'],
    ['Estilo Jet inconfundible, alcance más fácil aquí', 'Escala 30,3" ideal manos pequeñas', 'Cuerpo single-cut ligero', 'Entrada más barata de los ocho'],
    ['Single-coils actuales zumban — sin cancelar', 'Stock nuevo escaso en todos lados ahora', 'Hardware básico en todo', 'Recepción mixta 3,9 estrellas Amazon']),
  VD('Jackson JS1X Concert Bass Minion',
    ['Shortest real-wood bass at 28.6 inches', 'Passive PJ — no battery ever', 'Speed neck with sharkfin style', 'Cheapest of the eight, by far'],
    ['Cramped spacing for large hands', 'Basic electronics, no upgrades onboard', 'No active or humbucker voices', 'zZounds delisted it — fewer buying options'],
    ['Bajo de madera real más corto con 28,6"', 'PJ pasivo — sin batería jamás', 'Mástil speed con estética sharkfin', 'El más barato de los ocho, por lejos'],
    ['Espaciado estrecho para manos grandes', 'Electrónica básica, sin mejoras a bordo', 'Sin voces activas ni humbucker', 'zZounds lo deslistó — menos opciones de compra'])
);

g.faq.push(
  F('Is a headless bass better for a home office desk?', 'Yes. A headless bass removes the headstock, cutting 6 to 8 inches of total length while keeping full 34-inch string tension, like the Ibanez EHB1000. Nothing hits your monitors or shelves, tuning happens at the bridge, and seated balance improves. It is the simplest ergonomic upgrade for desk playing.', '¿Un bajo headless es mejor para el escritorio?', 'Sí. Un bajo headless elimina la pala, recortando 6 a 8 pulgadas de longitud total manteniendo tensión completa de 34", como el Ibanez EHB1000. Nada golpea monitores o estantes, se afina en el puente y el balance sentado mejora. Es la mejora ergonómica más simple para tocar en escritorio.'),
  F('Can I practice bass silently in an apartment?', 'Yes. The Traveler TB-4P has a built-in headphone amp with aux-in, so you need nothing else. For the other seven basses, plug into any small USB interface and closed-back headphones for full tone at midnight. Skip traditional amps in shared spaces.', '¿Puedo practicar bajo en silencio en un apartamento?', 'Sí. El Traveler TB-4P trae amplificador de auriculares con aux-in, no necesitas nada más. Para los otros siete, conéctate a cualquier interfaz USB pequeña y auriculares cerrados para tono completo a medianoche. Olvida amplis tradicionales en espacios compartidos.'),
  F('Is a 30-inch short-scale bass easier to play?', 'For small hands and guitarists doubling on bass, yes. Frets sit closer together, stretches shrink and weight usually drops. You trade a little low-end tightness versus 34-inch scale, which nobody notices through headphones or a small interface.', '¿Un bajo de escala corta 30" es más fácil?', 'Para manos pequeñas y guitarristas doblando bajo, sí. Los trastes quedan más juntos, los estiramientos se reducen y el peso suele bajar. Cambias un poco de firmeza en graves frente a 34", que nadie nota por auriculares o interfaz pequeña.'),
  F('Can I take these basses on a plane?', 'The Traveler Ultra-Light Bass at 33.75 inches and the Kala U-Bass fit airline overhead bins and backpacks. The TB-4P at 35.25 inches usually fits too. Headless basses like the EHB1000 are dramatically shorter than headed basses and travel far easier.', '¿Puedo llevar estos bajos en avión?', 'El Traveler Ultra-Light Bass con 85,7 cm y el Kala U-Bass caben en compartimentos superiores y mochilas. El TB-4P con 89,5 cm suele caber también. Los headless como el EHB1000 son dramáticamente más cortos y viajan mucho más fácil.'),
  F('Does the Kala U-Bass really sound like a bass?', 'Yes. It is tuned EADG exactly like a full bass, and its small body produces massive sub lows that surprise first-time listeners. The solid-body version behaves like an electric: silent unplugged, full voice through an amp or interface.', '¿El Kala U-Bass suena de verdad como un bajo?', 'Sí. Está afinado EADG exactamente como un bajo real, y su cuerpo pequeño produce subgraves masivos que sorprenden a primerizos. La versión solid-body se comporta como eléctrica: silenciosa desenchufada, voz completa por ampli o interfaz.'),
  F('Ibanez EHB1000 or Sire M6 Headless?', 'Pick fixed 34-inch scale with Bartolini plus Vari-mid electronics on the EHB1000, or multiscale ergonomics from 33 to 34.5 inches with Heritage-3 preamp on the Sire M6. Both are pro-grade headless basses; fixed scale suits traditionalists, multiscale suits players chasing even tension.', '¿Ibanez EHB1000 o Sire M6 Headless?', 'Elige escala fija 34" con Bartolini más Vari-mid en el EHB1000, o ergonomía multiescala de 33 a 34,5" con previo Heritage-3 en el Sire M6. Ambos son headless pro; la escala fija conviene a tradicionalistas, la multiescala a buscadores de tensión pareja.')
);

G.push(g);
fs.writeFileSync('data/guides.json', JSON.stringify(G, null, 2));
const gg = JSON.parse(fs.readFileSync('data/guides.json', 'utf8')).find(x => x.id === 'best-bass-home-office');
const union = [...new Set(gg.sections.flatMap(s => s.products || []))];
console.log('guide: cols=' + gg.productTable.columns.length + ' verdict=' + gg.verdictProsCons.length + ' sections=' + gg.sections.length + ' faq=' + gg.faq.length + ' cards=' + union.length + ' rowsok=' + gg.productTable.rows.every(r => r.values.length === gg.productTable.columns.length));
console.log('titleTag EN len=' + gg.titleTag.length + ' | desc EN len=' + gg.description.length);
