const fs = require('fs');
const s = fs.readFileSync('js/app.min.js', 'utf8');
console.log('Cuál ok:', s.includes('¿Cuál es'));
console.log('estándar ok:', s.includes('estándar'));
console.log('grabación ok:', s.includes('grabación'));
console.log('… ellipsis:', /…/.test(s));
console.log('— emdash:', /—/.test(s));
console.log('★ star:', s.includes('★'));
console.log('🎵 note:', s.includes('🎵'));
console.log('− minus:', s.includes('−'));
console.log('mojibake remaining:', (s.match(/â€|Ã(?:[±¤¡©³]|)/g) || []).length);
new Function(s);
console.log('SYNTAX OK');
console.log('--- git status ---');
console.log(require('child_process').execSync('git status --short js/app.min.js index.html').toString());