const fs = require('fs');
const DIR = 'C:/Users/Daniel/projects/topmusiciangear/';
const G = require(DIR + 'data/guides.json');
const E = [];
function add(g, pid, h, he, en, es) { E.push({ g, sec: { heading: h, heading_es: he, content: en, content_es: es, products: [pid] } }); }
// ---------- budget-mics: 433, 435, 437, 438, 277 ----------
add('budget-mics', 433, 'Samson Q9U: A Closer Look', 'Samson Q9U: análisis detallado',
'<strong>Broadcast controls without the broadcast invoice.</strong> A dynamic broadcast mic with both XLR and USB-C outputs, plus low-cut and mid-presence switches on the body for shaping voice before it reaches the recording. Built-in shockmount keeps desk thumps out of the take.</p><p>It sits between two worlds: more control than fixed-voicing dynamics, simpler than mics that need an app for everything. Ideal for podcasters who want hardware tone-shaping with one purchase covering USB today and XLR tomorrow.',
'<strong>Controles broadcast sin factura broadcast.</strong> Dinámico broadcast con salidas XLR y USB-C, más interruptores de recorte de graves y presencia media en el cuerpo para moldear la voz antes de la grabación. La suspensión integrada deja los golpes de mesa fuera de la toma.</p><p>Vive entre dos mundos: más control que dinámicos de voz fija, más simple que micros que piden app para todo. Ideal para podcasters que quieren moldear tono por hardware con una compra que cubre USB hoy y XLR mañana.');
add('budget-mics', 435, 'Behringer B 906: A Closer Look', 'Behringer B 906: análisis detallado',
'<strong>Three mics hiding in one budget body.</strong> Switchable low-cut, flat and HF-boost voicings reshape the same dynamic capsule for guitar amps, snare crack or brass bite without touching an EQ. Rugged enough for nightly stage abuse at a price that allows buying pairs.</p><p>It will not replace a characterful boutique dynamic, but as a utility mic that adapts per song, few budget options cover more ground. Buy it when one mic has to solve three different problems across the set.',
'<strong>Tres micros escondidos en un cuerpo económico.</strong> Recorte de graves, plano y realce de agudos conmutables remodelan la misma cápsula dinámica para amplis de guitarra, pegada de caja o mordida de metales sin tocar una EQ. Robusto para el maltrato nocturno a un precio que permite comprar pares.</p><p>No reemplaza un dinámico boutique con carácter, pero como micro utilitario que se adapta por tema, pocas opciones económicas cubren más terreno. Cómpralo cuando un solo micro deba resolver tres problemas distintos en el repertorio.');
add('budget-mics', 437, 'FIFINE K669D: A Closer Look', 'FIFINE K669D: análisis detallado',
'<strong>XLR discipline at a USB-mic price.</strong> A cardioid dynamic in a full-metal body with tripod stand included — the cheapest honest route into an interface-based chain. No software, no drivers, no batteries: voice in, signal out, every time.</p><p>Tone is clean and unhyped rather than broadcast-thick, which actually helps untreated rooms stay intelligible. For creators graduating from headsets who already own or plan an interface, it removes every excuse except practice.',
'<strong>Disciplina XLR a precio de micro USB.</strong> Dinámico cardioide en cuerpo metálico con trípode incluido — la ruta honesta más barata a una cadena con interfaz. Sin software, sin drivers, sin pilas: voz dentro, señal fuera, siempre.</p><p>El tono es limpio y sin hype en vez de broadcast grueso, lo que ayuda a salas sin tratar a seguir inteligibles. Para creadores que suben de auriculares y ya tienen o planean interfaz, elimina cada excusa menos practicar.');
add('budget-mics', 438, 'Samson C01: A Closer Look', 'Samson C01: análisis detallado',
'<strong>Large-diaphragm curiosity at the price of a pizza night.</strong> A 19mm condenser capsule with cardioid pattern and gold-plated XLR that opens the door to real condenser detail — breath, strings, room — for acoustic instruments and soft singers. Needs 48V phantom like any serious condenser.</p><p>Self-noise and build reflect the price, so loud untreated rooms will expose it fast. But as a first window into what condensers hear, nothing cheaper teaches more per euro about mic technique and room treatment.',
'<strong>Curiosidad de diafragma grande al precio de una noche de pizzas.</strong> Cápsula de condensador de 19mm con patrón cardioide y XLR bañado en oro que abre la puerta al detalle real de condensador — respiración, cuerdas, sala — para instrumentos acústicos y cantantes suaves. Pide phantom de 48V como cualquier condensador serio.</p><p>Ruido propio y construcción reflejan el precio, así que salas ruidosas lo delatan rápido. Pero como primera ventana a lo que oye un condensador, nada más barato enseña tanto por euro sobre técnica microfónica y tratamiento de sala.');
add('budget-mics', 277, 'Maono PD200X: A Closer Look', 'Maono PD200X: análisis detallado',
'<strong>The streamer mic that covers both present and future setups.</strong> Dual USB/XLR outputs with headphone monitoring, tap-to-mute and a gain knob on a full-metal body. The cardioid dynamic capsule takes shouting without clipping while rejecting keyboards behind it.</p><p>Buy it for the flexibility more than the flavor: clean modern broadcast tone that stays out of the way, with an upgrade path to XLR interfaces built in. Creators who refuse to buy twice start here.',
'<strong>El micro streamer que cubre el montaje actual y el futuro.</strong> Doble salida USB/XLR con monitoreo por auriculares, silencio táctil y perilla de ganancia en cuerpo metálico. La cápsula dinámica cardioide aguanta gritos sin saturar mientras rechaza teclados detrás.</p><p>Cómpralo por la flexibilidad más que por el sabor: tono broadcast moderno y limpio que no estorba, con ruta de mejora a XLR incluida. Creadores que se niegan a comprar dos veces empiezan aquí.');
// ---------- best-microphone: 50, 194, 321, 297, 291 ----------
add('best-microphone', 50, 'Shure SM58: A Closer Look', 'Shure SM58: análisis detallado',
'<strong>The vocal microphone everything else gets measured against.</strong> Pneumatic shock mount, steel-mesh ball grille and a presence rise tuned for speech intelligibility over loud bands. It survives drops, beer and decades of nightly use that retire lesser mics in months.</p><p>Studio engineers reach past it for nuanced condenser detail, and no one pretends otherwise. But for live vocals, rehearsals and podcast guests, its combination of isolation, durability and price remains the benchmark every rival chases.',
'<strong>El micro de voz contra el que se mide todo lo demás.</strong> Suspensión neumática, rejilla esférica de acero y realce de presencia afinado para inteligibilidad sobre bandas ruidosas. Sobrevive a caídas, cerveza y décadas de uso nocturno que jubilan micros menores en meses.</p><p>Los ingenieros lo saltan por detalle de condensador en estudio, y nadie finge lo contrario. Pero para directo, ensayos e invitados de podcast, su combinación de aislamiento, dureza y precio sigue siendo la referencia que todo rival persigue.');
add('best-microphone', 194, 'Shure MV7+: A Closer Look', 'Shure MV7+: análisis detallado',
'<strong>Broadcast credibility with USB manners.</strong> Hybrid dynamic with USB-C and XLR outputs, touch-panel metering, headphone monitoring and auto-level DSP that keeps inconsistent talkers even. Less gain-hungry than the SM7B, with the XLR path waiting when the setup grows.</p><p>It costs more than mics that sound fine with zero processing, and purists will always prefer the SM7B fully driven. But for creators who publish weekly and cannot re-record, consistency is a feature worth paying for.',
'<strong>Credibilidad broadcast con modales USB.</strong> Dinámico híbrido con salidas USB-C y XLR, medidores táctiles, monitoreo por auriculares y DSP de nivel automático que iguala a locutores inconsistentes. Menos hambriento de ganancia que el SM7B, con la vía XLR esperando cuando el montaje crece.</p><p>Cuesta más que micros que suenan bien sin proceso, y los puristas preferirán siempre el SM7B bien alimentado. Pero para creadores que publican cada semana y no pueden regrabar, la consistencia es una función que vale pagar.');
add('best-microphone', 321, 'Shure SM7dB: A Closer Look', 'Shure SM7dB: análisis detallado',
'<strong>The SM7B for interfaces that ran out of gain.</strong> Identical warm broadcast capsule and voicing switches, with a built-in preamp adding clean +18 or +28 dB before the signal leaves the mic. No Cloudlifter, no FetHead, no extra box and cable in the chain.</p><p>It costs more than the classic and the preamp needs no thought — set it once and forget it. For owners of modest interfaces and portable recorders, it removes the single biggest SM7B headache at the source.',
'<strong>El SM7B para interfaces que se quedaron sin ganancia.</strong> Idéntica cápsula cálida broadcast e interruptores de ecualización, con previo integrado que suma +18 o +28 dB limpios antes de que la señal salga del micro. Sin Cloudlifter, sin FetHead, sin caja ni cable extra en la cadena.</p><p>Cuesta más que el clásico y el previo no pide atención — se ajusta una vez y se olvida. Para dueños de interfaces modestas y grabadoras portátiles, elimina de raíz el mayor dolor de cabeza del SM7B.');
add('best-microphone', 297, 'Rode NT1 Signature Series: A Closer Look', 'Rode NT1 Signature Series: análisis detallado',
'<strong>Flagship silence without the flagship bundle.</strong> The HF6 1-inch capsule at 4 dBA self-noise — quieter than the room in most home studios — with shock mount, pop filter and XLR cable in the box. Neutral with a gentle presence lift that flatters vocals and acoustic instruments without harshness.</p><p>XLR-only operation means an interface is mandatory, unlike USB-equipped rivals. But for pure recorded tone per euro through a proper chain, few condensers argue with it.',
'<strong>Silencio insignia sin bundle insignia.</strong> La cápsula HF6 de 1 pulgada con 4 dBA de ruido propio — más silenciosa que la sala en la mayoría de home studios — con suspensión, antipop y cable XLR en la caja. Neutro con leve realce de presencia que favorece voces y acústicas sin dureza.</p><p>Solo funciona por XLR, así que la interfaz es obligatoria, al contrario que rivales USB. Pero en tono grabado puro por euro a través de una cadena seria, pocos condensadores discuten con él.');
add('best-microphone', 291, 'Audio-Technica AT2020USB-X: A Closer Look', 'Audio-Technica AT2020USB-X: análisis detallado',
'<strong>Studio condenser manners with streamer reflexes.</strong> The AT2020 capsule with 24-bit/96 kHz USB conversion, headphone mix control, capacitive mute and LED ring. Condenser detail and air for voices that outgrow dynamic USB mics, without buying an interface.</p><p>It inherits condenser honesty about rooms: untreated reflections and keyboard clatter come along for the ride. Treated space plus this mic equals the cheapest true studio vocal chain that plugs straight into a laptop.',
'<strong>Modales de condensador de estudio con reflejos de streamer.</strong> La cápsula AT2020 con conversión USB 24 bits/96 kHz, mezcla de auriculares, silencio capacitivo y anillo LED. Detalle y aire de condensador para voces que superan dinámicos USB, sin comprar interfaz.</p><p>Hereda la honestidad del condensador con las salas: reflexiones sin tratar y tecleo vienen incluidos. Espacio tratado más este micro iguala la cadena vocal de estudio más barata que se enchufa directo al portátil.');
const P = require(DIR + 'data/products.json');
for (const e of E) {
  const g = G.find(x => x.id === e.g);
  const s = e.sec;
  const txt = s.content + ' ' + s.content_es;
  if (/\$\d|€\d|£\d/.test(txt)) { console.log('PRICE-SKIP ' + e.g); continue; }
  g.sections.push({ heading: s.heading, heading_es: s.heading_es, content: s.content, content_es: s.content_es, products: s.products });
}
fs.writeFileSync(DIR + 'data/guides.json', JSON.stringify(G, null, 2));
console.log('done, entries: ' + E.length);
module.exports = E;