const fs = require('fs');
const DIR = 'C:/Users/Daniel/projects/topmusiciangear/';
const G = require(DIR + 'data/guides.json');
const E = [];
module.exports = E;
function add(g, pid, h, he, en, es) { E.push({ g, sec: { heading: h, heading_es: he, content: en, content_es: es, products: [pid] } }); }

// ---------- starter-studio: Rokit 7 ----------
add('starter-studio', 20, 'KRK Rokit 7 G5: A Closer Look', 'KRK Rokit 7 G5: análisis detallado',
'<strong>The first monitor should flatter nothing and survive everything.</strong> A bi-amped 7-inch design with Kevlar drivers, onboard DSP room correction and a front-firing port that tolerates placement against untreated bedroom walls. Punchy low end plus detailed highs translate to car stereos and earbuds without second-guessing.</p><p>For a starter studio the G5 matters because it removes the room excuse: measure, correct with DSP, and learn what mixes actually sound like. Not the flattest monitor in its class, but the most forgiving teacher for untreated spaces.',
'<strong>El primer monitor no debe adular nada ni romperse con nada.</strong> Diseño biamplificado de 7 pulgadas con drivers de Kevlar, corrección DSP de sala y puerto frontal que perdona la colocación contra paredes sin tratar. Graves contundentes y agudos detallados que se trasladan al coche y a los auriculares sin dudar.</p><p>Para un estudio inicial el G5 importa porque elimina la excusa de la sala: mide, corrige con DSP y aprende cómo suenan las mezclas de verdad. No es el monitor más plano de su clase, pero sí el maestro más paciente para espacios sin tratar.');

// ---------- budget-mics (7) ----------
add('budget-mics', 431, 'sE Electronics V7: A Closer Look', 'sE Electronics V7: análisis detallado',
'<strong>An SM58-shaped problem solver with a modern capsule inside.</strong> Supercardioid pickup narrows the acceptance angle so wedges and cymbals stay out, while the patented internal shockmount kills handling thumps without an external clip. The all-metal body and gold-plated XLR shrug off the abuse budget mics usually die from.</p><p>Against the SM58 it trades legacy for control: tighter pattern, brighter modern presence, similar indestructibility. Ideal for loud stages where the vocal has to win against guitars and brass.</p>',
'<strong>Un resolvedor con forma de SM58 y cápsula moderna dentro.</strong> El supercardioide estrecha el ángulo para dejar fuera cuñas y platos, mientras la suspensión interna patentada mata los golpes de manejo sin pinza externa. El cuerpo metálico y el XLR bañado en oro aguantan el maltrato que suele matar a los micros baratos.</p><p>Frente al SM58 cambia legado por control: patrón más cerrado, presencia moderna más brillante e igual indestructibilidad. Ideal para escenarios ruidosos donde la voz tiene que ganar a guitarras y metales.');

add('budget-mics', 432, 'Elgato Wave DX: A Closer Look', 'Elgato Wave DX: análisis detallado',
'<strong>A streamer mic designed with a microphone company, not a gaming company.</strong> Lewitt Audio engineered this dynamic XLR capsule for speech: tight cardioid pattern optimized for close talking, internal pop filtering, and output hot enough to skip the booster lesser dynamics demand. No USB, no DSP, no gimmicks — XLR straight to interface.</p><p>It makes sense for creators upgrading from USB who already own an interface: broadcast-adjacent tone, minimal room pickup, and Lewitt voicing at a working price. Not for singers or instruments — pure spoken-word tool.',
'<strong>Un micro de streamer diseñado por una empresa de micros, no de gaming.</strong> Lewitt Audio diseñó esta cápsula dinámica para la voz: cardioide cerrado optimizado para hablar cerca, filtrado antipop interno y salida con nivel suficiente para saltarse el booster que piden otros dinámicos. Sin USB, sin DSP, sin trucos — XLR directo a la interfaz.</p><p>Tiene sentido para creadores que suben de USB y ya tienen interfaz: tono casi broadcast, mínima captación de sala y ecualización Lewitt a precio de trabajo. No para cantantes ni instrumentos — herramienta pura de voz hablada.');

add('budget-mics', 434, 'AKG P120: A Closer Look', 'AKG P120: análisis detallado',
'<strong>The cheapest honest way into large-diaphragm condenser sound.</strong> A true 2/3-inch capsule with switchable bass-cut and a -20 dB pad, so loud guitar cabs and close singers stop being a problem. Rugged metal body that survives backpacks and rehearsal rooms far better than its price suggests.</p><p>Expect budget character, not boutique magic: slightly forward upper mids that help vocals cut, honest detail for acoustic instruments, and noise levels that demand reasonable gain staging. The rational first condenser before committing to expensive capsules.',
'<strong>La vía honesta más barata al sonido de condensador grande.</strong> Cápsula real de 2/3 de pulgada con corte de graves conmutable y pad de -20 dB, así que amplis ruidosos y cantantes cercanos dejan de ser problema. Cuerpo metálico robusto que sobrevive a mochilas y locales mucho mejor de lo que su precio sugiere.</p><p>Espera carácter económico, no magia boutique: medios-altos algo adelantados que ayudan a la voz a cortar, detalle honesto para acústicas y un ruido que pide una ganancia sensata. El primer condensador racional antes de apostar por cápsulas caras.');

add('budget-mics', 436, 'MAONO PD100 Gen2: A Closer Look', 'MAONO PD100 Gen2: análisis detallado',
'<strong>One mic for the desk that keeps changing.</strong> USB and XLR outputs cover streaming today and interface-based recording tomorrow, with 192 kHz/24-bit conversion, tap-to-mute, real-time monitoring and a gain knob on the body. The full-metal shell and cardioid dynamic capsule reject keyboards and room chatter.</p><p>Against single-output rivals it wins on flexibility alone: start plug-and-play, grow into XLR without buying twice. Not a character mic — a clean, modern broadcast voice that stays out of the way.',
'<strong>Un micro para el escritorio que no para de cambiar.</strong> Salidas USB y XLR cubren el streaming de hoy y la grabación con interfaz de mañana, con conversión 192 kHz/24 bits, silencio táctil, monitoreo en tiempo real y perilla de ganancia en el cuerpo. La carcasa metálica y la cápsula dinámica cardioide rechazan teclados y cháchara de la sala.</p><p>Frente a rivales de una sola salida gana solo por flexibilidad: empieza plug-and-play y crece a XLR sin comprar dos veces. No es un micro con carácter — una voz broadcast limpia y moderna que no estorba.');

add('budget-mics', 226, 'Shure Beta 58A: A Closer Look', 'Shure Beta 58A: análisis detallado',
'<strong>The SM58 for singers who fight muddy monitors.</strong> A supercardioid pattern with tighter rear rejection than the SM58, plus a brighter presence peak that cuts through dense rock mixes without pushing fader levels. The pneumatic shock mount and hardened grille survive the same abuse as its famous sibling.</p><p>Choose it over the SM58 when feedback or monitor bleed is the nightly battle: narrower pickup, hotter output, more cut. In quiet acoustic settings the extra brightness can sound edgy — there the SM58 stays king.',
'<strong>El SM58 para cantantes que pelean con monitores embarrados.</strong> Patrón supercardioide con más rechazo trasero que el SM58, más un pico de presencia brillante que corta mezclas densas de rock sin subir faders. La suspensión neumática y la rejilla endurecida aguantan el mismo maltrato que su famoso hermano.</p><p>Elígelo sobre el SM58 cuando el feedback o el sangrado de monitores sea la batalla de cada noche: captación más estrecha, más salida, más corte. En acústicos tranquilos el brillo extra puede sonar filoso — ahí el SM58 sigue siendo rey.');

add('budget-mics', 227, 'Sennheiser e935: A Closer Look', 'Sennheiser e935: análisis detallado',
'<strong>German engineering for voices the SM58 leaves thin.</strong> A cardioid dynamic with a smoother, more open top end than the American classics — present without harshness, warm without mud. Hum-compensating coil shrugs off stage lighting buzz, and the metal body handles drops that end lesser mics.</p><p>It flatters baritones and breathy singers where brighter mics exaggerate sibilance. Slightly less output than modern rivals, so budget a touch more preamp gain. A connoisseur alternative hiding at a working price.',
'<strong>Ingeniería alemana para voces que el SM58 deja finas.</strong> Dinámico cardioide con agudo más abierto y suave que los clásicos americanos — presente sin dureza, cálido sin barro. La bobina anticampos ignora el zumbido de focos, y el cuerpo metálico aguanta caídas que acaban con micros menores.</p><p>Favorece a barítonos y voces susurradas donde los micros brillantes exageran la sibilancia. Algo menos de salida que rivales modernos, así que reserva un poco más de ganancia. Una alternativa de entendido escondida a precio de trabajo.');

add('budget-mics', 228, 'Sennheiser e945: A Closer Look', 'Sennheiser e945: análisis detallado',
'<strong>Supercardioid focus for the loudest stages on a budget.</strong> Tighter than the e935 all around: narrower pickup, stronger rear rejection, and a presence lift voiced to slice through double guitars and cymbals. Same rugged metal construction and hum-bucking coil for buzz-free operation under stage lights.</p><p>Buy it for monitor-heavy rock and metal bills; skip it for quiet jazz trios where its forward character overpowers subtle dynamics. Technique matters — drift off-axis and the level drops fast, which rewards disciplined singers.</p>',
'<strong>Enfoque supercardioide para los escenarios más ruidosos con presupuesto.</strong> Más cerrado que el e935 en todo: captación más estrecha, más rechazo trasero y un realce de presencia afinado para rebanar dobles guitarras y platos. Misma construcción metálica robusta y bobina anticampos para operar sin zumbidos bajo focos.</p><p>Cómpralo para carteles de rock y metal con muchos monitores; sáltalo para tríos tranquilos de jazz donde su carácter frontal arrolla dinámicas sutiles. La técnica importa — sal del eje y el nivel cae rápido, lo que premia a cantantes disciplinados.');

add('budget-mics', 230, 'AKG D5: A Closer Look', 'AKG D5: análisis detallado',
'<strong>Laminated diaphragm, laminated price — serious engineering underneath.</strong> AKG Varimotion capsule with dual shock mounting and integrated wind protection delivers crisp, cut-through vocals that sit above live mixes without harshness. Supercardioid pattern keeps wedges at bay.</p><p>Its character suits rock and pop voices that need articulation more than warmth; thin voices may prefer something fuller. Road-proof metal body and a price that makes a full set of them realistic for working bands.',
'<strong>Diafragma laminado, precio laminado — ingeniería seria debajo.</strong> Cápsula Varimotion de AKG con doble suspensión y protección antiviento integrada entrega voces nítidas que se colocan sobre la mezcla sin dureza. El supercardioide mantiene las cuñas a raya.</p><p>Su carácter va con voces de rock y pop que necesitan articulación más que calidez; las voces finas quizá prefieran algo más lleno. Cuerpo metálico de carretera y un precio que hace realista un juego completo para bandas trabajadoras.');

add('budget-mics', 197, 'Rode PodMic: A Closer Look', 'Rode PodMic: análisis detallado',
'<strong>The broadcast look and sound for less than a night out drums up in gear money.</strong> Tight cardioid dynamic tuned for speech, internal pop filter and shock mount, swing mount included. It flatters thin voices with radio warmth and ignores untreated rooms better than any condenser near its price.</p><p>On a budget-mic shootout list it anchors the value end: less demanding on preamps than flagship dynamics, more focused than cheap condensers. Deep voices wanting more authority graduate to the Procaster; everyone else starts here.',
'<strong>Estética y sonido broadcast por menos de lo que cuesta una noche de copas en equipo.</strong> Dinámico cardioide cerrado ajustado para la voz, filtro antipop y suspensión internos, soporte giratorio incluido. Favorece voces finas con calidez radiofónica e ignora salas sin tratar mejor que ningún condensador cercano a su precio.</p><p>En una comparativa económica ancla el extremo del valor: menos exigente con previos que los dinámicos insignia, más enfocado que los condensadores baratos. Las voces profundas que quieran más autoridad suben al Procaster; el resto empieza aquí.');

add('budget-mics', 277, 'Maono PD200X: A Closer Look', 'Maono PD200X: análisis detallado',
'<strong>Proof that budget no longer means compromise on features.</strong> Dual USB/XLR outputs, headphone monitoring, tap mute and gain knob cover every streaming scenario, while the cardioid dynamic capsule handles shouting gamers without clipping. Metal body and shock mount included where rivals charge extra.</p><p>Sound is clean and modern rather than characterful — a reliable workhorse, not a flavor mic. Perfect first serious mic for creators who might add an interface later and refuse to buy twice.',
'<strong>Prueba de que económico ya no significa renunciar a funciones.</strong> Doble salida USB/XLR, monitoreo por auriculares, silencio táctil y perilla de ganancia cubren cada escenario de streaming, mientras la cápsula dinámica cardioide aguanta gamers gritando sin saturar. Cuerpo metálico y suspensión incluidos donde los rivales cobran extra.</p><p>El sonido es limpio y moderno más que carismático — un caballo de batalla fiable, no un micro con sabor. Primer micro serio perfecto para creadores que quizá sumen interfaz después y se niegan a comprar dos veces.');

// ---------- stage-mics: D5 ----------
add('stage-mics', 230, 'AKG D5: A Closer Look', 'AKG D5: análisis detallado',
'<strong>Cut is a survival trait on loud stages, and the D5 is built around it.</strong> The laminated Varimotion diaphragm stays crisp and articulate when guitars and cymbals push stage volume past reason, while the supercardioid pattern and dual shock mount keep monitors and handling noise out of the vocal. All-metal body, integrated windscreen, zero fuss.</p><p>Next to an SM58 it sounds more immediate and detailed; next to a Beta 58A it gives up some output but costs less. The rational pick for rock and punk bills where intelligibility beats warmth.',
'<strong>El corte es supervivencia en escenarios ruidosos, y el D5 se construye sobre eso.</strong> El diafragma laminado Varimotion se mantiene nítido y articulado cuando guitarras y platos empujan el volumen más allá de la razón, mientras el supercardioide y la doble suspensión dejan fuera monitores y ruidos de manejo. Cuerpo metálico, antiviento integrado, cero líos.</p><p>Junto a un SM58 suena más inmediato y detallado; junto a un Beta 58A cede algo de salida pero cuesta menos. La opción racional para carteles de rock y punk donde la inteligibilidad vence a la calidez.');

// ---------- monitor-setup: K&M stands ----------
add('monitor-setup', 59, 'K&M Monitor Stands: A Closer Look', 'K&M Monitor Stands: análisis detallado',
'<strong>The cheapest meaningful upgrade in monitoring is not a monitor.</strong> Getting tweeters to ear height and decoupling cabinets from resonant desks cleans bass and stereo imaging more than swapping speakers in the same wrong position. Height-adjustable steel columns with floor spikes do exactly that, rock solid.</p><p>German construction means buying once: stable under heavy nearfields, adjustable without tools mid-session, and still standing when the third monitor upgrade arrives. Measure ear height seated, set, forget.</p>',
'<strong>La mejora barata que más se nota en monitoreo no es un monitor.</strong> Subir los tweeters a la altura del oído y desacoplar las cajas de escritorios resonantes limpia graves e imagen estéreo más que cambiar de altavoces en la misma posición mala. Columnas de acero ajustables en altura con puntas de piso hacen justo eso, como una roca.</p><p>La construcción alemana significa comprar una vez: estables bajo nearfields pesados, ajustables sin herramientas en plena sesión, y ahí siguen cuando llega la tercera mejora de monitores. Mide la altura del oído sentado, ajusta, olvida.');

// ---------- channel-strip-plugins: 1176 ----------
add('channel-strip-plugins', 60, 'UA 1176 Classic Limiter Collection: A Closer Look', 'UA 1176 Classic Limiter Collection: análisis detallado',
'<strong>Three shades of the most imitated compressor ever built.</strong> Rev A Bluestripe snarls, Rev E Blackface punches, and the AE Anniversary polishes — all with the all-buttons-in mayhem one click away. Lightning FET attack grabs transients on drums, vocals and bass in ways plugin compressors still chase.</p><p>Inside a channel strip it is the first insert that makes everything downstream easier: level controlled at the source, tone already halfway there. CPU-light by modern standards, and the reason countless mixes start here before touching anything else.',
'<strong>Tres matices del compresor más imitado jamás construido.</strong> Rev A Bluestripe gruñe, Rev E Blackface golpea y el AE Anniversary pule — con la locura del all-buttons-in a un clic. El ataque FET relámpago agarra transitorios de batería, voces y bajo como aún persiguen los compresores por software.</p><p>Dentro de un channel strip es la primera inserción que facilita todo lo demás: nivel controlado en origen, tono medio hecho. Ligero de CPU para estándares actuales, y la razón por la que infinidad de mezclas empiezan aquí antes de tocar nada más.');

// ---------- live-sound-pa ----------
add('live-sound-pa', 105, 'EV ZLX-12P-G2: A Closer Look', 'EV ZLX-12P-G2: análisis detallado',
'<strong>The working band PA that outsells hype with parts availability.</strong> 1000W Class-D through a 12-inch woofer and titanium driver, with FIR-based DSP presets that tune the box to music, club, live or speech in seconds. At 32.7 lb it goes up on poles without a second pair of hands.</p><p>Against boutique boxes it wins on practicality: Bluetooth control, consistent voicing from unit to unit, and service networks that actually stock spares. Not the loudest per dollar — the most dependable.',
'<strong>El PA de banda trabajadora que vende más que el hype con repuestos disponibles.</strong> 1000W Clase-D con woofer de 12 pulgadas y driver de titanio, con presets DSP basados en FIR que ajustan la caja a música, club, directo o voz en segundos. Con 14,8 kg sube al mástil sin un segundo par de manos.</p><p>Frente a cajas boutique gana en practicidad: control Bluetooth, timbre consistente entre unidades y redes de servicio que de verdad tienen repuestos. No el más ruidoso por euro — el más fiable.');

add('live-sound-pa', 493, 'JBL EON712: A Closer Look', 'JBL EON712: análisis detallado',
'<strong>Proven EON lineage with modern DSP manners.</strong> 1300W peak pushing a custom 12-inch woofer to 127 dB, with dbx DriveRack processing — feedback suppression, 8-band parametric EQ, ducking — plus a 3-channel mixer and Bluetooth app control. Doubles as a 55-degree floor wedge for monitor duty.</p><p>It replaces a surprising amount of outboard: mixer, EQ, feedback killer and playback source in one 32 lb box. Buy it when the PA also has to be the rehearsal rig and the wedding DJ rig on alternating weekends.',
'<strong>Linaje EON probado con modales DSP modernos.</strong> 1300W de pico empujando un woofer a medida de 12 pulgadas hasta 127 dB, con procesado dbx DriveRack — supresión de feedback, EQ paramétrica de 8 bandas, ducking — más mezclador de 3 canales y app Bluetooth. Sirve también como cuña de suelo a 55 grados.</p><p>Reemplaza una sorprendente cantidad de cacharros: mezclador, EQ, mata-feedbacks y fuente de playback en una caja de 14,5 kg. Cómpralo cuando el PA tenga que ser también el equipo de ensayo y el de bodas en fines de semana alternos.');

add('live-sound-pa', 109, 'JBL PRX ONE: A Closer Look', 'JBL PRX ONE: análisis detallado',
'<strong>A full PA hiding in a column.</strong> 2000W peak with a 12-inch sub, seven input channels with DSP and 130 dB output from a package one person carries in two trips. Column dispersion fills awkward rooms — weddings, corporate, worship — more evenly than point-source boxes fighting walls.</p><p>The built-in mixer kills the analog snake for small shows: plug mics, instruments and playback straight in, mix from the app out front. Not a replacement for flown line arrays — a replacement for the van full of gear.',
'<strong>Un PA completo escondido en una columna.</strong> 2000W de pico con sub de 12 pulgadas, siete canales de entrada con DSP y 130 dB en un paquete que una persona carga en dos viajes. La dispersión en columna llena salas incómodas — bodas, empresas, iglesias — más parejo que cajas puntuales peleando con paredes.</p><p>El mezclador integrado mata la manguera analógica en bolos pequeños: enchufa micros, instrumentos y playback directo y mezcla desde la app. No reemplaza un line array volado — reemplaza la furgoneta llena de cacharros.');

// ---------- beginner-guitar: Enya ----------
add('beginner-guitar', 295, 'Enya Nova Go Sonic: A Closer Look', 'Enya Nova Go Sonic: análisis detallado',
'<strong>An electric guitar that forgot it needs an amplifier.</strong> Carbon-fiber body shrugs off humidity, knocks and weather, while the built-in 10W speaker with four DSP presets plays clean to lead with zero extra gear. Bluetooth backing tracks, headphone practice and USB-C phone recording complete the anywhere package.</p><p>For beginners the logic is unbeatable: every practice session sounds finished, anywhere, with no setup friction to kill motivation. Purists will want wood and tubes eventually — but nobody quits guitar for lack of inspiration on this one.',
'<strong>Una eléctrica que olvidó que necesita amplificador.</strong> El cuerpo de fibra de carbono se encoge de hombros ante humedad, golpes e intemperie, mientras el altavoz integrado de 10W con cuatro presets DSP va de limpio a lead sin equipo extra. Pistas por Bluetooth, práctica con auriculares y grabación USB-C al teléfono completan el paquete para cualquier sitio.</p><p>Para principiantes la lógica es imbatible: cada sesión suena terminada, en cualquier parte, sin fricción de montaje que mate la motivación. Los puristas querrán madera y válvulas con el tiempo — pero nadie deja la guitarra por falta de inspiración con esta.');

// ---------- best-electric-guitar: Enya ----------
add('best-electric-guitar', 295, 'Enya Nova Go Sonic: A Closer Look', 'Enya Nova Go Sonic: análisis detallado',
'<strong>Carbon fiber changes what an electric guitar is allowed to be.</strong> Immune to humidity swings that wreck setups, light enough to practice for hours, and loud enough unplugged-by-design through its onboard speaker to write songs on the couch. Single-coil neck plus humbucker bridge cover glassy cleans to driven leads.</p><p>In a best-of list it earns its slot on versatility-per-kilo: travel guitar, silent practicer, busking rig and recording sketchpad in one weatherproof body. Traditionalists chasing vintage nitro tone should look at wood — everyone else gets more playing time.',
'<strong>La fibra de carbono cambia lo que una eléctrica puede ser.</strong> Inmune a los cambios de humedad que arruinan ajustes, ligera para practicar horas y suficientemente ruidosa por diseño con su altavoz a bordo para componer en el sofá. Single del mástil más humbucker del puente cubren de limpios cristalinos a leads con drive.</p><p>En una lista de mejores se gana el puesto por versatilidad por kilo: guitarra de viaje, práctica silenciosa, equipo callejero y bloc de grabación en un cuerpo a prueba de clima. Los tradicionalistas del nitro vintage miren madera — el resto saca más horas de toque.');

// ---------- dxr-vs-prx: PRX ONE ----------
add('dxr-vs-prx', 109, 'JBL PRX ONE: A Closer Look', 'JBL PRX ONE: análisis detallado',
'<strong>Seven channels where the DXR has none.</strong> That is the whole argument in one sentence: the PRX ONE carries its mixer everywhere, so solo acts and duos arrive with a column and leave with a mix — no analog desk, no snake, no extra trip. 2000W peak and 130 dB from sub plus column array cover rooms the DXR needs help to fill.</p><p>Against a traditional box it trades throw distance and rider acceptance for total self-sufficiency. One person, two trips, full show — that math wins more weekends than raw SPL ever will.',
'<strong>Siete canales donde la DXR no tiene ninguno.</strong> Ese es todo el argumento en una frase: la PRX ONE lleva su mesa a todas partes, así que solistas y dúos llegan con una columna y salen con una mezcla — sin mesa analógica, sin manguera, sin viaje extra. 2000W de pico y 130 dB de sub más columna cubren salas donde la DXR pide ayuda.</p><p>Frente a una caja tradicional cambia alcance y aceptación en riders por autosuficiencia total. Una persona, dos viajes, show completo — esa cuenta gana más fines de semana que los SPL brutos.');

// ---------- katana-vs-dsl: Katana 50 ----------
add('katana-vs-dsl', 72, 'Boss Katana 50 Gen 3: A Closer Look', 'Boss Katana 50 Gen 3: análisis detallado',
'<strong>The modeling case in this duel, argued on practicality.</strong> Twelve amp characters from acoustic to brown high-gain, five simultaneous effects sections and power scaling from 0.5W to stage-ready 50W. USB recording, headphone practice and a pedalboard-free existence keep the total cost of ownership brutally low.</p><p>It will never sag like glowing bottles, and nobody here pretends otherwise — feel and harmonic bloom stay tube territory. What it does is erase every excuse between the player and daily practice: silent, light, versatile, and loud enough when the drummer shows up.',
'<strong>El caso del modelado en este duelo, defendido desde la practicidad.</strong> Doce caracteres de ampli de acústico a brown high-gain, cinco secciones de efectos simultáneos y escalado de 0,5W a 50W de escenario. Grabación USB, práctica con auriculares y existencia sin pedalera mantienen el coste total brutalmente bajo.</p><p>Nunca cederá como las botellas incandescentes, y aquí nadie finge lo contrario — tacto y flor armónica siguen siendo territorio valvular. Lo que hace es borrar cada excusa entre el guitarrista y la práctica diaria: silencioso, ligero, versátil y suficientemente ruidoso cuando aparece el batería.');

// ---------- home-office: Nova Go + Lava ----------
add('best-guitar-home-office', 295, 'Enya Nova Go Sonic: A Closer Look', 'Enya Nova Go Sonic: análisis detallado',
'<strong>The desk guitar for people whose desk is anywhere.</strong> Carbon body immune to office air-conditioning swings, built-in speaker for instant low-volume playing between calls, and headphone output when the household sleeps. USB-C captures ideas straight to the phone before they evaporate.</p><p>Remote workers get more music in dead minutes than any wood guitar chained to an amp can offer. Ten-hour battery means it lives on the stand, always on, always ready — the opposite of gear that needs a ritual to make a sound.',
'<strong>La guitarra de escritorio para quien su escritorio está en todas partes.</strong> Cuerpo de carbono inmune a los bandazos del aire acondicionado, altavoz integrado para tocar flojito entre llamadas y salida de auriculares cuando la casa duerme. El USB-C captura ideas directo al teléfono antes de que se evaporen.</p><p>Quien teletrabaja saca más música de los minutos muertos que cualquier guitarra de madera encadenada a un ampli. Diez horas de batería significan que vive en el pie, siempre encendida, siempre lista — lo opuesto al equipo que pide un ritual para sonar.');

add('best-guitar-home-office', 296, 'Lava ME 4: A Closer Look', 'Lava ME 4: análisis detallado',
'<strong>An acoustic that behaves like a tablet with strings.</strong> The 3.5-inch touchscreen runs tuner, effects, looper and 100+ backing tracks on the guitar itself — practice with drums, record sketches and share to the cloud without touching a computer. Plek-leveled frets and adjustable truss rod fix the two complaints players had about its predecessor.</p><p>Weatherproof carbon unibody plus two-kilo weight make it the travel-and-couch pick that wooden acoustics cannot match for convenience. Traditional tonewoods still win on pure acoustic voice — but for writing, practicing and posting from anywhere, the workflow gap is enormous.',
'<strong>Una acústica que se comporta como una tablet con cuerdas.</strong> La pantalla táctil de 3,5 pulgadas corre afinador, efectos, looper y más de 100 pistas de fondo en la propia guitarra — practica con batería, graba bocetos y comparte a la nube sin tocar un ordenador. Trastes nivelados por Plek y alma ajustable corrigen las dos quejas que había sobre su antecesora.</p><p>El monocasco de carbono a prueba de clima y dos kilos la hacen la opción de viaje y sofá que las acústicas de madera no igualan en comodidad. Las maderas tradicionales aún ganan en voz acústica pura — pero para componer, practicar y publicar desde cualquier sitio, la brecha de flujo es enorme.');

// ---------- guitar-amps: PD200X + XM8500 (amp-miking angle) ----------
add('best-mic-for-guitar-amps', 277, 'Maono PD200X: A Closer Look', 'Maono PD200X: análisis detallado',
'<strong>Close-miking cabs on a budget without the SM57 tax.</strong> A cardioid dynamic that takes SPL in stride, with USB for scratch takes plus XLR for the real session. Headphone monitoring and tap-mute help position the mic on the grille while listening in real time.</p><p>It will not out-character a boutique ribbon on a vintage stack — but for home studios miking their first amps, it delivers honest, usable cab tone for a fraction of the classic bill. Metal body survives the inevitable stand tip-over.',
'<strong>Microfonear pantallas con presupuesto sin el impuesto SM57.</strong> Un dinámico cardioide que aguanta SPL con calma, con USB para tomas de prueba más XLR para la sesión de verdad. El monitoreo por auriculares y el silencio táctil ayudan a colocar el micro en la rejilla escuchando en tiempo real.</p><p>No superará en carácter a una cinta boutique sobre un stack vintage — pero para home studios microfoneando sus primeros amplis, entrega un tono de pantalla honesto y utilizable por una fracción de la factura clásica. El cuerpo metálico sobrevive al inevitable vuelco del pie.');

add('best-mic-for-guitar-amps', 330, 'Behringer XM8500: A Closer Look', 'Behringer XM8500: análisis detallado',
'<strong>The disposable-price mic you will refuse to throw away.</strong> Presence rise tuned for guitars that need to cut, two-stage pop filtering, shock mounting and a metal tank body with case included. On a cranked combo it behaves like mics five times dearer, shrugging off SPL that would shred condensers.</p><p>Buy three: one lives on the cab permanently, one covers snare duty, one stays in the gig bag as the spare that has saved more shows than any backup plan. At this price the only real risk is underestimating it.',
'<strong>El micro de precio desechable que te negarás a tirar.</strong> Realce de presencia afinado para guitarras que necesitan cortar, filtrado antipop de dos etapas, suspensión y cuerpo tanque metálico con estuche incluido. Sobre un combo a tope se comporta como micros cinco veces más caros, encogiéndose de hombros ante SPL que destrozaría condensadores.</p><p>Compra tres: uno vive fijo en la pantalla, otro cubre la caja y otro queda en la bolsa como el repuesto que ha salvado más conciertos que ningún plan B. A este precio el único riesgo real es subestimarlo.');

// ---------- podcasting: XM8500 ----------
add('best-mic-for-podcasting', 330, 'Behringer XM8500: A Closer Look', 'Behringer XM8500: análisis detallado',
'<strong>The entire argument for starting cheap, in one metal body.</strong> Cardioid moving-coil vocal sound with the presence lift podcast voices need to cut through laptop speakers, plus two-stage pop filtering and shock mounting that embarrasses mics at multiples of the price. XLR-only keeps the chain honest: interface, gain, record.</p><p>Pair it with the cheapest clean interface available and the result passes blind tests against chains costing an order of magnitude more. Spend the savings on acoustic treatment — the mic already solved its part of the equation.',
'<strong>Todo el argumento por empezar barato, en un cuerpo metálico.</strong> Sonido vocal cardioide de bobina móvil con el realce de presencia que piden las voces de podcast para cortar en altavoces de portátil, más filtrado antipop de dos etapas y suspensión que avergüenzan a micros de múltiplos de su precio. Solo XLR mantiene la cadena honesta: interfaz, ganancia, grabar.</p><p>Júntalo con la interfaz limpia más barata y el resultado pasa pruebas ciegas contra cadenas de un orden de magnitud más. Dedica el ahorro a tratamiento acústico — el micro ya resolvió su parte de la ecuación.');

// ---------- daw-beginners: Pro Tools + Cubase ----------
add('best-daw-for-beginners', 113, 'Avid Pro Tools Studio: A Closer Look', 'Avid Pro Tools Studio: análisis detallado',
'<strong>Learn on the software the industry hires for.</strong> Audio editing precision, playlist comping and mix automation that set the professional standard — skills that transfer directly to paid studio work. Surround up to 7.1 and post-production tooling come along even at this tier.</p><p>The subscription stings and the MIDI side trails purpose-built composers tools, so pure beat-makers often start elsewhere. But for recording bands, editing dialogue and mixing songs destined for other studios, fluency here pays rent.',
'<strong>Aprende en el software por el que contrata la industria.</strong> Precisión de edición, comping por playlists y automatización que fijaron el estándar profesional — habilidades que se trasladan directas al trabajo pagado en estudio. Envolvente hasta 7.1 y herramientas de postproducción incluidas hasta en este nivel.</p><p>La suscripción escuece y el lado MIDI va detrás de herramientas de composición nativas, así que los beat-makers puros suelen empezar en otro lado. Pero para grabar bandas, editar diálogos y mezclar temas con destino a otros estudios, la fluidez aquí paga el alquiler.');

add('best-daw-for-beginners', 114, 'Steinberg Cubase Pro 15: A Closer Look', 'Steinberg Cubase Pro 15: análisis detallado',
'<strong>The composer-friendly counterweight to Pro Tools editing.</strong> MIDI editing depth, chord tools, VariAudio pitch correction and scoring that make songwriting and arranging feel native rather than bolted on. MixConsole and audio warp keep it equally serious when songs move to production.</p><p>Sheer depth can overwhelm week-one beginners — the learning curve is real and the interface shows its decades. But musicians who write as they produce grow into it instead of out of it, which is exactly the beginner trap Cubase avoids.',
'<strong>El contrapeso amable con el compositor frente a la edición Pro Tools.</strong> Profundidad MIDI, herramientas de acordes, corrección VariAudio y partituras que hacen nativo componer y arreglar en vez de un añadido. MixConsole y audio warp lo mantienen igual de serio al producir.</p><p>Tanta profundidad puede abrumar la primera semana — la curva existe y la interfaz muestra sus décadas. Pero quien compone mientras produce crece dentro de él en vez de superarlo, que es justo la trampa de principiante que Cubase evita.');

// ---------- beginner-electric: Epiphone + Jet + Nova Go ----------
add('best-beginner-electric-guitar', 465, 'Epiphone Les Paul Special-II E1: A Closer Look', 'Epiphone Les Paul Special-II E1: análisis detallado',
'<strong>Real Les Paul recipe at the lowest possible buy-in.</strong> Solid mahogany body, bolt-on mahogany neck with a comfortable 60s SlimTaper D, and open-coil Alnico humbuckers that snarl convincingly for rock and blues. Tune-o-matic plus stopbar holds tuning through enthusiastic bending.</p><p>Fit and finish vary unit to unit at this price, so try before buying when possible — but the fundamentals (wood, scale, pickups) are honest. The perfect counterweight when every other beginner list only speaks Fender.',
'<strong>Receta Les Paul real al precio de entrada más bajo posible.</strong> Cuerpo macizo de caoba, mástil atornillado de caoba con cómoda D SlimTaper sesentera y humbuckers abiertas de Alnico que gruñen convincentes en rock y blues. Tune-o-matic con cordal aguanta la afinación ante bendings entusiastas.</p><p>Ajustes y acabados varían por unidad a este precio, así que prueba antes de comprar si puedes — pero los fundamentales (madera, escala, pastillas) son honestos. El contrapeso perfecto cuando las demás listas de inicio solo hablan Fender.');

add('best-beginner-electric-guitar', 466, 'Jet Guitars JS-300: A Closer Look', 'Jet Guitars JS-300: análisis detallado',
'<strong>The neck is the headline; the price is the plot twist.</strong> Heat-treated Canadian roasted maple neck and board stay stable through seasons while feeling broken-in from day one, with a bone nut keeping open strings honest. Basswood body, Modern C and 9.5-inch radius keep it friendly while three ceramic single-coils do their Strat thing.</p><p>Brand recognition lags behind the big names, which matters at resale but not at practice time. For pure playing value per euro, few beginner guitars make a stronger case — and the modding platform is solid when skills outgrow stock parts.',
'<strong>El mástil es el titular; el precio es el giro.</strong> Mástil y diapasón de arce canadiense tostado tratado con calor, estable entre estaciones y con tacto rodado desde el día uno, con cejuela de hueso que mantiene honestas las cuerdas al aire. Cuerpo de tilo, C moderna y radio de 9,5 pulgadas lo hacen amable mientras tres single coils cerámicas hacen lo suyo Strat.</p><p>El reconocimiento de marca va detrás de los grandes, que importa al revender pero no al practicar. En valor puro de toque por euro, pocas guitarras de inicio argumentan mejor — y la plataforma de modificaciones es sólida cuando las manos superan las piezas de serie.');

add('best-beginner-electric-guitar', 295, 'Enya Nova Go Sonic: A Closer Look', 'Enya Nova Go Sonic: análisis detallado',
'<strong>The beginner guitar that removes every excuse except practice.</strong> No amp to buy, no cables to trip on, no neighbors to anger: speaker, effects, Bluetooth and headphone practice live in the carbon body. Ten-hour battery and weatherproof construction mean it practices wherever life happens.</p><p>Tone purists will graduate to wood and tubes, and should — but most beginners quit over friction, not tone. Nothing in this guide lowers the barrier between wanting to play and actually playing further than this.',
'<strong>La guitarra de inicio que elimina cada excusa menos practicar.</strong> Sin ampli que comprar, sin cables con que tropezar, sin vecinos que enfadar: altavoz, efectos, Bluetooth y práctica con auriculares viven en el cuerpo de carbono. Diez horas de batería y construcción a prueba de clima significan que practica donde pasa la vida.</p><p>Los puristas del tono se graduarán a madera y válvulas, y deben — pero la mayoría abandona por fricción, no por tono. Nada en esta guía baja más la barrera entre querer tocar y tocar de verdad que esta.');

// ---------- best-bass-amps: Crush Bass 50 ----------
add('best-bass-amps', 484, 'Orange Crush Bass 50: A Closer Look', 'Orange Crush Bass 50: análisis detallado',
'<strong>British analog attitude in a bedroom-friendly box.</strong> A discrete Class A/B output stage — not Class D — gives the 1x12 genuine push-pull feel, with a 2-band active EQ plus sweepable parametric mid for dialing out boxiness. Built-in drive with Blend keeps clean definition under the grit.</p><p>Fifty watts will not cover a loud drummer, and nobody should buy it expecting that. For home, rehearsal and small gigs where character beats sheer volume, few combos make practicing this enjoyable.',
'<strong>Actitud analógica británica en caja de dormitorio.</strong> Una etapa discreta Clase A/B — no Clase D — da al 1x12 auténtica sensación push-pull, con EQ activa de 2 bandas más medio paramétrico barridle para quitar encajonamiento. El drive integrado con Blend mantiene definición limpia bajo la saturación.</p><p>Cincuenta vatios no cubren un batería ruidoso, y nadie debería comprarlo esperando eso. Para casa, ensayo y conciertos pequeños donde el carácter vence al volumen bruto, pocos combos hacen tan disfrutable practicar.');

// ---------- best-pa-speakers: ELX200-15P + PRX915 ----------
add('best-pa-speakers', 495, 'EV ELX200-15P: A Closer Look', 'EV ELX200-15P: análisis detallado',
'<strong>Fifteen inches of low end without the fifteen-inch hernia.</strong> The ELX200-15P stretches the ELX200 formula to serious bass: 15-inch woofer, QuickSmartDSP presets and Bluetooth control in a box that stays manageable for solo loading. Kicks and bass guitars land with physical weight smaller tops only imply.</p><p>It gives up some midrange finesse to the 12-inch sibling and the top-box clarity of premium rivals. Buy the 15 when low-end authority matters more than vocal microscope detail — mobile DJs and bass-heavy bands first in line.',
'<strong>Quince pulgadas de grave sin hernia de quince pulgadas.</strong> El ELX200-15P estira la fórmula ELX200 a graves serios: woofer de 15 pulgadas, presets QuickSmartDSP y control Bluetooth en una caja manejable en solitario. Bombos y bajos caen con peso físico que las cajas pequeñas solo insinúan.</p><p>Cede algo de finura en medios frente a su hermano de 12 y claridad superior frente a rivales premium. Compra el 15 cuando la autoridad en graves importe más que el microscopio vocal — DJs móviles y bandas con bajo primero en la fila.');

add('best-pa-speakers', 496, 'JBL PRX915: A Closer Look', 'JBL PRX915: análisis detallado',
'<strong>Touring-grade sound for crews without touring budgets.</strong> 2000W Class-D driving a 15-inch woofer to 133 dB with dbx DriveRack brains: feedback suppression, parametric EQ, delay and presets, all from an OLED or phone app. Dual handles and 24.1 kg keep it movable without roadies.</p><p>Overkill for coffee shops, exactly right for loud bands and DJs who outgrew entry-level boxes. The price stings once; the reliability pays back every weekend the cheap box would have failed.',
'<strong>Sonido de gira para equipos sin presupuesto de gira.</strong> 2000W Clase-D moviendo un woofer de 15 pulgadas hasta 133 dB con cerebro dbx DriveRack: supresión de feedback, EQ paramétrica, delay y presets, todo desde OLED o app. Doble asa y 24,1 kg lo mantienen movible sin roadies.</p><p>Excesivo para cafés, exacto para bandas ruidosas y DJs que superaron cajas básicas. El precio escuece una vez; la fiabilidad devuelve cada fin de semana que la caja barata habría fallado.');

// ---------- best-analog-mixers: BiG SiX ----------
add('best-analog-mixers', 334, 'SSL BiG SiX: A Closer Look', 'SSL BiG SiX: análisis detallado',
'<strong>A real SSL console shrunk to desktop width.</strong> SuperAnalogue summing, four mic pres with 72 dB of gain, E-Series EQ and channel compression plus the G-Series bus compressor — the complete hit-record signal path without the control room. The 16-in/16-out USB interface makes it the studio centerpiece, not an accessory.</p><p>This is serious money for 16 channels, and nobody needing high counts should look here. But for hybrid studios mixing through real analog summing with total recall via USB, nothing else carries this badge at this size.',
'<strong>Una consola SSL real encogida al escritorio.</strong> Suma SuperAnalogue, cuatro previos de micro con 72 dB de ganancia, EQ serie E y compresión por canal más el compresor de bus serie G — la ruta completa de éxitos sin sala de control. La interfaz USB 16x16 la vuelve el centro del estudio, no un accesorio.</p><p>Es dinero serio por 16 canales, y quien necesite conteos altos mire otro lado. Pero para estudios híbridos que mezclan por suma analógica real con recall total por USB, nada más lleva esta insignia en este tamaño.');

// ---------- budget-pa-systems: EON712 ----------
add('budget-pa-systems', 493, 'JBL EON712: A Closer Look', 'JBL EON712: análisis detallado',
'<strong>The budget box with a pro app watching over it.</strong> 1300W peak and 127 dB from a custom 12-inch woofer, tuned by dbx DriveRack DSP with feedback suppression and 8-band EQ, all remote-controlled over Bluetooth. Doubles as a 55-degree wedge when monitor duty calls.</p><p>Plastic cabinet and a single 12-inch driver set physical limits no DSP overcomes at full tilt — but as the first serious PA for bands graduating from rehearsal rooms, it replaces a rack of outboard while fitting the van and the budget.',
'<strong>La caja económica con una app pro vigilando.</strong> 1300W de pico y 127 dB de un woofer a medida de 12 pulgadas, afinados por DSP dbx DriveRack con supresión de feedback y EQ de 8 bandas, todo controlado por Bluetooth. Sirve como cuña a 55 grados cuando toca monitoraje.</p><p>El gabinete plástico y un solo 12 imponen límites físicos que ningún DSP supera a tope — pero como primer PA serio para bandas que salen del local, reemplaza un rack de cacharros cabiendo en la furgo y el presupuesto.');

// ---------- fender-bass-guide: CV Jazz + Affinity PJ ----------
add('fender-bass-guide', 157, "Squier Classic Vibe '60s Jazz Bass: A Closer Look", "Squier Classic Vibe '60s Jazz Bass: análisis detallado",
'<strong>Sixties Jazz Bass feel without the vintage-market madness.</strong> Fender-designed alnico single-coils with that articulate midrange growl, slim comfortable C neck, and vintage bridge and tuners that complete the illusion. It nails the look, the ergonomics and 90% of the tone for a fraction of a US Fender.</p><p>Purists will still hear the last 10% in the wood and electronics of the real thing. For working players who need the Jazz Bass voice on loud stages without insuring a vintage instrument, this is the rational answer.',
'<strong>Tacto Jazz Bass sesentero sin la locura del mercado vintage.</strong> Single-coils alnico diseñadas por Fender con ese gruñido articulado de medios, mástil en C fino y cómodo, y puente y clavijero vintage que completan la ilusión. Clava estética, ergonomía y el 90% del tono por una fracción de un Fender USA.</p><p>Los puristas aún oirán el 10% restante en la madera y la electrónica del auténtico. Para currantes que necesitan la voz Jazz Bass en escenarios ruidosos sin asegurar un instrumento vintage, esta es la respuesta racional.');

add('fender-bass-guide', 158, 'Squier Affinity Series Precision Bass PJ: A Closer Look', 'Squier Affinity Series Precision Bass PJ: análisis detallado',
'<strong>Two classic basses for the price of none, almost.</strong> Split-coil Precision thump plus Jazz bridge growl in one poplar body: Motown fingerstyle, picked rock and slapped funk all live under one pickguard. Lightweight contours and a comfortable maple neck keep long sets painless.</p><p>Electronics and hardware are honest rather than luxurious — future upgrades are easy and cheap on this platform. As the entry ticket to the Fender bass family, nothing else covers this much stylistic ground per euro.',
'<strong>Dos bajos clásicos por el precio de casi ninguno.</strong> Thump Precision split-coil más gruñido Jazz del puente en un cuerpo de álamo: fingerstyle Motown, rock con púa y funk con slap viven bajo un mismo golpeador. Contornos ligeros y mástil de arce cómodo mantienen indoloros los repertorios largos.</p><p>Electrónica y herrajes son honestos más que lujosos — futuras mejoras fáciles y baratas en esta plataforma. Como entrada a la familia de bajos Fender, nada más cubre tanto terreno estilístico por euro.');

// ---------- active-vs-passive: JRX215 + SRT215 ----------
add('active-vs-passive-pa', 497, 'JBL JRX215: A Closer Look', 'JBL JRX215: análisis detallado',
'<strong>The case for staying passive, in one heavy box.</strong> Dual 15-inch woofers with a 64mm edgewound voice coil move serious air: 250W continuous handling, 1000W peaks and 129 dB without a single power cable to the speaker. Add any power amp and the system scales by simply adding boxes.</p><p>The price is weight and logistics: MDF bulk, external amplification and processing to manage. For venues with installed racks and crews who already own amps, passive remains cheaper per decibel than anything with a power cord.',
'<strong>El alegato por seguir pasivo, en una caja pesada.</strong> Dobles woofers de 15 pulgadas con bobina edgewound de 64mm mueven aire serio: 250W continuos, 1000W de pico y 129 dB sin un solo cable de corriente al altavoz. Suma cualquier etapa y el sistema escala añadiendo cajas.</p><p>El precio es peso y logística: bulto de MDF, amplificación externa y proceso que gestionar. Para locales con racks instalados y equipos que ya tienen etapas, lo pasivo sigue siendo más barato por decibelio que nada con cable de corriente.');

add('active-vs-passive-pa', 502, 'Mackie SRT215: A Closer Look', 'Mackie SRT215: análisis detallado',
'<strong>The case for going active, argued with processing power.</strong> 1600W with a 15-inch woofer and SymX horn hitting 133 dB, plus Advanced Impulse DSP with five voicings, system EQ and a four-channel Bluetooth mixer with an app. One power cable replaces amp racks, crossovers and outboard.</p><p>Complexity is the trade: more menus, more firmware, more that can confuse at 11pm. For mobile operators who mix from the dancefloor on a phone, the all-in-one math beats passive piece by piece.',
'<strong>El alegato por hacerse activo, defendido con proceso.</strong> 1600W con woofer de 15 pulgadas y trompa SymX hasta 133 dB, más DSP Advanced Impulse con cinco ecualizaciones, EQ de sistema y mezclador Bluetooth de cuatro canales con app. Un cable de corriente reemplaza racks de etapas, crossovers y cacharros.</p><p>La complejidad es el peaje: más menús, más firmware, más que puede confundir a las once de la noche. Para operadores móviles que mezclan desde la pista con el teléfono, la cuenta del todo-en-uno gana a lo pasivo pieza a pieza.');

// ---------- best-live-subwoofers: PRX ONE ----------
add('best-live-subwoofers', 109, 'JBL PRX ONE: A Closer Look', 'JBL PRX ONE: análisis detallado',
'<strong>Next to subs that only go boom, the PRX ONE runs the whole show.</strong> A 12-inch sub with 2000W peak under a column array, plus seven channels of mixing with DSP: plug the band straight in and mix from the app, no desk required. Column dispersion covers weddings and corporate rooms evenly where single boxes beam.</p><p>It will not replace a flown rig or keep up with a full rock backline at festival volume — the physics of a single 12-inch sub set that limit. But as the lowest-lugging route to complete, great-sounding shows, few boxes argue back.',
'<strong>Junto a subs que solo retumban, la PRX ONE lleva todo el show.</strong> Un sub de 12 pulgadas con 2000W de pico bajo una columna, más siete canales de mezcla con DSP: enchufa la banda directa y mezcla desde la app, sin mesa. La dispersión en columna cubre bodas y empresas parejo donde las cajas únicas enfocan en haz.</p><p>No reemplaza un rig volado ni aguanta un backline rock completo a volumen de festival — la física de un solo sub de 12 lo impide. Pero como ruta con menos carga hacia conciertos completos y con gran sonido, pocas cajas replican.');
