const fs = require('fs');
const g = JSON.parse(fs.readFileSync('data/guides.json','utf8'));
const idx = g.findIndex(x => x.id === 'best-32-channel-digital-mixers');
const guide = g[idx];

// 1. UPDATE COMPARISON TABLE
const table = guide.sections.find(s => s.isTable);
table.content = '<div class="guide-table-wrapper"><table class="guide-table"><thead><tr><th>Product</th><th>Local I/O (XLR)</th><th>Processing Capacity</th><th>Sample Rate / Latency</th><th>Mix Buses</th><th>Multitrack Recording</th><th>Network Protocol</th></tr></thead><tbody><tr><td>Behringer X32</td><td>32 XLR</td><td>40 channels</td><td>48 kHz / 0.8 ms</td><td>16 aux + LR</td><td>USB 32-track</td><td>AES50</td></tr><tr><td>Midas M32 LIVE</td><td>32 XLR</td><td>40 channels</td><td>48 kHz / 0.8 ms</td><td>16 aux + LR</td><td>Dual SD 32-track</td><td>AES50</td></tr><tr><td>Allen &amp; Heath SQ-6</td><td>32 XLR (recallable)</td><td>48 channels</td><td>96 kHz / 0.7 ms</td><td>36 mix buses</td><td>USB 96-track (SQ-Drive)</td><td>SLink (Dante optional)</td></tr><tr><td>Soundcraft Ui24R</td><td>24 XLR</td><td>24 channels</td><td>48 kHz / ~1 ms</td><td>6 aux + LR</td><td>USB 24-track + SD 2-track</td><td>None</td></tr><tr><td>Yamaha TF3</td><td>24 XLR</td><td>48 channels</td><td>48 kHz / ~1 ms</td><td>20 aux + LR</td><td>USB 34-track</td><td>Dante (NY64-D optional)</td></tr><tr><td>PreSonus StudioLive SE 32R</td><td>32 XLR</td><td>32 channels</td><td>48 kHz / ~1 ms</td><td>16 FlexMix + LR</td><td>USB 32-track + SD 2-track</td><td>Dante (optional)</td></tr><tr><td>Midas M32R LIVE</td><td>16 XLR</td><td>32 channels</td><td>48 kHz / 0.8 ms</td><td>16 aux + LR</td><td>Dual SD 32-track</td><td>AES50</td></tr><tr><td>Mackie DL32SE</td><td>32 XLR</td><td>32 channels</td><td>48 kHz / ~1 ms</td><td>32 mix buses</td><td>USB 32-track</td><td>None</td></tr><tr><td>PreSonus StudioLive 32SC</td><td>32 XLR</td><td>32 channels</td><td>48 kHz / ~1 ms</td><td>16 FlexMix + LR</td><td>USB 32-track + SD 2-track</td><td>Dante (optional)</td></tr></tbody></table></div>';

table.content_es = '<div class="guide-table-wrapper"><table class="guide-table"><thead><tr><th>Producto</th><th>E/S Local (XLR)</th><th>Capacidad de Procesamiento</th><th>Frecuencia de Muestreo / Latencia</th><th>Buses de Mezcla</th><th>Grabacion Multipista</th><th>Protocolo de Red</th></tr></thead><tbody><tr><td>Behringer X32</td><td>32 XLR</td><td>40 canales</td><td>48 kHz / 0,8 ms</td><td>16 aux + LR</td><td>USB 32 pistas</td><td>AES50</td></tr><tr><td>Midas M32 LIVE</td><td>32 XLR</td><td>40 canales</td><td>48 kHz / 0,8 ms</td><td>16 aux + LR</td><td>Dual SD 32 pistas</td><td>AES50</td></tr><tr><td>Allen &amp; Heath SQ-6</td><td>32 XLR (recallables)</td><td>48 canales</td><td>96 kHz / 0,7 ms</td><td>36 buses de mezcla</td><td>USB 96 pistas (SQ-Drive)</td><td>SLink (Dante opcional)</td></tr><tr><td>Soundcraft Ui24R</td><td>24 XLR</td><td>24 canales</td><td>48 kHz / ~1 ms</td><td>6 aux + LR</td><td>USB 24 pistas + SD 2 pistas</td><td>Ninguno</td></tr><tr><td>Yamaha TF3</td><td>24 XLR</td><td>48 canales</td><td>48 kHz / ~1 ms</td><td>20 aux + LR</td><td>USB 34 pistas</td><td>Dante (NY64-D opcional)</td></tr><tr><td>PreSonus StudioLive SE 32R</td><td>32 XLR</td><td>32 canales</td><td>48 kHz / ~1 ms</td><td>16 FlexMix + LR</td><td>USB 32 pistas + SD 2 pistas</td><td>Dante (opcional)</td></tr><tr><td>Midas M32R LIVE</td><td>16 XLR</td><td>32 canales</td><td>48 kHz / 0,8 ms</td><td>16 aux + LR</td><td>Dual SD 32 pistas</td><td>AES50</td></tr><tr><td>Mackie DL32SE</td><td>32 XLR</td><td>32 canales</td><td>48 kHz / ~1 ms</td><td>32 buses de mezcla</td><td>USB 32 pistas</td><td>Ninguno</td></tr><tr><td>PreSonus StudioLive 32SC</td><td>32 XLR</td><td>32 canales</td><td>48 kHz / ~1 ms</td><td>16 FlexMix + LR</td><td>USB 32 pistas + SD 2 pistas</td><td>Dante (opcional)</td></tr></tbody></table></div>';

console.log('Table updated');

// 2. UPDATE FAQ
const faq = guide.sections.find(s => s.isFaq);
faq.content = '<div class="guide-faq-item"><h3>What is the best 24-channel digital mixer for live sound?</h3><p>The Allen &amp; Heath SQ-6 is the best 24-channel mixer for live sound. It has 32 local XLR inputs, processes up to 48 channels at 96 kHz with just 0.7 ms latency, and its SQ-Drive records 96 tracks directly to USB without a computer.</p></div><div class="guide-faq-item"><h3>Which digital mixer has the lowest latency?</h3><p>The Allen &amp; Heath SQ-6 has the lowest latency at 0.7 ms thanks to its 96 kHz FPGA processing engine. Most other mixers in this range operate at 48 kHz with around 0.8-1 ms latency.</p></div><div class="guide-faq-item"><h3>Can I use a 24-channel mixer as a recording interface?</h3><p>Yes. The Yamaha TF3 records 34x34 channels via USB to a DAW. The SQ-6 records 96 tracks via SQ-Drive to a USB hard drive. The Ui24R records 24 tracks via USB and also has dual SD card recording.</p></div><div class="guide-faq-item"><h3>What is the cheapest 32-channel digital mixer?</h3><p>The PreSonus StudioLive SE 32R at around $1,599 is the cheapest 32-channel mixer with 32 recallable XMAX preamps, 16 FlexMix buses, and USB/SD multitrack recording.</p></div><div class="guide-faq-item"><h3>Do I need Dante for my digital mixer?</h3><p>Dante is only necessary if you plan to use digital stage boxes or network multiple mixers. For most bands and small venues, the built-in AES50 or SLink connections are sufficient. The Yamaha TF3 and PreSonus mixers offer Dante as an optional expansion card.</p></div><div class="guide-faq-item"><h3>How many aux buses do I need for monitors?</h3><p>For a standard band with 4-6 monitor mixes, you need at least 8 aux buses. The Behringer X32 has 16, the SQ-6 has 36, and the Yamaha TF3 has 20. If you use in-ear monitors, you may need more buses for separate stereo mixes.</p></div>';

faq.content_es = '<div class="guide-faq-item"><h3>Cual es la mejor mezcladora digital de 24 canales para sonido en vivo?</h3><p>El Allen &amp; Heath SQ-6 es la mejor mezcladora de 24 canales para sonido en vivo. Tiene 32 entradas XLR locales, procesa hasta 48 canales a 96 kHz con solo 0,7 ms de latencia, y su SQ-Drive graba 96 pistas directamente a USB sin necesidad de computadora.</p></div><div class="guide-faq-item"><h3>Que mezcladora digital tiene la latencia mas baja?</h3><p>El Allen &amp; Heath SQ-6 tiene la latencia mas baja con 0,7 ms gracias a su motor de procesamiento FPGA a 96 kHz. La mayoria de las otras mezcladoras en este rango operan a 48 kHz con alrededor de 0,8-1 ms de latencia.</p></div><div class="guide-faq-item"><h3>Puedo usar una mezcladora de 24 canales como interfaz de grabacion?</h3><p>Si. El Yamaha TF3 graba 34x34 canales via USB a un DAW. El SQ-6 graba 96 pistas via SQ-Drive a un disco duro USB. El Ui24R graba 24 pistas via USB y tambien tiene grabacion dual en tarjeta SD.</p></div><div class="guide-faq-item"><h3>Cual es la mezcladora digital de 32 canales mas barata?</h3><p>El PreSonus StudioLive SE 32R por aproximadamente $1.599 es la mezcladora de 32 canales mas barata con 32 preamplificadores XMAX recallables, 16 buses FlexMix y grabacion multipista USB/SD.</p></div><div class="guide-faq-item"><h3>Necesito Dante para mi mezcladora digital?</h3><p>Dante solo es necesario si planeas usar cajas de escenario digitales o conectar multiples mezcladoras en red. Para la mayoria de bandas y salas pequenas, las conexiones AES50 o SLink integradas son suficientes. El Yamaha TF3 y las mezcladoras PreSonus ofrecen Dante como tarjeta de expansion opcional.</p></div><div class="guide-faq-item"><h3>Cuantos buses aux necesito para monitores?</h3><p>Para una banda estandar con 4-6 mezclas de monitores, necesitas al menos 8 buses aux. El Behringer X32 tiene 16, el SQ-6 tiene 36 y el Yamaha TF3 tiene 20. Si usas in-ear monitors, puedes necesitar mas buses para mezclas estereo separadas.</p></div>';

console.log('FAQ updated');

fs.writeFileSync('data/guides.json', JSON.stringify(g, null, 2), 'utf8');
console.log('Saved guides.json');
