const fs = require('fs');
const t = fs.readFileSync('C:/Users/Daniel/projects/topmusiciangear/guides/best-multi-effects-pedals.html', 'utf8');
const e = fs.readFileSync('C:/Users/Daniel/projects/topmusiciangear/guides/best-multi-effects-pedals_es.html', 'utf8');
const chk = (f, s, src) => console.log(f + ' [' + s.slice(0, 40) + '] = ' + (src.includes(s) ? 'OK' : 'MISSING'));
chk('EN', 'LCD + knobs, 3 touch footswitches', t);
chk('EN', 'Analog / DSP (trails)', t);
chk('EN', '443 x 220 x 67 mm', t);
chk('EN', 'DC 12V (3A)', t);
chk('EN', '8 footswitches + expression, knobs', t);
chk('EN', 'Needs external switches/pedal for full control', t);
chk('EN', 'Requires 12V/3A dedicated supply', t);
chk('EN', 'up to 8 simultaneous blocks', t);
chk('EN', 'Up to 8 blocks + IR', t);
chk('ES', 'Pantalla compacta para edición profunda', e);
chk('ES', 'Requiere fuente dedicada 12V/3A', e);
chk('ES', 'hasta 8 bloques simultáneos', e);
chk('ES', 'El ME-90 y el Flex Prime lideran', e);
chk('ES', 'puerta de entrada perfecta', e);
chk('EN', ' посадirect-workflow', t);
