const fs = require('fs');
const DIR = 'C:/Users/Daniel/projects/topmusiciangear/';
let bad = 0;
const ck = (c, n) => { console.log((c ? 'ok ' : 'FAIL ') + n); if (!c) bad++; };
[['guides/best-live-subwoofers.html', 0], ['guides/best-live-subwoofers_es.html', 0]].forEach(([f]) => {
  const h = fs.readFileSync(DIR + f, 'utf8');
  let i = -1, last = '';
  while ((i = h.indexOf('<table class="guide-comp-table"', i + 1)) >= 0) last = h.slice(i, h.indexOf('</table>', i));
  const ths = (last.match(/<th>/g) || []).length;
  const tds = (last.match(/<td/g) || []).length;
  ck(ths === 8 && tds === 88, f + ' th=' + ths + ' td=' + tds);
  ck(!last.includes('undefined'), f + ' no undefined');
});
const en = fs.readFileSync(DIR + 'guides/best-live-subwoofers.html', 'utf8');
['TS18S', 'EON718S', '(each)'].forEach(n => ck(en.includes(n), 'EN has ' + n));
ck(!en.includes('PRX ONE'), 'EN PRX ONE gone');
const es = fs.readFileSync(DIR + 'guides/best-live-subwoofers_es.html', 'utf8');
ck(!es.includes('PRX ONE'), 'ES PRX ONE gone');
ck(es.includes('(cada uno)'), 'ES cada uno');
process.exit(bad ? 1 : 0);
